// AUTO-GENERATED by tauri-specta. DO NOT EDIT.

// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE, Channel } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	start: (pairedDevices: PairedDeviceInfo[], networkOptions: {
	customBootstrapNodes?: string[],
	discoveryMode?: DiscoveryMode,
	autoDiscoverLanHelpers?: boolean,
	provideLanHelper?: boolean,
	/**
	 *  公网可达性：允许在已知公网中继上建立 reservation 使本机可被跨网直达。
	 * 
	 *  与 discovery_mode 正交——LanOnly 只管"不主动连接内置公网引导"，
	 *  经 LAN Helper 学到的公网中继仍受本开关控制。关闭 = 严格局域网，
	 *  跨网可达仅剩 LAN Helper 转发路径（依赖打洞，可能不可用）。
	 */
	publicReachability?: boolean,
} | null) => __TAURI_INVOKE<null>("start", { pairedDevices, networkOptions }),
	shutdown: () => __TAURI_INVOKE<null>("shutdown"),
	listDevices: (filter: "all" | "connected" | "paired" | null) => __TAURI_INVOKE<DeviceListResult>("list_devices", { filter }),
	getNetworkStatus: () => __TAURI_INVOKE<NetworkStatus>("get_network_status"),
	/**  下载并安装应用更新（桌面端） */
	installUpdate: (url: string, isForce: boolean) => __TAURI_INVOKE<null>("install_update", { url, isForce }),
	listInboxItems: (includeArchived: boolean) => __TAURI_INVOKE<InboxItemSummary[]>("list_inbox_items", { includeArchived }),
	/**
	 *  检索收件箱。`limit` 默认 20，`include_archived` 默认 false。
	 * 
	 *  数据库未注入时由 Tauri State 注入机制直接返回错误（不会 panic）。
	 */
	searchInbox: (query: string, limit: number | null, includeArchived: boolean | null) => __TAURI_INVOKE<InboxSearchHit[]>("search_inbox", { query, limit, includeArchived }),
	getInboxItemDetail: (itemId: string) => __TAURI_INVOKE<({
	files: InboxItemFileEntry[],
	transfer: TransferProjection | null,
}) & (InboxItemSummary) | null>("get_inbox_item_detail", { itemId }),
	getInboxItemByTransferSessionId: (sessionId: string) => __TAURI_INVOKE<({
	files: InboxItemFileEntry[],
	transfer: TransferProjection | null,
}) & (InboxItemSummary) | null>("get_inbox_item_by_transfer_session_id", { sessionId }),
	repairMissingInboxItems: () => __TAURI_INVOKE<InboxItemDetail[]>("repair_missing_inbox_items"),
	openInboxItem: (itemId: string, fileId: number | null) => __TAURI_INVOKE<null>("open_inbox_item", { itemId, fileId }),
	showInboxItemInFolder: (itemId: string, fileId: number | null) => __TAURI_INVOKE<null>("show_inbox_item_in_folder", { itemId, fileId }),
	exportInboxItem: (itemId: string, destinationDir: string) => __TAURI_INVOKE<null>("export_inbox_item", { itemId, destinationDir }),
	archiveInboxItem: (itemId: string, archived: boolean) => __TAURI_INVOKE<null>("archive_inbox_item", { itemId, archived }),
	deleteInboxItem: (itemId: string, deleteLocalFiles: boolean) => __TAURI_INVOKE<null>("delete_inbox_item", { itemId, deleteLocalFiles }),
	/**  从系统 keychain 初始化设备身份，不再要求用户输入 Stronghold 密码。 */
	initializeIdentity: () => __TAURI_INVOKE<IdentityState>("initialize_identity"),
	/**  生成新的 Ed25519 密钥对（protobuf 编码，与存量 keychain 格式兼容）。 */
	generateKeypair: () => __TAURI_INVOKE<number[]>("generate_keypair"),
	/**  注册密钥对到 Tauri state，并在桌面端写入系统 keychain。 */
	registerKeypair: (keypair: number[]) => __TAURI_INVOKE<string>("register_keypair", { keypair }),
	/**  读取持久化的设备名（onboarding 完成前为 `None`）。 */
	getDeviceName: () => __TAURI_INVOKE<string | null>("get_device_name"),
	/**
	 *  设置设备名并持久化。
	 * 
	 *  仅写入 `device_config.json`。要让新名字通过 identify 协议的 `agent_version`
	 *  重新广播，前端在本命令返回后自己调 `shutdown` + `start`（前端持有
	 *  paired_devices + network_options 上下文）。
	 * 
	 *  `name = None`（或空串/纯空白）清空，回退到系统 hostname。
	 */
	setDeviceName: (name: string | null) => __TAURI_INVOKE<null>("set_device_name", { name }),
	/**  生成配对码 */
	generatePairingCode: (expiresInSecs: number | null) => __TAURI_INVOKE<PairingCodeInfo>("generate_pairing_code", { expiresInSecs }),
	/**  通过配对码查询对端设备信息 */
	getDeviceInfo: (code: string) => __TAURI_INVOKE<DeviceInfo>("get_device_info", { code }),
	/**
	 *  向对端发起配对请求
	 * 
	 *  配对成功后自动添加到已配对设备，并 emit `paired-device-added` 事件通知前端。
	 * 
	 *  `peer_id` 为 base58 字符串，`addrs` 为 multiaddr 字符串列表，由命令内部解析为
	 *  内核 newtype，方便通过 specta 生成 TypeScript bindings（内核类型本身不实现
	 *  `specta::Type`）。
	 */
	requestPairing: (peerId: string, method: PairingMethod, addrs: string[] | null) => __TAURI_INVOKE<PairingResponse>("request_pairing", { peerId, method, addrs }),
	/**
	 *  处理收到的配对请求（接受/拒绝）
	 * 
	 *  接受配对后自动添加到已配对设备，并 emit `paired-device-added` 事件通知前端。
	 */
	respondPairingRequest: (pendingId: number, method: PairingMethod, response: PairingResponse) => __TAURI_INVOKE<null>("respond_pairing_request", { pendingId, method, response }),
	/**
	 *  取消与指定设备的配对（同步更新运行时状态）
	 * 
	 *  `peer_id` 为 base58 字符串，由命令内部解析为 `NodeId`。
	 */
	removePairedDevice: (peerId: string) => __TAURI_INVOKE<null>("remove_paired_device", { peerId }),
	/**  更新已配对设备的可信策略。 */
	updatePairedDevicePolicy: (peerId: string, trustLevel: DeviceTrustLevel, receivePolicy: {
	autoAccept: boolean,
	requireConfirmation: boolean,
	maxTransferBytes?: number | null,
	allowDirectories: boolean,
	allowRelayAutoAccept: boolean,
	saveBehavior?: ReceiveSaveBehavior,
	defaultSaveLocation?: string | null,
	allowMcpSendToDevice: boolean,
	/**
	 *  允许 MCP/AI 代该来源设备处置入站 offer（接受或拒绝）。
	 * 
	 *  默认 false。与发送侧 `allow_mcp_send_to_device` **刻意不对称**：代收会往磁盘写入、
	 *  风险更高，故即便对 Owned 设备也需用户逐设备显式开启（发送侧则随信任级别自动派生）。
	 *  只能由用户在 app 的设备信任策略中开启，agent 无任何写权限——防止自我提权、静默代收。
	 */
	allowMcpAcceptFromDevice?: boolean,
	expiresAt?: number | null,
} | null) => __TAURI_INVOKE<PairedDeviceInfo>("update_paired_device_policy", { peerId, trustLevel, receivePolicy }),
	scanSources: (sources: FileSource[]) => __TAURI_INVOKE<ScannedSourceResult[]>("scan_sources", { sources }),
	prepareSend: (files: EnumeratedFile[], onProgress: Channel<PrepareProgressEvent>) => __TAURI_INVOKE<PreparedTransferResult>("prepare_send", { files, onProgress }),
	startSend: (preparedId: string, peerId: string, peerName: string, selectedFileIds: number[]) => __TAURI_INVOKE<StartSendResult>("start_send", { preparedId, peerId, peerName, selectedFileIds }),
	acceptReceive: (sessionId: string, saveLocation: CoreSaveLocation) => __TAURI_INVOKE<null>("accept_receive", { sessionId, saveLocation }),
	rejectReceive: (sessionId: string) => __TAURI_INVOKE<null>("reject_receive", { sessionId }),
	cancelSend: (sessionId: string) => __TAURI_INVOKE<null>("cancel_send", { sessionId }),
	cancelReceive: (sessionId: string) => __TAURI_INVOKE<null>("cancel_receive", { sessionId }),
	getTransferProjections: () => __TAURI_INVOKE<TransferProjection[]>("get_transfer_projections"),
	/**  发送方向会话的源文件绝对路径（「重新发送」重建载荷用；接收方向返回空列表）。 */
	getTransferSourcePaths: (sessionId: string) => __TAURI_INVOKE<string[]>("get_transfer_source_paths", { sessionId }),
	deleteTransferSession: (sessionId: string) => __TAURI_INVOKE<null>("delete_transfer_session", { sessionId }),
	clearTransferHistory: () => __TAURI_INVOKE<null>("clear_transfer_history"),
	pauseTransfer: (sessionId: string) => __TAURI_INVOKE<null>("pause_transfer", { sessionId }),
	resumeTransfer: (sessionId: string) => __TAURI_INVOKE<ResumeTransferResult>("resume_transfer", { sessionId }),
	/**
	 *  设置全局「暂停接收」。`true`=暂停：节点保持在线可发现、配对不受影响，但对新 offer
	 *  自动婉拒；`false`=恢复：新 offer 照常按既有策略处理。同步托盘文案并广播
	 *  `receiving-paused-changed` 事件。
	 */
	setReceivingPaused: (paused: boolean) => __TAURI_INVOKE<null>("set_receiving_paused", { paused }),
	/**  查询当前是否暂停接收（节点未启动视为未暂停）。 */
	isReceivingPaused: () => __TAURI_INVOKE<boolean>("is_receiving_paused"),
	/**
	 *  真正退出应用。
	 * 
	 *  关闭语义由前端 `onCloseRequested` 拦截：`closeBehavior=quit` 或首次对话框选「退出」
	 *  时由前端显式调用本命令，确保进程退出（仅 `hide()` 不退出；macOS 关最后一个窗口默认
	 *  也不退出）。托盘「退出」走 Rust 侧 `app.exit(0)`，不经本命令。
	 */
	quitApp: () => __TAURI_INVOKE<void>("quit_app"),
	/**  应用当前 locale：更新 rust-i18n 全局 locale 并即时重绘托盘菜单文案。 */
	setLocale: (locale: string) => __TAURI_INVOKE<null>("set_locale", { locale }),
	/**  查询 MCP Server 当前状态 */
	getMcpStatus: () => __TAURI_INVOKE<McpStatus>("get_mcp_status"),
	/**
	 *  启动 MCP Server
	 * 
	 *  `port` 为可选参数，默认 19527。
	 */
	startMcpServer: (port: number | null) => __TAURI_INVOKE<McpStatus>("start_mcp_server", { port }),
	/**  停止 MCP Server */
	stopMcpServer: () => __TAURI_INVOKE<McpStatus>("stop_mcp_server"),
	/**  前端根处理器 mount 时调用：标记就绪并取走冷启动期间缓冲的外部打开路径。 */
	takePendingExternalOpen: () => __TAURI_INVOKE<string[]>("take_pending_external_open"),
};

/** Events */
export const events = {
	devicesChanged: makeEvent<DevicesChanged>("devices-changed"),
	externalFileOpen: makeEvent<ExternalFileOpen>("external-file-open"),
	networkStatusChanged: makeEvent<NetworkStatusChanged>("network-status-changed"),
	pairedDeviceAdded: makeEvent<PairedDeviceAdded>("paired-device-added"),
	pairingRequestReceived: makeEvent<PairingRequestReceived>("pairing-request-received"),
	receivingPausedChanged: makeEvent<ReceivingPausedChanged>("receiving-paused-changed"),
	transferAccepted: makeEvent<TransferAccepted>("transfer-accepted"),
	transferComplete: makeEvent<TransferComplete>("transfer-complete"),
	transferDbError: makeEvent<TransferDbError>("transfer-db-error"),
	transferFailed: makeEvent<TransferFailed>("transfer-failed"),
	transferOffer: makeEvent<TransferOffer>("transfer-offer"),
	transferPaused: makeEvent<TransferPaused>("transfer-paused"),
	transferProgress: makeEvent<TransferProgress>("transfer-progress"),
	transferProjectionUpdate: makeEvent<TransferProjectionUpdate>("transfer-projection-update"),
	transferRejected: makeEvent<TransferRejected>("transfer-rejected"),
	transferResumed: makeEvent<TransferResumed>("transfer-resumed"),
	trayOpenReceiveFolder: makeEvent<TrayOpenReceiveFolder>("tray-open-receive-folder"),
	trayOpenSettings: makeEvent<TrayOpenSettings>("tray-open-settings"),
};

/* Types */
/**
 *  前端可见的错误结构体 —— [`AppError`] 在 specta 里被映射成这个形状，
 *  与 [`AppError::serialize`] 真正写出的 JSON 完全一致。
 */
export type AppErrorPayload = {
	kind: string,
	message: string,
};

export type BootstrapCandidateSource = "builtInPublic" | "userCustom" | "mdnsLanHelper" | 
/**  运行时经 identify 学到的基础设施节点（如 LanOnly 下经 LAN Helper 认识的公网中继） */
"learned";

export type CandidateSourceStatus = {
	source: BootstrapCandidateSource,
	count: number,
};

/**  连接类型。 */
export type ConnectionType = "lan" | "dcutr" | "relay";

/**
 *  接收端保存位置（host-agnostic）。
 * 
 *  core 内部统一用此类型，避免把 `entity::SaveLocation`（SeaORM 实体细节）
 *  暴露到公共 API 上。DB 边界用 [`From`] 与 `entity::SaveLocation` 双向转换。
 */
export type CoreSaveLocation = 
/**  文件系统绝对路径（桌面）或 `Paths.document` 子路径（移动端）。 */
{ type: "path"; path: string };

/**  统一的设备输出类型。 */
export type Device = {
	peerId: string,
	status: DeviceStatus,
	connection: ConnectionType | null,
	latency: number | null,
	isPaired: boolean,
	trustLevel: DeviceTrustLevel | null,
	receivePolicy: DeviceReceivePolicy | null,
	trustConfirmed: boolean | null,
} & OsInfo;

/**  设备过滤器 */
export type DeviceFilter = "all" | "connected" | "paired";

/**  查询设备信息的返回类型 */
export type DeviceInfo = {
	/**  节点身份 NodeId（base58 字符串） */
	peerId: string,
	codeRecord: ShareCodeRecord,
};

/**  设备列表查询结果。 */
export type DeviceListResult = {
	devices: Device[],
	total: number,
};

/**
 *  可信设备接收策略。
 * 
 *  字段保持 host-neutral：保存位置使用字符串表达的 host 路径，桌面端解释为绝对路径，
 *  移动端后续可解释为应用文档目录下的子路径。
 */
export type DeviceReceivePolicy = {
	autoAccept: boolean,
	requireConfirmation: boolean,
	maxTransferBytes?: number | null,
	allowDirectories: boolean,
	allowRelayAutoAccept: boolean,
	saveBehavior?: ReceiveSaveBehavior,
	defaultSaveLocation?: string | null,
	allowMcpSendToDevice: boolean,
	/**
	 *  允许 MCP/AI 代该来源设备处置入站 offer（接受或拒绝）。
	 * 
	 *  默认 false。与发送侧 `allow_mcp_send_to_device` **刻意不对称**：代收会往磁盘写入、
	 *  风险更高，故即便对 Owned 设备也需用户逐设备显式开启（发送侧则随信任级别自动派生）。
	 *  只能由用户在 app 的设备信任策略中开启，agent 无任何写权限——防止自我提权、静默代收。
	 */
	allowMcpAcceptFromDevice?: boolean,
	expiresAt?: number | null,
};

/**  设备状态。 */
export type DeviceStatus = "online" | "offline";

/**  已配对设备信任等级。 */
export type DeviceTrustLevel = "owned" | "collaborator" | "temporary" | "blocked";

export type DevicesChanged = Device[];

export type DiscoveryMode = "auto" | "lanOnly";

/**
 *  目录遍历后的扁平化文件条目
 * 
 *  同时用于 `scan_sources` 命令返回和 `prepare_send` 命令输入，
 *  因此同时派生 Serialize + Deserialize。
 */
export type EnumeratedFile = {
	/**  文件名 */
	name: string,
	/**  相对路径（Unix 风格 `/` 分隔符） */
	relativePath: string,
	/**  文件来源 */
	source: FileSource,
	/**  文件大小 */
	size: number,
};

/**
 *  外部「用 SwarmDrop 打开」文件/文件夹后归一化的本地绝对路径列表。
 *  事件名 `"external-file-open"`，前端根处理器据此扫描并跳转选设备屏。
 */
export type ExternalFileOpen = {
	paths: string[],
};

export type FileProgressInfo = {
	fileId: number,
	name: string,
	size: number,
	transferred: number,
	status: FileTransferStatus,
};

/**  文件来源：标准文件系统路径 */
export type FileSource = 
/**  标准文件系统路径 */
{ type: "path"; path: string };

export type FileTransferStatus = "pending" | "transferring" | "completed";

export type IdentityState = {
	keypair: number[],
	deviceId: string,
	pairedDevices: PairedDeviceInfo[],
	created: boolean,
};

/**  收件箱内容类型。 */
export type InboxContentKind = "files" | "text" | "clipboard" | "bundle";

/**  搜索命中条目下的文件标识（供下钻定位）。 */
export type InboxHitFile = {
	name: string,
	relativePath: string,
};

/**  收件箱详情 DTO。 */
export type InboxItemDetail = {
	files: InboxItemFileEntry[],
	transfer: TransferProjection | null,
} & InboxItemSummary;

/**  收件箱文件 DTO。 */
export type InboxItemFileEntry = {
	id: number,
	transferFileId: number | null,
	relativePath: string,
	name: string,
	size: number,
	checksum: string,
	localPath: string,
	missing: boolean,
};

/**  收件箱列表条目 DTO。 */
export type InboxItemSummary = {
	id: string,
	transferSessionId: string | null,
	sourcePeerId: string,
	sourceName: string,
	sourceKind: InboxSourceKind,
	contentKind: InboxContentKind,
	title: string,
	itemCount: number,
	totalSize: number,
	rootPath: string | null,
	contentHash: string | null,
	receivedAt: number,
	lastOpenedAt: number | null,
	archivedAt: number | null,
	deletedAt: number | null,
	missing: boolean,
};

/**  收件箱搜索命中（item 粒度）。 */
export type InboxSearchHit = {
	id: string,
	title: string,
	sourceName: string,
	itemCount: number,
	rootPath: string | null,
	receivedAt: number,
	/**  命中所在文本的片段（在 Rust 端按子串位置切窗口生成）。 */
	snippet: string,
	/**  该条目下的文件（文件名 + 相对路径），供 get_inbox_file 下钻。 */
	files: InboxHitFile[],
};

/**  收件箱来源类型。 */
export type InboxSourceKind = "paired_device" | "share_code" | "mcp" | "unknown";

/**  MCP Server 状态返回值 */
export type McpStatus = {
	running: boolean,
	addr: string | null,
};

export type NetworkRuntimeConfig = {
	customBootstrapNodes?: string[],
	discoveryMode?: DiscoveryMode,
	autoDiscoverLanHelpers?: boolean,
	provideLanHelper?: boolean,
	/**
	 *  公网可达性：允许在已知公网中继上建立 reservation 使本机可被跨网直达。
	 * 
	 *  与 discovery_mode 正交——LanOnly 只管"不主动连接内置公网引导"，
	 *  经 LAN Helper 学到的公网中继仍受本开关控制。关闭 = 严格局域网，
	 *  跨网可达仅剩 LAN Helper 转发路径（依赖打洞，可能不可用）。
	 */
	publicReachability?: boolean,
};

/**  网络状态快照。 */
export type NetworkStatus = {
	status: NodeStatus,
	peerId: string | null,
	listenAddrs: string[],
	natStatus: string,
	publicAddr: string | null,
	connectedPeers: number,
	discoveredPeers: number,
	/**  Relay 中继是否就绪（至少有一个中继节点已连接）。 */
	relayReady: boolean,
	/**
	 *  公网可达：持有公网范围中继的活跃 reservation，或已确认公网直达地址。
	 *  false = 仅局域网可达（跨网设备无法直接访问本机）。
	 */
	publicReachable: boolean,
	/**  公网可达性设置的回显（host 侧检测"设置已变更需重启"用）。 */
	publicReachabilityEnabled: boolean,
	/**  当前已连接的中继节点 NodeId 列表。 */
	relayPeers: string[],
	/**  是否至少有一个引导节点已连接。 */
	bootstrapConnected: boolean,
	/**  当前发现模式。 */
	discoveryMode: DiscoveryMode,
	/**  是否自动发现局域网协助节点。 */
	autoDiscoverLanHelpers: boolean,
	/**  本设备是否配置为提供局域网协助能力。 */
	localLanHelperEnabled: boolean,
	/**  本设备当前是否正在作为局域网协助节点运行。 */
	localLanHelperRunning: boolean,
	/**  Relay Server 是否启用。 */
	relayServerEnabled: boolean,
	/**  LAN Helper 可公告地址。 */
	lanHelperAdvertisedAddrs: string[],
	/**  已发现的局域网协助节点数量。 */
	lanHelperCount: number,
	/**  候选总数。 */
	bootstrapCandidateCount: number,
	/**  按来源聚合的候选数量。 */
	candidateSources: CandidateSourceStatus[],
	/**  当前 relay peer 的候选来源。 */
	relaySource: BootstrapCandidateSource | null,
};

export type NetworkStatusChanged = NetworkStatus;

/**  节点运行状态。 */
export type NodeStatus = "running" | "stopped";

/**  Offer 被拒绝的原因。 */
export type OfferRejectReason = { type: "not_paired" } | { type: "user_declined" } | { type: "policy_rejected" } | 
/**  接收方处于全局「暂停接收」状态，婉拒新 offer。 */
{ type: "receiving_paused" };

/**
 *  设备操作系统信息。
 * 
 *  `hostname` 是系统主机名（运行时取，桌面端通常是机器名，移动端通常拿不到）；
 *  `name` 是用户在 onboarding / 设置里起的名字（持久化，host 注入），UI 显示按
 *  `name.as_deref().unwrap_or(&hostname)` 回退。
 */
export type OsInfo = {
	/**  用户起的设备名；缺省时回退到 `hostname`。 */
	name?: string | null,
	hostname: string,
	os: string,
	platform: string,
	arch: string,
	capabilities?: string[],
};

export type PairedDeviceAdded = PairedDeviceInfo;

/**  已配对设备信息。 */
export type PairedDeviceInfo = {
	peerId: string,
	pairedAt: number,
	trustLevel?: DeviceTrustLevel,
	receivePolicy?: DeviceReceivePolicy,
	trustConfirmed?: boolean,
} & OsInfo;

export type PairingCodeInfo = {
	code: string,
	createdAt: string,
	expiresAt: string,
};

/**
 *  配对方式。
 * 
 *  `Code` 携带分享码作凭证；`Direct` 为局域网直连（授权依据是「对端在本机 mDNS
 *  多播域内」）。未来的邀请链接机制会新增 `Invite` 变体（扩展位，预留于此）。
 */
export type PairingMethod = { type: "code"; code: string } | { type: "direct" };

/**  配对被拒绝的原因。 */
export type PairingRefuseReason = { type: "user_rejected" };

export type PairingRequest = {
	osInfo: OsInfo,
	timestamp: number,
	method: PairingMethod,
};

/**
 *  配对请求 payload：原 core 事件含 PeerId（非 specta-friendly），在此 host 层
 *  投影成 `String`，并把 `request` 字段 flatten 摊开（保持原 wire 形状）。
 */
export type PairingRequestPayload = {
	peerId: string,
	pendingId: number,
} & PairingRequest;

export type PairingRequestReceived = PairingRequestPayload;

export type PairingResponse = { status: "success" } | { status: "refused"; reason: PairingRefuseReason };

/**  `prepare_send` 的 hash 进度事件 */
export type PrepareProgressEvent = {
	/**  用于区分并发 prepare（多用户在不同会话同时调用） */
	preparedId: string,
	/**  当前正在 hash 的文件名 */
	currentFile: string,
	/**  已完成 hash 的文件数 */
	completedFiles: number,
	/**  总文件数 */
	totalFiles: number,
	/**  累积已 hash 的字节数（所有文件） */
	bytesHashed: number,
	/**  总字节数（所有文件） */
	totalBytes: number,
};

export type PreparedTransferResult = {
	preparedId: string,
	files: TransferFileResult[],
	totalSize: number,
};

/**  自动接收时的保存行为。 */
export type ReceiveSaveBehavior = 
/**  使用策略里配置的默认保存位置，接收完成后进入收件箱。 */
"inbox_and_default_save_location";

/**
 *  全局「暂停接收」状态变更（托盘 / 命令切换后广播，供 UI 与托盘同步）。
 *  事件名 `"receiving-paused-changed"`，payload 为 `true`=已暂停。
 */
export type ReceivingPausedChanged = boolean;

export type ResumeTransferResult = {
	sessionId: string,
	direction: string,
	peerId: string,
	peerName: string,
	files: TransferFileResult[],
	totalSize: number,
	transferredBytes: number,
};

export type RuntimeTransferDirection = "send" | "receive" | "unknown";

export type ScannedSourceResult = {
	isDirectory: boolean,
	files: EnumeratedFile[],
	totalSize: number,
};

/**
 *  DHT 上跨设备共享的配对码记录。
 * 
 *  `created_at` / `expires_at` 保持 `i64`（Unix 秒）以稳定线路格式 +
 *  控制 DHT record 体积；与 IPC 边界的 `PairingCodeInfo`（DateTime<Utc>）解耦。
 */
export type ShareCodeRecord = {
	createdAt: number,
	expiresAt: number,
	/**  发布者的可达地址，用于跨网络场景下让对方直接 dial。 */
	listenAddrs?: string[],
} & OsInfo;

/**  `send_offer` 的返回类型 */
export type StartSendResult = {
	sessionId: string,
};

/**  suspended 原因（phase=Suspended 时有值）。 */
export type SuspendedReason = "local_paused" | "remote_paused" | "interrupted" | "peer_offline" | "app_restarted";

/**  terminal 原因（phase=Terminal 时有值）。 */
export type TerminalReason = "completed" | "cancelled" | "rejected" | "fatal_error";

export type TransferAccepted = TransferAcceptedEvent;

/**  对方接受 Offer 的事件 payload */
export type TransferAcceptedEvent = {
	sessionId: string,
};

export type TransferComplete = TransferCompleteEvent;

export type TransferCompleteEvent = {
	sessionId: string,
	direction: RuntimeTransferDirection,
	totalBytes: number,
	elapsedMs: number,
	saveLocation: CoreSaveLocation | null,
};

export type TransferDbError = TransferDbErrorEvent;

export type TransferDbErrorEvent = {
	sessionId: string,
	message: string,
};

/**  传输方向 */
export type TransferDirection = "send" | "receive";

export type TransferFailed = TransferFailedEvent;

export type TransferFailedEvent = {
	sessionId: string,
	direction: RuntimeTransferDirection,
	error: string,
};

export type TransferFileResult = {
	fileId: number,
	name: string,
	relativePath: string,
	size: number,
	isDirectory: boolean,
};

export type TransferOffer = TransferOfferEvent;

export type TransferOfferEvent = {
	sessionId: string,
	peerId: string,
	deviceName: string,
	files: TransferOfferFileEvent[],
	totalSize: number,
	/**  发起来源（人工 / MCP 代理），供接收端 UI 标识。 */
	origin: TransferOrigin,
	policyAction: string | null,
	policyReason: string | null,
};

export type TransferOfferFileEvent = {
	fileId: number,
	name: string,
	relativePath: string,
	size: number,
	isDirectory: boolean,
};

/**
 *  传输发起来源：人在应用内发起，或 AI 代理经 MCP 发起。
 * 
 *  由发送方自报、承载于 Offer，供接收端展示与 inbox 来源派生——是信息性/UX 信号，
 *  不作接收端安全边界（真正的控制是发送端 `allow_mcp_send_to_device` 门控）。
 */
export type TransferOrigin = 
/**  用户在应用内手动发起。 */
{ type: "human" } | 
/**  AI 代理经 MCP 发起；`client` 为 MCP 客户端名（如 claude-desktop），不可得时为 None。 */
{ type: "mcp"; client: string | null };

export type TransferPaused = TransferPausedEvent;

export type TransferPausedEvent = {
	sessionId: string,
	direction: RuntimeTransferDirection,
};

/**
 *  传输生命周期大状态（phase）。
 *  替代旧的扁平 [`SessionStatus`]（过渡期并存）：phase 表达大状态，
 *  具体原因由 [`SuspendedReason`] / [`TerminalReason`] 表达。
 */
export type TransferPhase = "offered" | "waiting_accept" | "active" | "suspended" | "terminal";

export type TransferProgress = TransferProgressEvent;

export type TransferProgressEvent = {
	sessionId: string,
	direction: RuntimeTransferDirection,
	totalFiles: number,
	completedFiles: number,
	totalBytes: number,
	transferredBytes: number,
	speed: number | null,
	eta: number | null,
	files: FileProgressInfo[],
};

/**  传输投影 DTO —— 前端唯一状态源（逐步替代旧的分散事件 + 扁平 `SessionStatus`）。 */
export type TransferProjection = {
	sessionId: string,
	direction: TransferDirection,
	peerId: string,
	peerName: string,
	phase: TransferPhase,
	suspendedReason: SuspendedReason | null,
	terminalReason: TerminalReason | null,
	recoverable: boolean,
	epoch: number,
	totalSize: number,
	transferredBytes: number,
	startedAt: number,
	updatedAt: number,
	finishedAt: number | null,
	errorMessage: string | null,
	policyAction: string | null,
	policyReason: string | null,
	savePath: CoreSaveLocation | null,
	/**
	 *  「打开文件夹」应定位的真实容器目录 URI(收到内容实际所在的文件夹),已在 core 解析:
	 *  各文件 `local_dir` 全部同一目录 → 该目录;否则回退存储根 `save_path`。前端直读,
	 *  不再自行兜底(已完成接收必为 `Some`)。
	 */
	contentRoot: string | null,
	files: TransferProjectionFile[],
};

export type TransferProjectionFile = {
	fileId: number,
	name: string,
	relativePath: string,
	size: number,
	transferredBytes: number,
};

/**  传输投影更新（redesign：前端唯一状态源）。事件名 `"transfer-projection-update"`。 */
export type TransferProjectionUpdate = TransferProjection;

export type TransferRejected = TransferRejectedEvent;

/**  对方拒绝 Offer 的事件 payload */
export type TransferRejectedEvent = {
	sessionId: string,
	reason: OfferRejectReason | null,
};

export type TransferResumed = TransferResumedEvent;

export type TransferResumedEvent = {
	sessionId: string,
	direction: RuntimeTransferDirection,
	peerId: string,
	peerName: string,
	files: TransferResumedFileInfo[],
	totalSize: number,
};

export type TransferResumedFileInfo = {
	fileId: number,
	name: string,
	relativePath: string,
	size: number,
	isDirectory: boolean,
};

/**
 *  托盘「打开接收文件夹」：路径由前端 `savePath` 拥有，故由前端打开。
 *  事件名 `"tray-open-receive-folder"`。
 */
export type TrayOpenReceiveFolder = null;

/**  托盘「设置」：由前端路由跳转到设置页。事件名 `"tray-open-settings"`。 */
export type TrayOpenSettings = null;

/* Tauri Specta runtime */
type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

