// AUTO-GENERATED by tauri-specta. DO NOT EDIT.

// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE, Channel } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	start: (networkOptions: {
	/**
	 *  由当前 host 提供的引导/中继节点完整地址。
	 * 
	 *  公共基础设施是桌面、移动和 Web 各自的部署策略，不属于跨平台核心；各端可按自身
	 *  transport 能力提供不同的 TCP、QUIC、WebSocket 或 WebRTC Direct 地址。
	 */
	bootstrapNodes?: string[],
	discoveryMode?: DiscoveryMode,
	autoDiscoverLanHelpers?: boolean,
	provideLanHelper?: boolean,
	/**
	 *  公网可达性：允许在已知公网中继上建立 reservation 使本机可被跨网直达。
	 * 
	 *  与 discovery_mode 正交——LanOnly 只管"不主动连接内置公网引导"，
	 *  经 LAN Helper 学到的公网中继仍受本开关控制。关闭 = 严格局域网，
	 *  跨网可达仅剩 LAN Helper 转发路径（依赖打洞，可能不可用）。
	 */
	publicReachability?: boolean,
} | null) => __TAURI_INVOKE<null>("start", { networkOptions }),
	shutdown: () => __TAURI_INVOKE<null>("shutdown"),
	listDevices: (filter: "all" | "connected" | "paired" | null) => __TAURI_INVOKE<DeviceListResult>("list_devices", { filter }),
	getNetworkStatus: () => __TAURI_INVOKE<NetworkStatus>("get_network_status"),
	/**  下载并安装应用更新（桌面端） */
	installUpdate: (url: string, isForce: boolean) => __TAURI_INVOKE<null>("install_update", { url, isForce }),
	listInboxItems: (includeArchived: boolean) => __TAURI_INVOKE<InboxItemSummary[]>("list_inbox_items", { includeArchived }),
	/**
	 *  检索收件箱。`limit` 缺省取三端共享的 [`INBOX_SEARCH_LIMIT`]，`include_archived` 默认 false。
	 * 
	 *  存储端口未注入时由 Tauri State 注入机制直接返回错误（不会 panic）。
	 */
	searchInbox: (query: string, limit: number | null, includeArchived: boolean | null) => __TAURI_INVOKE<InboxSearchHit[]>("search_inbox", { query, limit, includeArchived }),
	getInboxItemDetail: (itemId: string) => __TAURI_INVOKE<({
	files: InboxItemFileEntry[],
	transfer: TransferProjection | null,
}) & (InboxItemSummary) | null>("get_inbox_item_detail", { itemId }),
	getInboxItemByTransferSessionId: (sessionId: string) => __TAURI_INVOKE<({
	files: InboxItemFileEntry[],
	transfer: TransferProjection | null,
}) & (InboxItemSummary) | null>("get_inbox_item_by_transfer_session_id", { sessionId }),
	repairMissingInboxItems: () => __TAURI_INVOKE<InboxItemDetail[]>("repair_missing_inbox_items"),
	openInboxItem: (itemId: string, fileId: number | null) => __TAURI_INVOKE<null>("open_inbox_item", { itemId, fileId }),
	showInboxItemInFolder: (itemId: string, fileId: number | null) => __TAURI_INVOKE<null>("show_inbox_item_in_folder", { itemId, fileId }),
	exportInboxItem: (itemId: string, destinationDir: string) => __TAURI_INVOKE<null>("export_inbox_item", { itemId, destinationDir }),
	archiveInboxItem: (itemId: string, archived: boolean) => __TAURI_INVOKE<null>("archive_inbox_item", { itemId, archived }),
	/**
	 *  删除收件箱条目；`delete_local_files` 为真时连已落盘的文件一起删。
	 * 
	 *  编排（先文件后记录、删文件失败不阻断、条目不存在报错）是**三端共用的领域规则**，
	 *  住在 [`swarmdrop_transfer::inbox::delete_inbox_item`]。此前这里裸写
	 *  `tokio::fs::remove_file` —— 那是绕过 `FileAccess` 端口的第三份删除实现，
	 *  现已收编到 `TauriFileAccess::delete_finalized_file`。
	 * 
	 *  `FileAccess` 从 state 取而不是现建一个：与 `start()` 注入给 `TransferManager` 的
	 *  **是同一个 `Arc`**（组装点在 `setup.rs`）。收件箱命令刻意不经 `TransferManager`
	 *  ——它是与网络无关的内容账本，绑到节点生命周期上会变成「没联网就翻不了已收到的东西」。
	 */
	deleteInboxItem: (itemId: string, deleteLocalFiles: boolean) => __TAURI_INVOKE<null>("delete_inbox_item", { itemId, deleteLocalFiles }),
	/**  从系统 keychain 初始化设备身份，不再要求用户输入 Stronghold 密码。 */
	initializeIdentity: () => __TAURI_INVOKE<IdentityState>("initialize_identity"),
	/**  生成新的 Ed25519 密钥对（protobuf 编码，与存量 keychain 格式兼容）。 */
	generateKeypair: () => __TAURI_INVOKE<number[]>("generate_keypair"),
	/**  注册密钥对到 Tauri state，并在桌面端写入系统 keychain。 */
	registerKeypair: (keypair: number[]) => __TAURI_INVOKE<string>("register_keypair", { keypair }),
	/**  读取持久化的设备名（onboarding 完成前为 `None`）。 */
	getDeviceName: () => __TAURI_INVOKE<string | null>("get_device_name"),
	/**
	 *  设置设备名：落盘 + 让已连接的对端立刻看到新名字。
	 * 
	 *  编排在 [`swarmdrop_core::device_name::rename_device`] 里（写盘 → 本机 `OsInfo` →
	 *  identify `agent_version` 逐连接下发 + 主动 push → 发 `DeviceRenamed` 事件）。
	 *  **节点不重启、连接不断、在途传输不中断。**
	 * 
	 *  「节点在不在跑」这件事由 core 的签名吸收：`guard.as_ref()` 本身就是
	 *  `Option<&NetManager>`，节点未启动（onboarding，或设置页早于 `start`）时它是 `None`，
	 *  core 走只落盘那条分支。宿主这侧因此不写 if/else。
	 * 
	 *  归一化（trim / 剥控制字符与 `;` / 40 char 截断 / 空则清空）全在
	 *  [`DeviceName::parse`] 里，本命令不做任何就地处理 —— 三端共用同一个入口。
	 *  `name = None`（或归一化后为空）清空，回退到系统 hostname。
	 * 
	 *  **返回归一化后的结果**（清空时 `None`），前端直接拿它更新本地状态。命令手里本来就握着
	 *  `DeviceName::parse` 的产物，返回 `()` 只会逼调用方回读一次才知道真正落库的是什么。
	 *  Web 端 `rename_device` 早就是这个形态，本次三端统一。
	 */
	setDeviceName: (name: string | null) => __TAURI_INVOKE<string | null>("set_device_name", { name }),
	/**
	 *  生成一次性签名邀请串（供二维码/链接分享）。
	 * 
	 *  `local_only=true` 走 LocalOnly 策略（受邀方只用私网地址、禁公网 fallback）。
	 *  邀请自包含地址提示，不经 DHT——旧 6 位分享码机制已废弃。
	 */
	generatePairInvite: (localOnly: boolean | null) => __TAURI_INVOKE<string>("generate_pair_invite", { localOnly }),
	/**
	 *  撤销本机发出的邀请（重新生成覆盖旧串、用户放弃、关闭邀请界面）。
	 * 
	 *  幂等：不认识的串直接 no-op（详见 `PairingManager::revoke_invite`），所以前端可以
	 *  fire-and-forget。节点未启动时同样无事可做——注册表随节点一起没了（重启后由
	 *  `load_invites` 从库里读回，见 `invite-persistence`）。
	 */
	revokePairInvite: (invite: string) => __TAURI_INVOKE<boolean>("revoke_pair_invite", { invite }),
	/**
	 *  列出本机未过期的已发出邀请（最近生成的在前）。
	 * 
	 *  TTL 24h 之后「我现在有几条邀请在外面飘」不再是个可以忽略的问题 —— 这个列表加上
	 *  [`revoke_pair_invite_by_id`] 是那段窗口的可见性与控制手段，不是可选装饰。
	 */
	listPairInvites: () => __TAURI_INVOKE<PairInviteListItem[]>("list_pair_invites"),
	/**
	 *  按列表条目的 `id`（capability 哈希 hex）撤销 —— 列表里没有原始邀请串。
	 * 
	 *  **返回是否已落盘**。`false` 意味着撤销在本次运行内生效了，但重启后那条邀请会复活
	 *  （写穿失败，库里仍是生成时写下的 pending）—— UI 必须把这件事告诉用户，
	 *  否则他会以为已经撤销干净了。
	 */
	revokePairInviteById: (id: string) => __TAURI_INVOKE<boolean>("revoke_pair_invite_by_id", { id }),
	/**
	 *  生成 canonical 邀请链接的二维码 SVG（三端统一编码规范：原样编码 + 最优分段 + ECL::M
	 *  + quiet zone，见 `swarmdrop_invite::qr`）。前端 `dangerouslySetInnerHTML` 塞入白卡。
	 */
	inviteQrSvg: (invite: string) => __TAURI_INVOKE<string>("invite_qr_svg", { invite }),
	/**
	 *  解码并验签邀请串，返回对端展示信息（**不发起配对、不消费**）。
	 * 
	 *  供受邀方在扫码/粘贴/剪贴板感知后先展示确认卡；篡改/伪造的邀请在此即被验签拒绝。
	 */
	decodePairInvite: (invite: string) => __TAURI_INVOKE<PairInvitePreview>("decode_pair_invite", { invite }),
	/**
	 *  用邀请串发起配对（受邀方）：解码验签 → 连接发起方 → 出示凭证。
	 * 
	 *  配对成功后由 core 落盘并 emit `paired-device-added`。
	 * 
	 *  返回 [`PairingOutcome`]：`response` 是对端的答复，`persisted` 为 `false` 时表示
	 *  **配对成功了但这条记录没写进钥匙串** —— 本次运行内可用，重启后这台设备会从列表消失
	 *  （对端仍记着）。UI 必须如实告知，不能当成普通成功。
	 */
	consumePairInvite: (invite: string) => __TAURI_INVOKE<PairingOutcome>("consume_pair_invite", { invite }),
	/**
	 *  向对端发起配对请求
	 * 
	 *  配对成功后自动添加到已配对设备，并 emit `paired-device-added` 事件通知前端。
	 * 
	 *  `peer_id` 为 base58 字符串，`addrs` 为 multiaddr 字符串列表，由命令内部解析为
	 *  内核 newtype，方便通过 specta 生成 TypeScript bindings（内核类型本身不实现
	 *  `specta::Type`）。
	 */
	requestPairing: (peerId: string, method: PairingMethod, addrs: string[] | null) => __TAURI_INVOKE<PairingOutcome>("request_pairing", { peerId, method, addrs }),
	/**
	 *  处理收到的配对请求（接受/拒绝）。
	 * 
	 *  接受后由 core 落盘并 emit `paired-device-added` 事件通知前端。
	 * 
	 *  **返回是否已落盘**（响应本身是入参，不必回传）：`false` = 配对成功但记录没写进钥匙串，
	 *  重启后这台设备会不见（对端仍记着）。语义与 [`PairingOutcome::persisted`] 同。
	 */
	respondPairingRequest: (pendingId: number, method: PairingMethod, response: PairingResponse) => __TAURI_INVOKE<boolean>("respond_pairing_request", { pendingId, method, response }),
	/**
	 *  取消与指定设备的配对。
	 * 
	 *  「节点在不在跑」这条分支由 core 的 [`swarmdrop_core::paired_devices::unpair`] 吸收：节点在跑就走
	 *  `PairingManager::unpair`（持久化 → 共享内存表 → 事件，**fail-closed**，不会再出现
	 *  「本次运行解除了、重启又复活」）；没跑则只删持久化并由 core 补发
	 *  `PairedDeviceRemoved`（那条路径上 `PairingManager` 根本没起）。
	 *  桌面此前在这里手工补那条事件、移动端忘了补 —— 同一段分支写两遍必然漂。
	 * 
	 *  `peer_id` 为 base58 字符串，由命令内部解析为 `NodeId`。
	 */
	removePairedDevice: (peerId: string) => __TAURI_INVOKE<null>("remove_paired_device", { peerId }),
	/**
	 *  某信任级别的默认接收策略。
	 * 
	 *  **纯派生，不取任何 State**——它在节点没起来时也该能用（信任策略对话框可以先开着）。
	 * 
	 *  存在的全部理由是**不让前端再抄一份那张表**。此前 `trust-policy-dialog.tsx` 里有一份
	 *  `defaultPolicyForTrust`、移动端 `device-trust.ts` 里另有一份，两份还长出了不同的
	 *  「切级别时保留哪些字段」规则，而内核那一份一个都不保留——同一个产品动作三种行为。
	 *  现在规则只在 [`DeviceReceivePolicy::for_trust_level`] 一处。
	 * 
	 *  `previous` 传该设备**当前**的策略；用户显式设过的保存位置与代收授权会被带过去
	 *  （`blocked` 除外）。
	 */
	defaultReceivePolicy: (trustLevel: DeviceTrustLevel, previous: {
	autoAccept: boolean,
	requireConfirmation: boolean,
	maxTransferBytes?: number | null,
	allowDirectories: boolean,
	allowRelayAutoAccept: boolean,
	saveBehavior?: ReceiveSaveBehavior,
	defaultSaveLocation?: string | null,
	allowMcpSendToDevice: boolean,
	/**
	 *  允许 MCP/AI 代该来源设备处置入站 offer（接受或拒绝）。
	 * 
	 *  默认 false。与发送侧 `allow_mcp_send_to_device` **刻意不对称**：代收会往磁盘写入、
	 *  风险更高，故即便对 Owned 设备也需用户逐设备显式开启（发送侧则随信任级别自动派生）。
	 *  只能由用户在 app 的设备信任策略中开启，agent 无任何写权限——防止自我提权、静默代收。
	 */
	allowMcpAcceptFromDevice?: boolean,
	expiresAt?: number | null,
} | null) => __TAURI_INVOKE<DeviceReceivePolicy>("default_receive_policy", { trustLevel, previous }),
	/**
	 *  更新已配对设备的可信策略。
	 * 
	 *  落盘与「节点在跑时把新值推进共享内存表」都在 core 的
	 *  [`swarmdrop_core::paired_devices::set_receive_policy`]（否则「策略已保存、本次运行仍按旧策略裁决入站
	 *  offer」）。存在性检查也只在那一处 —— 它找不到时已经返回 `Err`，命令层再 `find` 一遍
	 *  是走不到的死分支。
	 */
	updatePairedDevicePolicy: (peerId: string, trustLevel: DeviceTrustLevel, receivePolicy: {
	autoAccept: boolean,
	requireConfirmation: boolean,
	maxTransferBytes?: number | null,
	allowDirectories: boolean,
	allowRelayAutoAccept: boolean,
	saveBehavior?: ReceiveSaveBehavior,
	defaultSaveLocation?: string | null,
	allowMcpSendToDevice: boolean,
	/**
	 *  允许 MCP/AI 代该来源设备处置入站 offer（接受或拒绝）。
	 * 
	 *  默认 false。与发送侧 `allow_mcp_send_to_device` **刻意不对称**：代收会往磁盘写入、
	 *  风险更高，故即便对 Owned 设备也需用户逐设备显式开启（发送侧则随信任级别自动派生）。
	 *  只能由用户在 app 的设备信任策略中开启，agent 无任何写权限——防止自我提权、静默代收。
	 */
	allowMcpAcceptFromDevice?: boolean,
	expiresAt?: number | null,
} | null) => __TAURI_INVOKE<PairedDeviceInfo>("update_paired_device_policy", { peerId, trustLevel, receivePolicy }),
	scanSources: (sources: FileSource[]) => __TAURI_INVOKE<ScannedSourceResult[]>("scan_sources", { sources }),
	prepareSend: (files: EnumeratedFile[], onProgress: Channel<PrepareProgressEvent>) => __TAURI_INVOKE<PreparedTransferResult>("prepare_send", { files, onProgress }),
	startSend: (preparedId: string, peerId: string, peerName: string, selectedFileIds: number[]) => __TAURI_INVOKE<StartSendResult>("start_send", { preparedId, peerId, peerName, selectedFileIds }),
	acceptReceive: (sessionId: string, saveLocation: CoreSaveLocation) => __TAURI_INVOKE<null>("accept_receive", { sessionId, saveLocation }),
	rejectReceive: (sessionId: string) => __TAURI_INVOKE<null>("reject_receive", { sessionId }),
	cancelSend: (sessionId: string) => __TAURI_INVOKE<null>("cancel_send", { sessionId }),
	cancelReceive: (sessionId: string) => __TAURI_INVOKE<null>("cancel_receive", { sessionId }),
	pauseSend: (sessionId: string) => __TAURI_INVOKE<null>("pause_send", { sessionId }),
	pauseReceive: (sessionId: string) => __TAURI_INVOKE<null>("pause_receive", { sessionId }),
	getTransferProjections: () => __TAURI_INVOKE<TransferProjection[]>("get_transfer_projections"),
	/**  发送方向会话的源文件绝对路径（「重新发送」重建载荷用；接收方向返回空列表）。 */
	getTransferSourcePaths: (sessionId: string) => __TAURI_INVOKE<string[]>("get_transfer_source_paths", { sessionId }),
	/**  删除单条传输记录。走域方法而非 `store().delete_session()`——「进行中不可删」的守卫在那里。 */
	deleteTransferSession: (sessionId: string) => __TAURI_INVOKE<null>("delete_transfer_session", { sessionId }),
	/**  清空传输历史：只删已终态的记录，进行中与可续传的会话保留（端口契约）。 */
	clearTransferHistory: () => __TAURI_INVOKE<null>("clear_transfer_history"),
	resumeTransfer: (sessionId: string) => __TAURI_INVOKE<ResumeTransferResult>("resume_transfer", { sessionId }),
	/**
	 *  设置全局「暂停接收」。`true`=暂停：节点保持在线可发现、配对不受影响，但对新 offer
	 *  自动婉拒；`false`=恢复：新 offer 照常按既有策略处理。同步托盘文案并广播
	 *  `receiving-paused-changed` 事件。
	 */
	setReceivingPaused: (paused: boolean) => __TAURI_INVOKE<null>("set_receiving_paused", { paused }),
	/**  查询当前是否暂停接收（节点未启动视为未暂停）。 */
	isReceivingPaused: () => __TAURI_INVOKE<boolean>("is_receiving_paused"),
	/**
	 *  真正退出应用。
	 * 
	 *  关闭语义由前端 `onCloseRequested` 拦截：`closeBehavior=quit` 或首次对话框选「退出」
	 *  时由前端显式调用本命令，确保进程退出（仅 `hide()` 不退出；macOS 关最后一个窗口默认
	 *  也不退出）。托盘「退出」走 Rust 侧 `app.exit(0)`，不经本命令。
	 */
	quitApp: () => __TAURI_INVOKE<void>("quit_app"),
	/**  应用当前 locale：更新 rust-i18n 全局 locale 并即时重绘托盘菜单文案。 */
	setLocale: (locale: string) => __TAURI_INVOKE<null>("set_locale", { locale }),
	/**
	 *  用系统文件管理器打开应用日志目录。
	 * 
	 *  目录不存在时返回错误而非静默成功——那通常意味着文件层没装上（见
	 *  [`crate::logging::install_file_layer`]），让用户看到比假装打开了更有用。
	 */
	openLogDir: () => __TAURI_INVOKE<null>("open_log_dir"),
	/**  查询 MCP Server 当前状态 */
	getMcpStatus: () => __TAURI_INVOKE<McpStatus>("get_mcp_status"),
	/**
	 *  启动 MCP Server
	 * 
	 *  `port` 为可选参数，默认 19527。
	 */
	startMcpServer: (port: number | null) => __TAURI_INVOKE<McpStatus>("start_mcp_server", { port }),
	/**  停止 MCP Server */
	stopMcpServer: () => __TAURI_INVOKE<McpStatus>("stop_mcp_server"),
	/**
	 *  前端根处理器 mount 时调用：标记就绪并**一次取走**冷启动期间缓冲的两类负载
	 *  （文件路径 + 深链邀请）。
	 * 
	 *  一次取走而非两个命令：`frontend_ready` 是共享标记，拆开会让第二类负载丢在
	 *  「标记已置位、前端还没订阅完」那道缝里（详见 [`external_open::take_pending`]）。
	 */
	takePendingExternalOpen: () => __TAURI_INVOKE<PendingExternalOpen>("take_pending_external_open"),
};

/** Events */
export const events = {
	deviceRenamed: makeEvent<DeviceRenamed>("device-renamed"),
	devicesChanged: makeEvent<DevicesChanged>("devices-changed"),
	externalFileOpen: makeEvent<ExternalFileOpen>("external-file-open"),
	externalPairInvite: makeEvent<ExternalPairInvite>("external-pair-invite"),
	networkStatusChanged: makeEvent<NetworkStatusChanged>("network-status-changed"),
	pairedDeviceAdded: makeEvent<PairedDeviceAdded>("paired-device-added"),
	pairedDeviceRemoved: makeEvent<PairedDeviceRemoved>("paired-device-removed"),
	pairingRequestReceived: makeEvent<PairingRequestReceived>("pairing-request-received"),
	receivingPausedChanged: makeEvent<ReceivingPausedChanged>("receiving-paused-changed"),
	transferAccepted: makeEvent<TransferAccepted>("transfer-accepted"),
	transferComplete: makeEvent<TransferComplete>("transfer-complete"),
	transferDbError: makeEvent<TransferDbError>("transfer-db-error"),
	transferFailed: makeEvent<TransferFailed>("transfer-failed"),
	transferOffer: makeEvent<TransferOffer>("transfer-offer"),
	transferPaused: makeEvent<TransferPaused>("transfer-paused"),
	transferProgress: makeEvent<TransferProgress>("transfer-progress"),
	transferProjectionUpdate: makeEvent<TransferProjectionUpdate>("transfer-projection-update"),
	transferRejected: makeEvent<TransferRejected>("transfer-rejected"),
	transferResumed: makeEvent<TransferResumed>("transfer-resumed"),
	trayOpenReceiveFolder: makeEvent<TrayOpenReceiveFolder>("tray-open-receive-folder"),
	trayOpenSettings: makeEvent<TrayOpenSettings>("tray-open-settings"),
};

/* Types */
/**
 *  前端可见的错误结构体 —— [`AppError`] 在 specta 里被映射成这个形状，
 *  与 [`AppError::serialize`] 真正写出的 JSON 完全一致。
 */
export type AppErrorPayload = {
	kind: string,
	message: string,
};

export type BootstrapCandidateSource = 
/**  当前 host 注入的静态引导/中继配置（含各端默认值和用户追加地址）。 */
"hostConfigured" | "mdnsLanHelper" | 
/**  运行时经 identify 学到的基础设施节点（如 LanOnly 下经 LAN Helper 认识的公网中继） */
"learned";

export type CandidateSourceStatus = {
	source: BootstrapCandidateSource,
	count: number,
};

/**
 *  链路详情：当前连接的可核对事实。
 * 
 *  与 [`ConnectionType`] 的分工——那个是给所有人看的一句话结论（局域网 / 打洞 /
 *  中继），这个是「凭什么这么说」：走的哪条地址、哪种传输、经不经中继、经的是谁。
 *  三端 UI 把它放在默认折叠的区块里，普通用户看不到，排障时一眼能拿到全部证据。
 */
export type ConnectionDetails = {
	/**
	 *  承载字节的传输协议。
	 * 
	 *  `None` 是真实存在的情况，不是缺陷：入站中继连接的 `send_back_addr` 只有
	 *  `/p2p/<src>` 一段，地址里没有任何传输信息。呈现层照实显示「未知」。
	 */
	transport: TransportKind | null,
	/**  当前最优连接的远端 multiaddr，原样给出——便于直接粘进 issue 或与日志比对。 */
	remoteAddr: string,
	/**
	 *  中转身份：经中继时是那台 relay 的 PeerId，直连为 `None`。
	 * 
	 *  「经中继」三个字对排障几乎没用，得说清楚经的是哪一台——自建 relay 还是
	 *  局域网里的 LanHelper，处理方式完全不同。
	 */
	relay: string | null,
};

/**  连接类型。 */
export type ConnectionType = "lan" | "dcutr" | "relay";

/**
 *  接收端保存位置（host-agnostic）。
 * 
 *  core 内部统一用此类型，避免把 `entity::SaveLocation`（SeaORM 实体细节）
 *  暴露到公共 API 上。DB 边界用 [`From`] 与 `entity::SaveLocation` 双向转换。
 */
export type CoreSaveLocation = 
/**
 *  宿主自己解释的保存位置串，**core 视其为不透明**。
 * 
 *  桌面是文件系统绝对路径；移动端是 expo-file-system 的 URI，**可能是 `file://`，
 *  也可能是 Android SAF 的 `content://` tree**（用户在设置里选了系统公共目录时）；
 *  Web 是 OPFS 的相对路径。名字叫 `Path` 是历史，别据此假设它一定是文件系统路径——
 *  移动端的发布路径正是靠嗅探 `content://` 前缀来分派的。
 */
{ type: "path"; path: string };

/**  统一的设备输出类型。 */
export type Device = {
	peerId: string,
	status: DeviceStatus,
	connection: ConnectionType | null,
	/**
	 *  链路详情。仅在线且内核报告过连接地址时有值——离线设备、以及只靠 mDNS
	 *  地址推断出 `connection` 的宽限期内，这里是 `None`（没连接就没有链路可谈）。
	 */
	connectionDetails: ConnectionDetails | null,
	/**
	 *  内核尝试过局域网直连升级但失败了。
	 * 
	 *  与 `connection == Relay` 一起看才有意义：那时它把「对端本来就在外网」与
	 *  「对端就在同一网段却连不上」分开。后者呈现层应给出可行动的提示——查防火墙，
	 *  或（浏览器上）允许本地网络访问。
	 */
	lanUpgradeFailed: boolean,
	latency: number | null,
	isPaired: boolean,
	trustLevel: DeviceTrustLevel | null,
	receivePolicy: DeviceReceivePolicy | null,
	trustConfirmed: boolean | null,
} & OsInfo;

/**  设备过滤器 */
export type DeviceFilter = "all" | "connected" | "paired";

/**  设备列表查询结果。 */
export type DeviceListResult = {
	devices: Device[],
	total: number,
};

/**
 *  可信设备接收策略。
 * 
 *  字段保持 host-neutral：保存位置使用字符串表达的 host 路径，桌面端解释为绝对路径，
 *  移动端后续可解释为应用文档目录下的子路径。
 */
export type DeviceReceivePolicy = {
	autoAccept: boolean,
	requireConfirmation: boolean,
	maxTransferBytes?: number | null,
	allowDirectories: boolean,
	allowRelayAutoAccept: boolean,
	saveBehavior?: ReceiveSaveBehavior,
	defaultSaveLocation?: string | null,
	allowMcpSendToDevice: boolean,
	/**
	 *  允许 MCP/AI 代该来源设备处置入站 offer（接受或拒绝）。
	 * 
	 *  默认 false。与发送侧 `allow_mcp_send_to_device` **刻意不对称**：代收会往磁盘写入、
	 *  风险更高，故即便对 Owned 设备也需用户逐设备显式开启（发送侧则随信任级别自动派生）。
	 *  只能由用户在 app 的设备信任策略中开启，agent 无任何写权限——防止自我提权、静默代收。
	 */
	allowMcpAcceptFromDevice?: boolean,
	expiresAt?: number | null,
};

/**
 *  本机设备名已更新（落盘 + identify 广播都已完成）。事件名 `"device-renamed"`。
 * 
 *  前端更新设备名镜像的**唯一**入口：改名可能来自另一个窗口或 MCP 工具，让发起改名的
 *  那个界面自己刷新覆盖不到这些来源。`displayName` 已含「空则回退 hostname」的语义
 *  （core 的 `OsInfo::display_name()`），前端不必再写一遍那个回退。
 */
export type DeviceRenamed = {
	name: string | null,
	displayName: string,
};

/**  设备状态。 */
export type DeviceStatus = "online" | "offline";

/**  已配对设备信任等级。 */
export type DeviceTrustLevel = "owned" | "collaborator" | "temporary" | "blocked";

export type DevicesChanged = Device[];

export type DiscoveryMode = "auto" | "lanOnly";

/**
 *  目录遍历后的扁平化文件条目
 * 
 *  同时用于 `scan_sources` 命令返回和 `prepare_send` 命令输入，
 *  因此同时派生 Serialize + Deserialize。
 */
export type EnumeratedFile = {
	/**  文件名 */
	name: string,
	/**  相对路径（Unix 风格 `/` 分隔符） */
	relativePath: string,
	/**  文件来源 */
	source: FileSource,
	/**  文件大小 */
	size: number,
};

/**
 *  外部「用 SwarmDrop 打开」文件/文件夹后归一化的本地绝对路径列表。
 *  事件名 `"external-file-open"`，前端根处理器据此扫描并跳转选设备屏。
 */
export type ExternalFileOpen = {
	paths: string[],
};

/**
 *  深链（`swarmdrop://…`）送达的配对邀请链接原文。
 * 
 *  事件名 `"external-pair-invite"`。**未解码未验签** —— 宿主层只递文本，前端照常走
 *  「解码验签 → 确认卡 → 用户确认」的安全闸，与扫码/粘贴同一条路
 *  （openspec: pair-deep-link）。
 */
export type ExternalPairInvite = {
	invite: string,
};

/**
 *  会话失败原因。持久化进 `transfer_sessions.error_message` 列（类型不变，存 JSON）。
 * 
 *  变体数量刻意贴着**实际构造点**（两处 `ActorReport::FatalError` + 一处过期回收），
 *  不预留「将来可能用到」的码 —— `failure-semantics-contract` 的 D3 已经吃过一次亏：
 *  造出来到不了 UI 的判别码只是三端文案表里的死条目。
 */
export type FailureCode = 
/**
 *  超过保留期仍未恢复，被启动清理回收。
 * 
 *  `retention_days` 进文案（「超过 N 天」），所以它是参数而不是常量 ——
 *  保留期是配置项，两端可能不同。
 */
{ code: "sessionExpired"; retentionDays: number } | 
/**
 *  对端拒绝了续传请求。
 * 
 *  **直接内嵌 [`ResumeRejectReason`]，不再压成字符串。** 这条通道此前经
 *  `resume_reject_message()` 把一个六变体的枚举摊平成六句中文 —— 判别信息在
 *  wire 上本来就是结构化的，落库时降级成自由文本，到了 UI 又没法还原。
 */
{ code: "resumeRejected"; reason: ResumeRejectReason } | 
/**
 *  发送方的 Offer 没能送达对端（发送失败或收到非预期响应）。
 * 
 *  两个调用点的技术细节（IO 错误、响应类型）对用户是同一件事：对方没收到你的请求。
 *  细节进 `warn!`。
 */
{ code: "offerFailed" } | 
/**
 *  **存量数据**：本判别码引入之前写入的自由文本。
 * 
 *  不写回填迁移 —— 失败原因是过程账本上的一句解释，重算不出来（原始错误早没了），
 *  猜也猜不准。存量行原样展示旧串即可，新行一律是判别码；随着历史滚动它自然消失。
 *  这与收件箱标题的处置不同（那边**回填**了），区别在于标题可以从文件列表重算，
 *  失败原因不能。
 */
{ code: "legacy"; message: string };

export type FileProgressInfo = {
	fileId: number,
	name: string,
	size: number,
	transferred: number,
	status: FileTransferStatus,
};

/**  文件来源：标准文件系统路径 */
export type FileSource = 
/**  标准文件系统路径 */
{ type: "path"; path: string };

export type FileTransferStatus = "pending" | "transferring" | "completed";

export type IdentityState = {
	keypair: number[],
	deviceId: string,
	pairedDevices: PairedDeviceInfo[],
	created: boolean,
};

/**  收件箱内容类型。 */
export type InboxContentKind = "files" | "text" | "clipboard" | "bundle";

/**  搜索命中条目下的文件标识（供下钻定位）。 */
export type InboxHitFile = {
	name: string,
	relativePath: string,
};

/**  收件箱详情 DTO。 */
export type InboxItemDetail = {
	files: InboxItemFileEntry[],
	transfer: TransferProjection | null,
} & InboxItemSummary;

/**  收件箱文件 DTO。 */
export type InboxItemFileEntry = {
	id: number,
	transferFileId: number | null,
	/**  条目根之下的相对路径。**Web 宿主删文件用这个**——OPFS 的键就是它。 */
	relativePath: string,
	name: string,
	size: number,
	checksum: string,
	/**
	 *  宿主可直接操作的完整路径。**桌面 / 移动删文件用这个**（那边是真实文件系统路径）；
	 *  **Web 上它是带 `opfs:/` 前缀的展示值，喂给 `remove_path` 会去找一个叫 `opfs:` 的目录**。
	 * 
	 *  两个路径字段并存且「该用哪个」按端不同，是这个 DTO 最容易踩空的地方——所以写在这里，
	 *  而不是让每个宿主自己从别处推断。
	 */
	localPath: string,
	missing: boolean,
};

/**  收件箱列表条目 DTO。 */
export type InboxItemSummary = {
	id: string,
	transferSessionId: string | null,
	sourcePeerId: string,
	sourceName: string,
	sourceKind: InboxSourceKind,
	contentKind: InboxContentKind,
	title: string,
	itemCount: number,
	totalSize: number,
	rootPath: string | null,
	contentHash: string | null,
	receivedAt: number,
	lastOpenedAt: number | null,
	archivedAt: number | null,
	deletedAt: number | null,
	missing: boolean,
};

/**  收件箱搜索命中（item 粒度）。 */
export type InboxSearchHit = {
	id: string,
	title: string,
	sourceName: string,
	itemCount: number,
	rootPath: string | null,
	receivedAt: number,
	/**
	 *  命中所在文本的片段（在 Rust 端按子串位置切窗口生成）。
	 * 
	 *  `None` = **不该渲染片段行**：命中的是标题或来源名（条目行上已经显示着），
	 *  或一个候选都没命中。判据在 [`inbox_snippet`]，三端不要各判一遍。
	 */
	snippet: string | null,
	/**  该条目下的文件（文件名 + 相对路径），供 get_inbox_file 下钻。 */
	files: InboxHitFile[],
};

/**  收件箱来源类型。 */
export type InboxSourceKind = "paired_device" | "share_code" | "mcp" | "unknown";

/**  MCP Server 状态返回值 */
export type McpStatus = {
	running: boolean,
	addr: string | null,
};

export type NetworkRuntimeConfig = {
	/**
	 *  由当前 host 提供的引导/中继节点完整地址。
	 * 
	 *  公共基础设施是桌面、移动和 Web 各自的部署策略，不属于跨平台核心；各端可按自身
	 *  transport 能力提供不同的 TCP、QUIC、WebSocket 或 WebRTC Direct 地址。
	 */
	bootstrapNodes?: string[],
	discoveryMode?: DiscoveryMode,
	autoDiscoverLanHelpers?: boolean,
	provideLanHelper?: boolean,
	/**
	 *  公网可达性：允许在已知公网中继上建立 reservation 使本机可被跨网直达。
	 * 
	 *  与 discovery_mode 正交——LanOnly 只管"不主动连接内置公网引导"，
	 *  经 LAN Helper 学到的公网中继仍受本开关控制。关闭 = 严格局域网，
	 *  跨网可达仅剩 LAN Helper 转发路径（依赖打洞，可能不可用）。
	 */
	publicReachability?: boolean,
};

/**  网络状态快照。 */
export type NetworkStatus = {
	status: NodeStatus,
	peerId: string | null,
	listenAddrs: string[],
	natStatus: string,
	publicAddr: string | null,
	connectedPeers: number,
	discoveredPeers: number,
	/**  Relay 中继是否就绪（至少有一个中继节点已连接）。 */
	relayReady: boolean,
	/**
	 *  公网可达：持有公网范围中继的活跃 reservation，或已确认公网直达地址。
	 *  false = 仅局域网可达（跨网设备无法直接访问本机）。
	 */
	publicReachable: boolean,
	/**  公网可达性设置的回显（host 侧检测"设置已变更需重启"用）。 */
	publicReachabilityEnabled: boolean,
	/**  当前已连接的中继节点 NodeId 列表。 */
	relayPeers: string[],
	/**  是否至少有一个引导节点已连接。 */
	bootstrapConnected: boolean,
	/**  当前发现模式。 */
	discoveryMode: DiscoveryMode,
	/**  是否自动发现局域网协助节点。 */
	autoDiscoverLanHelpers: boolean,
	/**  本设备是否配置为提供局域网协助能力。 */
	localLanHelperEnabled: boolean,
	/**  本设备当前是否正在作为局域网协助节点运行。 */
	localLanHelperRunning: boolean,
	/**  Relay Server 是否启用。 */
	relayServerEnabled: boolean,
	/**  LAN Helper 可公告地址。 */
	lanHelperAdvertisedAddrs: string[],
	/**  已发现的局域网协助节点数量。 */
	lanHelperCount: number,
	/**  候选总数。 */
	bootstrapCandidateCount: number,
	/**  按来源聚合的候选数量。 */
	candidateSources: CandidateSourceStatus[],
	/**  当前 relay peer 的候选来源。 */
	relaySource: BootstrapCandidateSource | null,
};

export type NetworkStatusChanged = NetworkStatus;

/**  节点运行状态。 */
export type NodeStatus = "running" | "stopped";

/**  Offer 被拒绝的原因。 */
export type OfferRejectReason = { type: "not_paired" } | { type: "user_declined" } | { type: "policy_rejected" } | 
/**  接收方处于全局「暂停接收」状态，婉拒新 offer。 */
{ type: "receiving_paused" } | 
/**
 *  Offer 里有文件的 `relative_path` 会逃出保存目录（绝对路径、盘符或 `..` 穿越）。
 * 
 *  独立成一个变体而不是并进 `PolicyRejected`：这**不是**接收方的偏好设置拒绝了你，
 *  而是这条 offer 本身不合法。两者对发送方的含义完全不同——前者「换个设置或问问对方」，
 *  后者「你的客户端发了非法数据」。合法客户端永远不会触发它。
 */
{ type: "unsafe_path" };

/**
 *  设备操作系统信息。
 * 
 *  `hostname` 是系统主机名（运行时取，桌面端通常是机器名，移动端通常拿不到）；
 *  `name` 是用户在 onboarding / 设置里起的名字（持久化），由 core 的组合根从
 *  [`DeviceConfig`](crate::ports::DeviceConfig) 端口填充，UI 显示按
 *  `name.as_deref().unwrap_or(&hostname)` 回退。
 */
export type OsInfo = {
	/**  用户起的设备名；缺省时回退到 `hostname`。 */
	name?: string | null,
	hostname: string,
	os: string,
	platform: string,
	arch: string,
	capabilities?: string[],
};

/**
 *  「已发出的邀请」列表条目。
 * 
 *  **没有邀请串本身** —— capability 明文不落盘也不出注册表（invite-persistence design D4），
 *  所以重启后拼不回原始链接。UI 只能显示元数据 + 提供撤销；想再分享就生成一条新的。
 */
export type PairInviteListItem = {
	/**  `sha256(capability)` 的 hex —— 撤销时回传，UI 当不透明 ID 用。 */
	id: string,
	/**  创建时刻（Unix 秒）。 */
	createdAt: number,
	/**  过期时刻（Unix 秒）。 */
	expiresAt: number,
	/**  已被对方消费（仍在列表里显示到过期，让用户知道它被用过）。 */
	consumed: boolean,
};

/**  邀请串解码后的展示投影（用于配对确认卡；不含 capability 等敏感字段）。 */
export type PairInvitePreview = {
	/**  发起方 NodeId（base58）。 */
	peerId: string,
	displayName: string,
	displayPlatform: string,
	/**  过期时刻（Unix 秒）——前端与当前时间比对判断是否已过期。 */
	expiresAt: number,
	/**  LocalOnly 策略（仅局域网）。 */
	localOnly: boolean,
};

export type PairedDeviceAdded = PairedDeviceInfo;

/**  已配对设备信息。 */
export type PairedDeviceInfo = {
	peerId: string,
	pairedAt: number,
	trustLevel?: DeviceTrustLevel,
	receivePolicy?: DeviceReceivePolicy,
	trustConfirmed?: boolean,
} & OsInfo;

/**
 *  已解除配对的设备 PeerId（base58）。事件名 `"paired-device-removed"`。
 * 
 *  它是前端移除该设备的**唯一**入口：命令自己不再顺手改本地状态，否则同一条记录
 *  会被两条路径各删一次，谁先谁后取决于时序。
 */
export type PairedDeviceRemoved = string;

/**
 *  配对方式。
 * 
 *  `Direct` 为局域网直连（授权依据是「对端在本机 mDNS 多播域内」）；`Invite` 携带
 *  一次性邀请凭证（128bit capability，见 [`swarmdrop_invite`]）——受邀方
 *  解码邀请串后连接发起方并出示凭证，发起方按
 *  [`InviteRegistry`](swarmdrop_invite::InviteRegistry) 校验。
 * 
 *  6 位分享码（旧 `Code` 变体 + DHT 发布/查询）已废弃——低熵可枚举、DHT 记录无法
 *  证明身份，被自包含签名邀请取代（openspec: pair-invite-protocol）。
 */
export type PairingMethod = { type: "direct" } | { type: "invite"; 
/**  128bit bearer 凭证明文。发起端以其 SHA-256 查询状态表，明文不落盘。 */
capability: [number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number] };

/**
 *  一次配对尝试的结果。
 * 
 *  `persisted` 与 [`revoke_pair_invite_by_id`] 的返回值同构：**本次运行内已生效，但重启后
 *  会变回去**。这类「一半成功」不能压成 `Err` —— 配对达成时对端已经把本机加进它的列表，
 *  本机再报失败只会让两台设备对同一件事的认知永久分叉。UI 该说的是「这台设备重启后会丢，
 *  建议重新配对」，不是「配对失败」。
 */
export type PairingOutcome = {
	response: PairingResponse,
	/**  设备是否已落盘。**仅当 `response` 为成功时有意义**，其余情况恒为 `true`。 */
	persisted: boolean,
};

/**  配对被拒绝的原因。 */
export type PairingRefuseReason = { type: "user_rejected" };

export type PairingRequest = {
	osInfo: OsInfo,
	timestamp: number,
	method: PairingMethod,
};

/**
 *  配对请求 payload：原 core 事件含 PeerId（非 specta-friendly），在此 host 层
 *  投影成 `String`，并把 `request` 字段 flatten 摊开（保持原 wire 形状）。
 */
export type PairingRequestPayload = {
	peerId: string,
	pendingId: number,
} & PairingRequest;

export type PairingRequestReceived = PairingRequestPayload;

export type PairingResponse = { status: "success" } | { status: "refused"; reason: PairingRefuseReason };

/**  冷启动期间缓冲的外部入口负载（一次取走，见 [`take_pending`]）。 */
export type PendingExternalOpen = {
	/**  「打开方式」送达的路径（可能多个）。 */
	paths: string[],
	/**  深链送达的配对邀请链接（只留最后一条，见 [`Inner::invite`]）。 */
	invite: string | null,
};

/**  `prepare_send` 的 hash 进度事件 */
export type PrepareProgressEvent = {
	/**  用于区分并发 prepare（多用户在不同会话同时调用） */
	preparedId: string,
	/**  当前正在 hash 的文件名 */
	currentFile: string,
	/**  已完成 hash 的文件数 */
	completedFiles: number,
	/**  总文件数 */
	totalFiles: number,
	/**  累积已 hash 的字节数（所有文件） */
	bytesHashed: number,
	/**  总字节数（所有文件） */
	totalBytes: number,
};

export type PreparedTransferResult = {
	preparedId: string,
	files: TransferFileResult[],
	totalSize: number,
};

/**  自动接收时的保存行为。 */
export type ReceiveSaveBehavior = 
/**  使用策略里配置的默认保存位置，接收完成后进入收件箱。 */
"inbox_and_default_save_location";

/**
 *  全局「暂停接收」状态变更（托盘 / 命令切换后广播，供 UI 与托盘同步）。
 *  事件名 `"receiving-paused-changed"`，payload 为 `true`=已暂停。
 */
export type ReceivingPausedChanged = boolean;

/**  断点续传被拒绝的原因。 */
export type ResumeRejectReason = { type: "cancelled" } | { type: "fatal_error" } | { type: "source_modified" } | { type: "checkpoint_invalid" } | { type: "peer_unavailable" } | { type: "session_not_found" };

export type ResumeTransferResult = {
	sessionId: string,
	direction: string,
	peerId: string,
	peerName: string,
	files: TransferFileResult[],
	totalSize: number,
	transferredBytes: number,
};

export type RuntimeTransferDirection = "send" | "receive" | "unknown";

export type ScannedSourceResult = {
	isDirectory: boolean,
	files: EnumeratedFile[],
	totalSize: number,
};

/**  `send_offer` 的返回类型 */
export type StartSendResult = {
	sessionId: string,
};

/**  suspended 原因（phase=Suspended 时有值）。 */
export type SuspendedReason = "local_paused" | "remote_paused" | "interrupted" | "peer_offline" | "app_restarted";

/**  terminal 原因（phase=Terminal 时有值）。 */
export type TerminalReason = "completed" | "cancelled" | "rejected" | "fatal_error" | 
/**
 *  入站 offer 的决策窗口耗尽，本端从未作答。
 * 
 *  **与 `Rejected` 分开是必要的，不是措辞讲究。** 对端看到的确实是一次婉拒（清理任务
 *  drop 掉 responder，RPC handler 据此回复），但本端用户**什么都没做**——把它记成
 *  「已拒绝」等于在他自己的传输历史里写一条他没做过的决定，而这恰恰是他下次想不起来
 *  「我拒过这个人吗」时会去查的地方。
 */
"expired";

export type TransferAccepted = TransferAcceptedEvent;

/**  对方接受 Offer 的事件 payload */
export type TransferAcceptedEvent = {
	sessionId: string,
};

export type TransferComplete = TransferCompleteEvent;

export type TransferCompleteEvent = {
	sessionId: string,
	direction: RuntimeTransferDirection,
	totalBytes: number,
	elapsedMs: number,
	saveLocation: CoreSaveLocation | null,
};

export type TransferDbError = TransferDbErrorEvent;

export type TransferDbErrorEvent = {
	sessionId: string,
	message: string,
};

/**  传输方向 */
export type TransferDirection = "send" | "receive";

export type TransferFailed = TransferFailedEvent;

export type TransferFailedEvent = {
	sessionId: string,
	direction: RuntimeTransferDirection,
	error: string,
};

export type TransferFileResult = {
	fileId: number,
	name: string,
	relativePath: string,
	size: number,
	isDirectory: boolean,
};

export type TransferOffer = TransferOfferEvent;

export type TransferOfferEvent = {
	sessionId: string,
	peerId: string,
	deviceName: string,
	files: TransferOfferFileEvent[],
	totalSize: number,
	/**  发起来源（人工 / MCP 代理），供接收端 UI 标识。 */
	origin: TransferOrigin,
	policyAction: string | null,
	policyReason: string | null,
};

export type TransferOfferFileEvent = {
	fileId: number,
	name: string,
	relativePath: string,
	size: number,
	isDirectory: boolean,
};

/**
 *  传输发起来源：人在应用内发起，或 AI 代理经 MCP 发起。
 * 
 *  由发送方自报、承载于 Offer，供接收端展示与 inbox 来源派生——是信息性/UX 信号，
 *  不作接收端安全边界（真正的控制是发送端 `allow_mcp_send_to_device` 门控）。
 */
export type TransferOrigin = 
/**  用户在应用内手动发起。 */
{ type: "human" } | 
/**  AI 代理经 MCP 发起；`client` 为 MCP 客户端名（如 claude-desktop），不可得时为 None。 */
{ type: "mcp"; client: string | null };

export type TransferPaused = TransferPausedEvent;

export type TransferPausedEvent = {
	sessionId: string,
	direction: RuntimeTransferDirection,
};

/**
 *  传输生命周期大状态（phase）。
 *  替代旧的扁平 [`SessionStatus`]（过渡期并存）：phase 表达大状态，
 *  具体原因由 [`SuspendedReason`] / [`TerminalReason`] 表达。
 */
export type TransferPhase = "offered" | "waiting_accept" | "active" | "suspended" | "terminal";

export type TransferProgress = TransferProgressEvent;

export type TransferProgressEvent = {
	sessionId: string,
	direction: RuntimeTransferDirection,
	totalFiles: number,
	completedFiles: number,
	totalBytes: number,
	transferredBytes: number,
	speed: number | null,
	eta: number | null,
	files: FileProgressInfo[],
};

/**  传输投影 DTO —— 前端唯一状态源（逐步替代旧的分散事件 + 扁平 `SessionStatus`）。 */
export type TransferProjection = {
	sessionId: string,
	direction: TransferDirection,
	peerId: string,
	peerName: string,
	phase: TransferPhase,
	suspendedReason: SuspendedReason | null,
	terminalReason: TerminalReason | null,
	recoverable: boolean,
	epoch: number,
	totalSize: number,
	transferredBytes: number,
	startedAt: number,
	updatedAt: number,
	finishedAt: number | null,
	/**  失败判别码（见 [`crate::failure`]）。曾是直达三端 UI 的自由中文文本。 */
	failure: FailureCode | null,
	policyAction: string | null,
	policyReason: string | null,
	savePath: CoreSaveLocation | null,
	/**
	 *  「打开文件夹」应定位的真实容器目录 URI(收到内容实际所在的文件夹),已在 core 解析:
	 *  各文件 `local_dir` 全部同一目录 → 该目录;否则回退存储根 `save_path`。前端直读,
	 *  不再自行兜底(已完成接收必为 `Some`)。
	 */
	contentRoot: string | null,
	files: TransferProjectionFile[],
};

export type TransferProjectionFile = {
	fileId: number,
	name: string,
	relativePath: string,
	size: number,
	transferredBytes: number,
};

/**  传输投影更新（redesign：前端唯一状态源）。事件名 `"transfer-projection-update"`。 */
export type TransferProjectionUpdate = TransferProjection;

export type TransferRejected = TransferRejectedEvent;

/**  对方拒绝 Offer 的事件 payload */
export type TransferRejectedEvent = {
	sessionId: string,
	reason: OfferRejectReason | null,
};

export type TransferResumed = TransferResumedEvent;

export type TransferResumedEvent = {
	sessionId: string,
	direction: RuntimeTransferDirection,
	peerId: string,
	peerName: string,
	files: TransferResumedFileInfo[],
	totalSize: number,
};

export type TransferResumedFileInfo = {
	fileId: number,
	name: string,
	relativePath: string,
	size: number,
	isDirectory: boolean,
};

/**
 *  承载连接的传输协议（由 multiaddr 协议栈判定，见 [`Addr::transport`](crate::Addr::transport)）。
 * 
 *  与 [`PathKind`] **正交**，排障时要一起看：`PathKind` 回答「字节走不走中继」，
 *  本枚举回答「字节跑在哪种传输上」。同是 `Relayed`，底层 TCP 还是 QUIC 指向
 *  完全不同的排查方向；同是 `Direct`，`Webrtc` 说明是打洞来的、`Quic` 说明是公网直拨。
 * 
 *  变体名刻意不写成 `WebRtc`：camelCase 序列化后会变成 `"webRtc"`，而三端 UI 与
 *  日志里这个词一直是 `webrtc`。
 */
export type TransportKind = 
/**  TCP（上叠 Noise + Yamux）。 */
"tcp" | 
/**  QUIC v1（传输层自带 TLS）。 */
"quic" | 
/**  WebRTC 打洞：**信令**经 relay，数据面一个字节不过中继。 */
"webrtc" | 
/**  WebRTC Direct：certhash 免信令免域名，浏览器够到原生端的唯一入口。 */
"webrtcDirect";

/**
 *  托盘「打开接收文件夹」：路径由前端 `savePath` 拥有，故由前端打开。
 *  事件名 `"tray-open-receive-folder"`。
 */
export type TrayOpenReceiveFolder = null;

/**  托盘「设置」：由前端路由跳转到设置页。事件名 `"tray-open-settings"`。 */
export type TrayOpenSettings = null;

/* Tauri Specta runtime */
type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

