/* tslint:disable */
/* eslint-disable */
/**
 * The `ReadableStreamType` enum.
 *
 * *This API requires the following crate features to be activated: `ReadableStreamType`*
 */

type ReadableStreamType = "bytes";
// 由 `cargo test -p swarmdrop-web --features specta --test specta_export` 生成，勿手改。
// 形状与运行期 serde_wasm_bindgen 序列化一致（u64 等已映射为 number）。

// This file has been generated by Specta. Do not edit this file manually.
/**
 *  链路详情：当前连接的可核对事实。
 *
 *  与 [`ConnectionType`] 的分工——那个是给所有人看的一句话结论（局域网 / 打洞 /
 *  中继），这个是「凭什么这么说」：走的哪条地址、哪种传输、经不经中继、经的是谁。
 *  三端 UI 把它放在默认折叠的区块里，普通用户看不到，排障时一眼能拿到全部证据。
 */
export type ConnectionDetails = {
    /**
     *  承载字节的传输协议。
     *
     *  `None` 是真实存在的情况，不是缺陷：入站中继连接的 `send_back_addr` 只有
     *  `/p2p/<src>` 一段，地址里没有任何传输信息。呈现层照实显示「未知」。
     */
    transport: TransportKind | null,
    /**  当前最优连接的远端 multiaddr，原样给出——便于直接粘进 issue 或与日志比对。 */
    remoteAddr: string,
    /**
     *  中转身份：经中继时是那台 relay 的 PeerId，直连为 `None`。
     *
     *  「经中继」三个字对排障几乎没用，得说清楚经的是哪一台——自建 relay 还是
     *  局域网里的 LanHelper，处理方式完全不同。
     */
    relay: string | null,
};

/**  `connect()` 的结构化返回。 */
export type ConnectionJson = {
    path: PathKindJson,
    addr: string,
};

/**  连接类型。 */
export type ConnectionType = "lan" | "dcutr" | "relay";

/**
 *  接收端保存位置（host-agnostic）。
 *
 *  core 内部统一用此类型，避免把 `entity::SaveLocation`（SeaORM 实体细节）
 *  暴露到公共 API 上。DB 边界用 [`From`] 与 `entity::SaveLocation` 双向转换。
 */
export type CoreSaveLocation =
/**  文件系统绝对路径（桌面）或 `Paths.document` 子路径（移动端）。 */
{ type: "path"; path: string };

/**  统一的设备输出类型。 */
export type Device = {
    peerId: string,
    status: DeviceStatus,
    connection: ConnectionType | null,
    /**
     *  链路详情。仅在线且内核报告过连接地址时有值——离线设备、以及只靠 mDNS
     *  地址推断出 `connection` 的宽限期内，这里是 `None`（没连接就没有链路可谈）。
     */
    connectionDetails: ConnectionDetails | null,
    /**
     *  内核尝试过局域网直连升级但失败了。
     *
     *  与 `connection == Relay` 一起看才有意义：那时它把「对端本来就在外网」与
     *  「对端就在同一网段却连不上」分开。后者呈现层应给出可行动的提示——查防火墙，
     *  或（浏览器上）允许本地网络访问。
     */
    lanUpgradeFailed: boolean,
    latency: number | null,
    isPaired: boolean,
    trustLevel: DeviceTrustLevel | null,
    receivePolicy: DeviceReceivePolicy | null,
    trustConfirmed: boolean | null,
} & OsInfo;

/**
 *  可信设备接收策略。
 *
 *  字段保持 host-neutral：保存位置使用字符串表达的 host 路径，桌面端解释为绝对路径，
 *  移动端后续可解释为应用文档目录下的子路径。
 */
export type DeviceReceivePolicy = {
    autoAccept: boolean,
    requireConfirmation: boolean,
    maxTransferBytes?: number | null,
    allowDirectories: boolean,
    allowRelayAutoAccept: boolean,
    saveBehavior?: ReceiveSaveBehavior,
    defaultSaveLocation?: string | null,
    allowMcpSendToDevice: boolean,
    /**
     *  允许 MCP/AI 代该来源设备处置入站 offer（接受或拒绝）。
     *
     *  默认 false。与发送侧 `allow_mcp_send_to_device` **刻意不对称**：代收会往磁盘写入、
     *  风险更高，故即便对 Owned 设备也需用户逐设备显式开启（发送侧则随信任级别自动派生）。
     *  只能由用户在 app 的设备信任策略中开启，agent 无任何写权限——防止自我提权、静默代收。
     */
    allowMcpAcceptFromDevice?: boolean,
    expiresAt?: number | null,
};

/**  设备状态。 */
export type DeviceStatus = "online" | "offline";

/**  已配对设备信任等级。 */
export type DeviceTrustLevel = "owned" | "collaborator" | "temporary" | "blocked";

/**  传输文件元信息。 */
export type FileInfo = {
    fileId: number,
    name: string,
    relativePath: string,
    size: number,
    checksum: string,
};

export type FileProgressInfo = {
    fileId: number,
    name: string,
    size: number,
    transferred: number,
    status: FileTransferStatus,
};

export type FileTransferStatus = "pending" | "transferring" | "completed";

/**  收件箱内容类型。 */
export type InboxContentKind = "files" | "text" | "clipboard" | "bundle";

/**  搜索命中条目下的文件标识（供下钻定位）。 */
export type InboxHitFile = {
    name: string,
    relativePath: string,
};

/**  收件箱详情 DTO。 */
export type InboxItemDetail = {
    files: InboxItemFileEntry[],
    transfer: TransferProjection | null,
} & InboxItemSummary;

/**  收件箱文件 DTO。 */
export type InboxItemFileEntry = {
    id: number,
    transferFileId: number | null,
    /**  条目根之下的相对路径。**Web 宿主删文件用这个**——OPFS 的键就是它。 */
    relativePath: string,
    name: string,
    size: number,
    checksum: string,
    /**
     *  宿主可直接操作的完整路径。**桌面 / 移动删文件用这个**（那边是真实文件系统路径）；
     *  **Web 上它是带 `opfs:/` 前缀的展示值，喂给 `remove_path` 会去找一个叫 `opfs:` 的目录**。
     *
     *  两个路径字段并存且「该用哪个」按端不同，是这个 DTO 最容易踩空的地方——所以写在这里，
     *  而不是让每个宿主自己从别处推断。
     */
    localPath: string,
    missing: boolean,
};

/**  收件箱列表条目 DTO。 */
export type InboxItemSummary = {
    id: string,
    transferSessionId: string | null,
    sourcePeerId: string,
    sourceName: string,
    sourceKind: InboxSourceKind,
    contentKind: InboxContentKind,
    title: string,
    itemCount: number,
    totalSize: number,
    rootPath: string | null,
    contentHash: string | null,
    receivedAt: number,
    lastOpenedAt: number | null,
    archivedAt: number | null,
    deletedAt: number | null,
    missing: boolean,
};

/**  收件箱搜索命中（item 粒度）。 */
export type InboxSearchHit = {
    id: string,
    title: string,
    sourceName: string,
    itemCount: number,
    rootPath: string | null,
    receivedAt: number,
    /**
     *  命中所在文本的片段（在 Rust 端按子串位置切窗口生成）。
     *
     *  `None` = **不该渲染片段行**：命中的是标题或来源名（条目行上已经显示着），
     *  或一个候选都没命中。判据在 [`inbox_snippet`]，三端不要各判一遍。
     */
    snippet: string | null,
    /**  该条目下的文件（文件名 + 相对路径），供 get_inbox_file 下钻。 */
    files: InboxHitFile[],
};

/**  收件箱来源类型。 */
export type InboxSourceKind = "paired_device" | "share_code" | "mcp" | "unknown";

/**
 *  「已发出的邀请」列表条目（openspec: invite-persistence）。
 *
 *  **没有邀请串本身**：capability 明文不落盘也不出注册表，刷新后拼不回原始链接。
 *  UI 只显示元数据 + 提供撤销；想再分享就生成一条新的。
 *
 *  时间戳用字符串承载 Unix 秒，与 `pendingId` 同一个理由（避免 u64 → BigInt 的取回麻烦）。
 */
export type InviteListItemJson = {
    /**  `sha256(capability)` 的 hex —— 撤销时回传，UI 当不透明 ID 用。 */
    id: string,
    createdAt: string,
    expiresAt: string,
    /**  已被对方消费（仍显示到过期，让用户知道它被用过）。 */
    consumed: boolean,
};

/**  挂起 offer 的 JS 投影（`pending_offers()` 返回 `OfferJson[]`）。 */
export type OfferJson = {
    sessionId: string,
    peerId: string,
    peerName: string,
    totalSize: number,
    files: FileInfo[],
};

/**  Offer 被拒绝的原因。 */
export type OfferRejectReason = { type: "not_paired" } | { type: "user_declined" } | { type: "policy_rejected" } |
/**  接收方处于全局「暂停接收」状态，婉拒新 offer。 */
{ type: "receiving_paused" };

/**
 *  设备操作系统信息。
 *
 *  `hostname` 是系统主机名（运行时取，桌面端通常是机器名，移动端通常拿不到）；
 *  `name` 是用户在 onboarding / 设置里起的名字（持久化），由 core 的组合根从
 *  [`DeviceConfig`](crate::ports::DeviceConfig) 端口填充，UI 显示按
 *  `name.as_deref().unwrap_or(&hostname)` 回退。
 */
export type OsInfo = {
    /**  用户起的设备名；缺省时回退到 `hostname`。 */
    name?: string | null,
    hostname: string,
    os: string,
    platform: string,
    arch: string,
    capabilities?: string[],
};

/**
 *  邀请串解码后的展示投影（配对确认卡用）。
 *
 *  **不含 capability**：那是 128bit bearer 凭据，明文绝不出 wasm 边界——确认卡只需要
 *  「这是谁、还有效多久、是不是仅局域网」，多给一个字段就多一条泄漏路径。
 *
 *  **TTL 由调用方按 `expiresAt` 判**，这里不放 `expired: bool`：确认卡会在屏幕上停留几十秒，
 *  而布尔在序列化那一刻就开始变旧。权威判定本来也在发起端的 `InviteRegistry`，
 *  解码侧的预检只为 UX（见 `PairInvite::decode` 的文档）。
 *
 *  `expiresAt` 用字符串承载 Unix 秒，与 [`InviteListItemJson`] 同一个理由。
 */
export type PairInvitePreviewJson = {
    /**
     *  发起方 NodeId（base58）。取自签名覆盖范围内的 `inviter_id`，伪造不了——
     *  自我过滤 / 已配对过滤都该以它为判据。
     */
    peerId: string,
    displayName: string,
    displayPlatform: string,
    expiresAt: string,
    /**  LocalOnly 策略（受邀方只用私网地址、禁公网 fallback）。 */
    localOnly: boolean,
};

/**  连接路径类别（[`swarmdrop_net_base::PathKind`] 的 JS 投影，TS 侧是字符串联合）。 */
export type PathKindJson = "local" | "direct" | "relayed";

/**
 *  挂起入站配对请求的 JS 投影（`pending_pairing_requests()` 返回）。
 *
 *  browser-as-inviter 用：桌面消费浏览器生成的 invite 后，浏览器（邀请方）本机需弹确认。
 *  `pendingId` 以字符串承载核心的 u64 pending id（避免 JS number 精度 + serde_wasm_bindgen
 *  对 u64 产 BigInt 的取回麻烦），`respond_pairing_request` 再 parse 回 u64。
 */
export type PendingPairingJson = {
    pendingId: string,
    peerId: string,
    deviceName: string,
};

/**  `prepare_send` 的 hash 进度事件 */
export type PrepareProgressEvent = {
    /**  用于区分并发 prepare（多用户在不同会话同时调用） */
    preparedId: string,
    /**  当前正在 hash 的文件名 */
    currentFile: string,
    /**  已完成 hash 的文件数 */
    completedFiles: number,
    /**  总文件数 */
    totalFiles: number,
    /**  累积已 hash 的字节数（所有文件） */
    bytesHashed: number,
    /**  总字节数（所有文件） */
    totalBytes: number,
};

/**  自动接收时的保存行为。 */
export type ReceiveSaveBehavior =
/**  使用策略里配置的默认保存位置，接收完成后进入收件箱。 */
"inbox_and_default_save_location";

/**  单个 relay 意图的状态快照（`relays_state()` 元素 / `relays_changed()` 流的产出单元）。 */
export type RelayInfoJson = {
    /**  relay 节点身份（base58 NodeId）。 */
    id: string,
    state: RelayStateKind,
    /**  `active` 时为本机经该 relay 的完整可达地址（内核拼装下发），其余为 null。 */
    circuitAddr: string | null,
    /**
     *  `failed` 时的末次错误描述，其余为 null。重试轮数不下发——那是
     *  策略层内账（supervisor 唯一持有），诊断走日志。
     */
    lastError: string | null,
};

/**  relay reservation 状态类别（[`swarmdrop_net::RelayState`] 的 JS 投影，TS 侧字符串联合）。 */
export type RelayStateKind = "connecting" | "active" | "failed";

export type RuntimeTransferDirection = "send" | "receive" | "unknown";

/**  suspended 原因（phase=Suspended 时有值）。 */
export type SuspendedReason = "local_paused" | "remote_paused" | "interrupted" | "peer_offline" | "app_restarted";

/**  terminal 原因（phase=Terminal 时有值）。 */
export type TerminalReason = "completed" | "cancelled" | "rejected" | "fatal_error";

/**  对方接受 Offer 的事件 payload */
export type TransferAcceptedEvent = {
    sessionId: string,
};

export type TransferCompleteEvent = {
    sessionId: string,
    direction: RuntimeTransferDirection,
    totalBytes: number,
    elapsedMs: number,
    saveLocation: CoreSaveLocation | null,
};

export type TransferDbErrorEvent = {
    sessionId: string,
    message: string,
};

/**  传输方向 */
export type TransferDirection = "send" | "receive";

export type TransferFailedEvent = {
    sessionId: string,
    direction: RuntimeTransferDirection,
    error: string,
};

export type TransferOfferEvent = {
    sessionId: string,
    peerId: string,
    deviceName: string,
    files: TransferOfferFileEvent[],
    totalSize: number,
    /**  发起来源（人工 / MCP 代理），供接收端 UI 标识。 */
    origin: TransferOrigin,
    policyAction: string | null,
    policyReason: string | null,
};

export type TransferOfferFileEvent = {
    fileId: number,
    name: string,
    relativePath: string,
    size: number,
    isDirectory: boolean,
};

/**
 *  传输发起来源：人在应用内发起，或 AI 代理经 MCP 发起。
 *
 *  由发送方自报、承载于 Offer，供接收端展示与 inbox 来源派生——是信息性/UX 信号，
 *  不作接收端安全边界（真正的控制是发送端 `allow_mcp_send_to_device` 门控）。
 */
export type TransferOrigin =
/**  用户在应用内手动发起。 */
{ type: "human" } |
/**  AI 代理经 MCP 发起；`client` 为 MCP 客户端名（如 claude-desktop），不可得时为 None。 */
{ type: "mcp"; client: string | null };

export type TransferPausedEvent = {
    sessionId: string,
    direction: RuntimeTransferDirection,
};

/**
 *  传输生命周期大状态（phase）。
 *  替代旧的扁平 [`SessionStatus`]（过渡期并存）：phase 表达大状态，
 *  具体原因由 [`SuspendedReason`] / [`TerminalReason`] 表达。
 */
export type TransferPhase = "offered" | "waiting_accept" | "active" | "suspended" | "terminal";

export type TransferProgressEvent = {
    sessionId: string,
    direction: RuntimeTransferDirection,
    totalFiles: number,
    completedFiles: number,
    totalBytes: number,
    transferredBytes: number,
    speed: number | null,
    eta: number | null,
    files: FileProgressInfo[],
};

/**  传输投影 DTO —— 前端唯一状态源（逐步替代旧的分散事件 + 扁平 `SessionStatus`）。 */
export type TransferProjection = {
    sessionId: string,
    direction: TransferDirection,
    peerId: string,
    peerName: string,
    phase: TransferPhase,
    suspendedReason: SuspendedReason | null,
    terminalReason: TerminalReason | null,
    recoverable: boolean,
    epoch: number,
    totalSize: number,
    transferredBytes: number,
    startedAt: number,
    updatedAt: number,
    finishedAt: number | null,
    errorMessage: string | null,
    policyAction: string | null,
    policyReason: string | null,
    savePath: CoreSaveLocation | null,
    /**
     *  「打开文件夹」应定位的真实容器目录 URI(收到内容实际所在的文件夹),已在 core 解析:
     *  各文件 `local_dir` 全部同一目录 → 该目录;否则回退存储根 `save_path`。前端直读,
     *  不再自行兜底(已完成接收必为 `Some`)。
     */
    contentRoot: string | null,
    files: TransferProjectionFile[],
};

export type TransferProjectionFile = {
    fileId: number,
    name: string,
    relativePath: string,
    size: number,
    transferredBytes: number,
};

/**  对方拒绝 Offer 的事件 payload */
export type TransferRejectedEvent = {
    sessionId: string,
    reason: OfferRejectReason | null,
};

export type TransferResumedEvent = {
    sessionId: string,
    direction: RuntimeTransferDirection,
    peerId: string,
    peerName: string,
    files: TransferResumedFileInfo[],
    totalSize: number,
};

export type TransferResumedFileInfo = {
    fileId: number,
    name: string,
    relativePath: string,
    size: number,
    isDirectory: boolean,
};

/**
 *  承载连接的传输协议（由 multiaddr 协议栈判定，见 [`Addr::transport`](crate::Addr::transport)）。
 *
 *  与 [`PathKind`] **正交**，排障时要一起看：`PathKind` 回答「字节走不走中继」，
 *  本枚举回答「字节跑在哪种传输上」。同是 `Relayed`，底层 TCP 还是 QUIC 指向
 *  完全不同的排查方向；同是 `Direct`，`Webrtc` 说明是打洞来的、`Quic` 说明是公网直拨。
 *
 *  变体名刻意不写成 `WebRtc`：camelCase 序列化后会变成 `"webRtc"`，而三端 UI 与
 *  日志里这个词一直是 `webrtc`。
 */
export type TransportKind =
/**  TCP（上叠 Noise + Yamux）。 */
"tcp" |
/**  QUIC v1（传输层自带 TLS）。 */
"quic" |
/**  WebRTC 打洞：**信令**经 relay，数据面一个字节不过中继。 */
"webrtc" |
/**  WebRTC Direct：certhash 免信令免域名，浏览器够到原生端的唯一入口。 */
"webrtcDirect";

/**
 *  Web 壳对外错误。`kind` 供 JS 分支，`message` 供展示。
 *
 *  wasm-bindgen 方法 reject 的错误值就是本类型的序列化对象（`{ kind, message }`）——
 *  **不拍成字符串**（字符串丢了机器可判别的 kind）。JsValue 转换在 `error.rs`。
 */
export type WebError =
/**  身份 / 密钥错误。 */
{ kind: "identity"; message: string } |
/**  网络 / 连接 / DHT 错误。 */
{ kind: "network"; message: string } |
/**  传输错误。 */
{ kind: "transfer"; message: string } |
/**  入参非法（地址格式、缺 `/p2p/` 等）。 */
{ kind: "invalidInput"; message: string } |
/**
 *  调用被 `AbortSignal` 取消。**abort ≠ 撤回拨号**：Promise 立即 reject 且
 *  无常驻意图残留，但在途拨号会继续到自然失败（libp2p 无逐次拨号取消面）。
 */
{ kind: "aborted"; message: string } |
/**  分享码不存在 / 已过期。 */
{ kind: "notFound"; message: string } |
/**  存储（OPFS / localStorage）错误。 */
{ kind: "storage"; message: string };

/**
 *  `TransferEvent` 的可序列化镜像（1:1 变体，字段与 payload 同名）。
 *
 *  `TransferEvent` 本身未 derive `Serialize`（transfer 不改）——与桌面把它映射进
 *  `CoreEvent` 的适配范式一致。`events()` 的 ReadableStream 逐条产出本类型的序列化对象。
 */
export type WebTransferEvent = { type: "transferOfferReceived"; offer: TransferOfferEvent } | { type: "transferProgress"; event: TransferProgressEvent } | { type: "transferAccepted"; event: TransferAcceptedEvent } | { type: "transferRejected"; event: TransferRejectedEvent } | { type: "transferCompleted"; event: TransferCompleteEvent } | { type: "transferFailed"; event: TransferFailedEvent } | { type: "transferPaused"; event: TransferPausedEvent } | { type: "transferResumed"; event: TransferResumedEvent } | { type: "transferDbError"; event: TransferDbErrorEvent } | { type: "transferProjection"; projection: TransferProjection } | { type: "prepareProgress"; event: PrepareProgressEvent };



export class IntoUnderlyingByteSource {
    private constructor();
    free(): void;
    [Symbol.dispose](): void;
    cancel(): void;
    pull(controller: ReadableByteStreamController): Promise<any>;
    start(controller: ReadableByteStreamController): void;
    readonly autoAllocateChunkSize: number;
    readonly type: ReadableStreamType;
}

export class IntoUnderlyingSink {
    private constructor();
    free(): void;
    [Symbol.dispose](): void;
    abort(reason: any): Promise<any>;
    close(): Promise<any>;
    write(chunk: any): Promise<any>;
}

export class IntoUnderlyingSource {
    private constructor();
    free(): void;
    [Symbol.dispose](): void;
    cancel(): void;
    pull(controller: ReadableStreamDefaultController): Promise<any>;
}

/**
 * 浏览器传输端节点。
 */
export class WebNode {
    private constructor();
    free(): void;
    [Symbol.dispose](): void;
    /**
     * 接受入站 offer 并开始接收（落 OPFS）。
     */
    accept_offer(session_id: string): Promise<void>;
    /**
     * 归档 / 取消归档收件箱条目。条目不存在时静默成功。
     */
    archive_inbox_item(item_id: string, archived: boolean): Promise<void>;
    /**
     * 取消一条**接收**会话。
     *
     * 与 [`cancel_send`](Self::cancel_send) 同样只是导出：域层通知对端停发、
     * dispatch `UserCommand::Cancel` 进不可续传终态，并调 `cleanup_part_files()`
     * 逐个走 `FileAccess::cleanup_sink` 清掉本次会话开出来的半成品——在 Web 上那就是
     * [`OpfsFileAccess::cleanup_sink`](crate::file_access)，OPFS 里的截断文件会被真删掉。
     *
     * **方向不自动判**（要发送就调 `cancel_send`）：取消是有副作用的操作（发帧、删文件、
     * 写终态），拿它当探针试方向会把「dispatch 失败」误读成「不是这个方向」。
     */
    cancel_receive(session_id: string): Promise<void>;
    /**
     * 取消一条**发送**会话。
     *
     * 只是一条 wasm 边界上的线，取消语义整套在域层（`crates/transfer`）里做完：
     * 按 wire 发 Cancel 帧通知对端（对方随即清掉自己的半成品）、dispatch
     * `UserCommand::Cancel` 让协调器把会话写成**不可续传**的终态（`recoverable=false`，
     * 故刷新后不会再冒出「续传」按钮）、并按 `session_id` 索引只动这一条会话。
     * **Web 侧不要再补任何本地取消逻辑**，否则就有了第二条状态机路径。
     *
     * 覆盖「offer 已发出、对方还没接受」这条边界：此时没有 send actor，域层会回落到
     * `outbound_offers`（`flow/send.rs`）——丢弃 prepared、照样 dispatch `Cancel`，
     * 所以「发出去等半天对方不理」也止得住损，调用方无需区分。
     */
    cancel_send(session_id: string): Promise<void>;
    /**
     * 清空传输历史：删除所有**已结束**的会话记录，进行中与已中断的一条不动。
     *
     * 同样只清账本，收件箱里的文件不受影响（见 [`delete_transfer_session`](Self::delete_transfer_session)）。
     */
    clear_transfer_history(): Promise<void>;
    /**
     * 关停节点：NetManager::shutdown 取消内部 token（停 presence / infra / event-loop +
     * transfer cleanup，drop Router 停路由）并关 Endpoint（drop Swarm → 断连）——
     * 与 `WebNode.endpoint` 是同一 handle，无需再显式关一次。
     */
    close(): Promise<void>;
    /**
     * 拨任意 multiaddr（`.../ws` 或 `.../webrtc-direct/certhash/...`，须带 `/p2p/<id>`）。
     * 返回结构化的连接信息（`{ path: "local"|"direct"|"relayed", addr }`）。
     *
     * `signal`（可选）：标准 `AbortSignal`——超时组合用平台原语表达
     * （`AbortSignal.timeout(5000)` / `AbortSignal.any([...])`）。abort 时 Promise
     * 立即以 `{ kind: "aborted" }` reject；**abort ≠ 撤回拨号**（在途拨号继续到
     * 自然失败，无常驻意图残留）。不传 signal 时由内核兜底超时（Browser 15s）
     * 保证有限时间内 settle。
     */
    connect(addr: string, signal?: AbortSignal | null): Promise<ConnectionJson>;
    /**
     * 受邀方：消费邀请串完成**真配对握手**。
     *
     * `pair_with_invite` 解码验签 → TTL 预检 → 按 `TransportPolicy` 过滤地址 → 连邀请方出示
     * capability（`PairingMethod::Invite`）→ 邀请方（桌面）校验 CAS 一次性消费 + 用户确认 →
     * 双方写配对记录。身份 pin 由握手强制（连到的必然是 `inviter_id`）。成功返回已配对对端的
     * NodeId（base58）；确认发生在**邀请方**侧，浏览器侧无需交互。配对后该对端进入本机信任
     * 表，双向传输（收 / 发）不再被 `NotPaired` 拦。
     */
    connect_invite(invite: string): Promise<string>;
    /**
     * 解码并验签邀请串，返回对端展示信息 —— **不发起配对、不消费**。
     *
     * 供受邀方在粘贴 / 点链接进来之后先亮一张确认卡：篡改、伪造、格式不认的邀请在这里
     * 就被拒掉，用户点「配对」才走 [`connect_invite`](Self::connect_invite)。
     *
     * **纯本地**：不拨号、不查 DHT、不碰 IndexedDB，全程零出网 —— 确认卡出现之前不该有
     * 任何网络行为，这条是它成立的依据。
     *
     * **判不出「已撤销」**：撤销状态只在邀请方的注册表里，受邀方手上只有一段自包含的
     * 签名串，那件事根本没传播过来。要判就得出网，与上一条冲突。所以撤销只能在
     * `connect_invite` 阶段由邀请方拒绝，调用方把那个失败渲染成人话即可 ——
     * **不要在本地发明撤销判据**（最容易发明的「查 `list_invites` 看在不在」尤其错：
     * 那是本机自己发出的邀请，对受邀方永远为空，于是所有邀请都会被判成已撤销）。
     *
     * 同步返回：与 [`invite_qr_svg`](Self::invite_qr_svg) 一样是纯计算，`&self` 只是
     * 可达性的代价（前端拿模块句柄的唯一路径是 `getNode()`）。
     */
    decode_invite_preview(invite: string): PairInvitePreviewJson;
    /**
     * 软删除收件箱条目；`delete_local_files` 为真时连 OPFS 里的文件一起删。
     *
     * 与桌面 `delete_inbox_item(item_id, delete_local_files)` 同签名同语义：**是否连文件
     * 一起删由宿主决定，端口只管账本**（`delete_inbox_item_record` 永远只软删记录）。
     *
     * 不删文件时那份 OPFS 副本会成为孤儿——记录一软删，`list`/`search`/`detail` 就都看不到
     * 它了，配额却还占着，用户唯一的出路是浏览器的「清除站点数据」。所以这个入口不是锦上添花：
     * 没有它，Web 端的每一次删除都在泄漏。
     *
     * 编排（顺序、失败处理、幂等）是**三端共用的领域规则**，住在
     * [`swarmdrop_transfer::inbox::delete_inbox_item`]——本方法只做参数解析与错误转换。
     * 「OPFS 的键要剥掉 `opfs:/` 前缀」那一层在 [`OpfsFileAccess::delete_finalized_file`]，
     * 编排不需要知道哪一端用哪个字段。
     */
    delete_inbox_item(item_id: string, delete_local_files: boolean): Promise<void>;
    /**
     * 删除一条传输记录。
     *
     * **只删记录**：OPFS 里已落盘的文件不动，收件箱照旧能看能下载——文件的生命周期归
     * 收件箱侧管（三端一致的分工，别在这里发明 Web 特例）。
     *
     * 进行中的会话会被域层拒绝（`TransferManager::delete_session` 的守卫），错误经
     * `WebError` 透出——UI 的按钮可见性只是第一道，绕过它直调导出同样删不掉。
     */
    delete_transfer_session(session_id: string): Promise<void>;
    /**
     * 完成接收后，把 OPFS 里的文件读回成 blob URL 供 `<a download>` 下载。
     */
    download_url(relative_path: string): Promise<string>;
    /**
     * 传输事件流（逐条产出 `WebTransferEvent` 序列化对象）。**只能取一次**（单点消费）。
     */
    events(): ReadableStream<WebTransferEvent>;
    /**
     * 发起方（browser-as-inviter）：生成一次性签名邀请串，供桌面/移动扫码或粘贴消费。
     *
     * `local_only=true` 走 LocalOnly（受邀方只用私网地址）。邀请自包含本机 dialable 地址提示——
     * 浏览器不 listen 本地 socket，其可达地址来自 **relay reservation**（circuit 地址）；故桌面要
     * 拨得到本机，本机需先经 [`relays_ensure`](Self::relays_ensure) 在某 helper 上建 reservation
     * （等到 `active`），否则邀请里无可拨地址、消费方连不上。
     * **async 化于 invite-persistence**：生成时要把邀请写穿进 IndexedDB，否则刷新页面
     * 后本机就不认识刚发出去的那条邀请了（注册表 fail-closed，查不到即拒绝）。
     */
    generate_invite(local_only: boolean): Promise<string>;
    /**
     * 单条收件箱详情（含文件清单与关联传输投影）；不存在或已软删返回 `null`。
     */
    inbox_item(item_id: string): Promise<InboxItemDetail | null>;
    /**
     * 按传输会话 id 取收件箱详情（「这次传输收到的东西」的反查）；无关联返回 `null`。
     */
    inbox_item_by_session(session_id: string): Promise<InboxItemDetail | null>;
    /**
     * 收件箱条目列表，按 `receivedAt` 倒序；`includeArchived=false` 时排除已归档项，
     * 软删项一律不返回。
     *
     * **返回的是完整详情**（含文件清单与关联传输投影），不是 summary。前端此前拿到
     * summary 后要 `Promise.all(summaries.map(inbox_item))` 逐条补详情——1 + N 次 wasm
     * 调用，且拉详情与拉列表之间条目可能已被删（于是要 `filter(d => d !== null)` 去兜
     * 一个自己制造出来的竞态）。而收件箱在浏览器侧是全内存表，列表与详情读的是同一份
     * 数据，那 N 次调用买不到任何新鲜度。
     */
    inbox_items(include_archived: boolean): Promise<InboxItemDetail[]>;
    /**
     * 邀请二维码的 SVG 字符串（深模块 + 透明背景，渲染端自己套白卡）。
     *
     * 编码规范由 [`swarmdrop_invite::qr`] 三端单点固化（原样编码 + 最优分段 + ECL::M +
     * quiet zone）——浏览器**不要**另引 JS 二维码库：三端各画一遍，码面规范就会漂，
     * 而漂了的表现是「某一端生成的码另一端扫不出来」，很难归因。
     *
     * **这是纯函数，`&self` 只是可达性的代价，不代表它是节点能力**——别把这里当作
     * 「纯计算也该挂 `WebNode`」的先例。做成自由函数或 `WebNode` 的静态方法都更贴切，
     * 但前端拿 wasm 模块句柄的唯一路径是 `node-runtime.ts` 里那个**不导出**的
     * `loadModule()`（静态 import 会在 Next 预渲染时挂，故只能动态 import + 记忆化）。
     * 走自由函数就得再开一个 `getModule()` 访问器并自己缓存一份——为一个叶子功能
     * 加这套机器不值，而 `getNode()` 是现成的。
     *
     * 同步返回：纯计算，不碰 IndexedDB 也不碰网络。
     */
    invite_qr_svg(invite: string): string;
    /**
     * 本机未过期的已发出邀请（最近生成的在前）。
     *
     * TTL 24h + 跨刷新存活之后，「我现在有几条邀请在外面飘」需要能看见 ——
     * 这个列表与 [`revoke_invite_by_id`](Self::revoke_invite_by_id) 是那段窗口的控制手段。
     */
    list_invites(): InviteListItemJson[];
    /**
     * 标记条目最近打开时间（用户点开详情/下载时调）。条目不存在时静默成功。
     */
    mark_inbox_item_opened(item_id: string): Promise<void>;
    /**
     * 本节点身份（base58）。
     */
    node_id(): string;
    /**
     * 已配对设备清单——与桌面 `list_devices` 同源的 [`DeviceManager::get_devices`] 读模型
     * （含在线状态/连接类型，presence 在 Web 侧同样运作）。
     */
    paired_devices(): Device[];
    /**
     * 暂停一条**接收**会话。
     *
     * 与 [`pause_send`](Self::pause_send) 对称，但落盘的半成品**不清理**（那是取消才做的事）
     * ——OPFS 里已写入的部分连同 checkpoint 一起留着，`resume` 从断点续。
     *
     * 接收方向的 suspended 会话 `worth_persisting`，所以它**跨刷新也能续**：重新打开页面后
     * 会话仍在传输列表里，「续传」照常可点。
     *
     * **方向不自动判**，理由同 `cancel_*`：暂停有副作用（停 actor、写状态、通知对端），
     * 拿它当探针试方向会在第一条真失败时顺手对另一个方向也来一遍。
     */
    pause_receive(session_id: string): Promise<void>;
    /**
     * 暂停一条**发送**会话。
     *
     * 与取消同样只是一条 wasm 边界上的线：域层停掉 sender actor、把文件级进度落库、
     * dispatch `UserCommand::Pause`（`active` → `suspended(LocalPaused)`，
     * **`recoverable = true`**），并通知对端。之后调 [`resume`](Self::resume) 接着传。
     *
     * ## 浏览器上它为什么恢复得了（与「发送不跨刷新」不矛盾）
     *
     * [`initiate_resume`] 要的两样东西在**同一个页面生命周期内**都还在：
     *
     * - **会话记录**：`WebTransferStore` 是「内存读缓存 + IndexedDB 写穿」，`create_session`
     *   无条件写内存，`worth_persisting` 只决定要不要**再**写 IndexedDB。所以非终态发送
     *   会话查得到，只是刷新后就没了。
     * - **文件内容**：用户选的 `File` 存在 [`OpfsFileAccess`](crate::file_access) 的源注册表
     *   里，登记后不移除，`read_source_chunk` 照常读得到。
     *
     * 刷新之后两样同时消失，`initiate_resume` 在 `find_session` 那一步就报「会话不存在」
     * ——那正是应有的行为，不需要在这里另设守卫（见 `store.rs` 的落库范围表）。
     */
    pause_send(session_id: string): Promise<void>;
    /**
     * 当前挂起（待确认）的入站 offer 列表。
     */
    pending_offers(): OfferJson[];
    /**
     * 挂起的入站配对请求（消费方扫/粘本机 invite 后到达）。**取出即清空**，调用方自行累积展示。
     */
    pending_pairing_requests(): PendingPairingJson[];
    /**
     * 拒绝入站 offer。
     */
    reject_offer(session_id: string): Promise<void>;
    /**
     * relay 状态变化流：每次变化产出一份全量快照（可直接 setState）。
     * 可多次调用（每次独立订阅），与 `events()` 的单点消费不同。
     */
    relays_changed(): ReadableStream<RelayInfoJson[]>;
    /**
     * 撤销 relay 意图（[`relays_ensure`](Self::relays_ensure) 的对称面）。
     *
     * **真撤销**而非停止等待：停止后台收敛重试、关闭 circuit listener、立刻
     * 断开与该 helper 的连接（含中止在途拨号），条目从状态集合消失。
     */
    relays_drop(helper_id: string): Promise<void>;
    /**
     * 登记一个 relay helper 的常驻可达意图（幂等，同步返回）。
     *
     * 浏览器被动接收连接的唯一入口。拨号 / reservation / 断线重建由 core 的
     * InfraSupervisor 统一收敛（最迟 1s 内启动第一轮，失败退避重试）；进度经
     * [`relays_state`](Self::relays_state) / [`relays_changed`](Self::relays_changed)
     * 观测，或用 [`relays_until_active`](Self::relays_until_active) 等首次建立。
     *
     * 返回 helper 的 base58 NodeId——即 `relays_drop` / `relays_until_active` 的
     * 入参，调用方直接串联，无需自行解析 multiaddr 的 `/p2p/` 段。
     */
    relays_ensure(helper_addr: string): string;
    /**
     * 全量 relay 状态快照（`{ id, state, circuitAddr?, lastError? }[]`）。
     */
    relays_state(): RelayInfoJson[];
    /**
     * 等待某 relay 首次进入 `active`，resolve 出 circuit 可达地址（内核拼装）。
     *
     * 观察到 `failed` 时**立即 reject**（把「要不要再等下一轮退避」还给调用方），
     * 意图保留——要停止后台收敛请调 [`relays_drop`](Self::relays_drop)。
     * `signal`（可选）：abort 只是不再等待，同样不改变意图生命周期。
     * 不传 signal 时 30s 兜底超时保证 Promise 有限时间内 settle。
     */
    relays_until_active(helper_id: string, signal?: AbortSignal | null): Promise<string>;
    /**
     * 解除与某台已配对设备的配对（`peer_id` 为 base58 NodeId）。
     *
     * 走 core 的 `PairingManager::unpair`：**先落盘、再删共享内存表、最后发事件**。
     * 持久化失败即整体报错且内存表不动——绝不出现「这次点了就没了、刷新一下又回来」。
     * 删内存表这一步同时撤销 presence 保活与 `is_paired` 判定（一个 tick 内收敛），
     * 所以本方法之后不需要再补任何本地清理。
     *
     * **单方语义**：只解除本机这一侧，对端仍然认得本机；对端再发起传输会被 `NotPaired`
     * 拒掉，要恢复得重新走一次完整配对。
     *
     * 幂等：本来就没配对的 peer 直接返回成功，不发事件。
     */
    remove_paired_device(peer_id: string): Promise<void>;
    /**
     * 改本机设备名：落盘 → 本机 `OsInfo` → identify 的 `agent_version` → 发
     * `DeviceRenamed`（编排在 core 的 `device_name::rename_device`，三端同一份）。
     *
     * **已连接的对端一个 RTT 内就看到新名字**：新值逐连接下发给每条已建立连接的
     * identify handler，再向这些对端主动 push；未连接的对端下次连上时直接取到新值。
     * 节点不重启、连接不断、传输不中断，页面也不必刷新。
     *
     * 返回归一化后的名字（`undefined` = 已清空，对外回落到
     * [`default_device_name`](crate::device_config::default_device_name)）。入参经
     * `DeviceName::parse` 归一化（trim、剥控制字符与 `;`、截断到 40 个 char），所以返回值
     * 可能与传进来的不同——UI 要展示的是这个返回值，而不是用户的草稿。
     *
     * 与模块级 [`set_device_name`](crate::device_config::set_device_name) 的分工：那个只
     * 落盘，供节点起不来时的设置页用；节点在跑就走这里。两者的分支在 JS 侧
     * （`node-runtime.ts`）——节点句柄只活在那边，Rust 够不到。
     */
    rename_device(name?: string | null): Promise<string | undefined>;
    /**
     * 响应一个入站配对请求（`accept=true` 接受并写配对记录、CAS 消费 invite / `false` 拒绝）。
     */
    respond_pairing_request(pending_id: string, accept: boolean): Promise<void>;
    /**
     * 手动发起断点续传（对某 suspended 会话）。
     *
     * 三种 suspended 都走这一条：用户自己暂停的（`LocalPaused`）、对端暂停的
     * （`RemotePaused`）、以及连接中断 / 对方离线。恢复需要对端在线并应答探测，
     * 失败时错误照常经 `WebError` 透出。
     */
    resume(session_id: string): Promise<void>;
    /**
     * 撤销本机发出的邀请（重新生成覆盖旧串、用户放弃、关闭邀请界面）。
     *
     * 幂等且不报错——不认识的串直接 no-op（详见 `PairingManager::revoke_invite`），
     * 调用方 fire-and-forget 即可（**返回 Promise，不 await 也能用**）。
     *
     * async 化于 invite-persistence：撤销要把那行从 IndexedDB 删掉，否则刷新后它又回来了。
     * 返回**是否已落盘**：`false` 时重启后那条邀请会复活，调用方应当提示用户。
     */
    revoke_invite(invite: string): Promise<boolean>;
    /**
     * 按列表条目的 `id`（capability 哈希 hex）撤销 —— 列表里没有原始邀请串。
     * 返回**是否已落盘**：`false` 时刷新后那条邀请会复活，调用方应当提示用户。
     */
    revoke_invite_by_id(id: string): Promise<boolean>;
    /**
     * 收件箱子串检索：大小写不敏感，覆盖标题 / 来源设备名 / 文件名与相对路径。
     * 空查询返回空列表；结果按 `receivedAt` 倒序并截断到 `limit`
     * （缺省取三端共享的 `INBOX_SEARCH_LIMIT`，前端不必自带魔数）。
     */
    search_inbox(query: string, limit: number | null | undefined, include_archived: boolean): Promise<InboxSearchHit[]>;
    /**
     * 向 `to`（base58 NodeId）发送用户选择的文件：登记文件源 → prepare（checksum + bao
     * outboard）→ 发 Offer。返回 session_id。
     */
    send_files(to: string, files: File[]): Promise<string>;
    /**
     * 建节点：持久化身份（Window=localStorage / Worker=OPFS）+ IndexedDB 恢复已配对设备 → 包 core 组合根 [`start_node`]
     * （Browser [`EndpointProfile`] + Web 端口）→ 完整 [`NetManager`] + 3 协议 Router（含
     * pairing）。**须在主线程 Window 跑**——webrtc-websys dial 碰 window，Worker 里会 panic。
     */
    static spawn(): Promise<WebNode>;
    /**
     * 已持久化的传输会话投影，**按 `startedAt` 倒序**（端口契约，三端一致）。
     *
     * 页面刷新后事件流从零开始，前端据此回补收件箱与传输活动视图（收件箱 = 其中
     * `direction=receive` 且 `terminalReason=completed` 的条目，文件仍在 OPFS，可继续
     * [`download_url`](Self::download_url)）。各面板再按自己的维度（结束时间 / 更新时间）
     * 重排是预期行为——端口保证的是确定性，不是最终展示序。
     *
     * **不含**非终态的发送会话与待决 offer：浏览器刷新后无法在不重新选择文件的前提下
     * 读回 `File`，待决 offer 也已无处应答，故它们本就不落库（见 `store.rs` 模块注释）。
     */
    transfer_history(): Promise<TransferProjection[]>;
    /**
     * 更新已配对设备的信任级别与收件策略。
     *
     * 与桌面 `update_paired_device_policy` 命令**同一条路径**：落盘与「节点在跑时把新值推进
     * 共享内存表」都在 core 的
     * [`set_receive_policy`](swarmdrop_core::paired_devices::set_receive_policy)。
     * 后半句不能省——`swarmdrop_transfer::policy` 裁决入站 offer 时读的是内存表那份，
     * 只落盘会变成「策略已保存、本次运行仍按旧策略放行」。存在性检查也只在那一处。
     *
     * `receive_policy` 传 `undefined` 表示**按新信任级别取默认策略**（`for_trust_level`），
     * 这是「只改信任级别、策略跟着走」那条路径；传具体值则逐字段采用。
     *
     * **返回 `()`，调用方自己重取一次 `paired_devices()`**——与
     * [`remove_paired_device`](Self::remove_paired_device) 同一个约定。两个理由：
     * core 这条路径不发事件（没有对应的 `CoreEvent` 变体，补一条会波及三端全部 event
     * adapter 的穷尽 match，是独立增量）；而 `paired_devices()` 在 Web 侧是同步的内存查询，
     * 重取一次比把 `PairedDeviceInfo`（存储型）也搬进 Web 的类型面便宜——那一面目前只有
     * `Device` 这一个读模型，多一个就多一处要解释「这两个有什么区别」。
     */
    update_paired_device_policy(peer_id: string, trust_level: DeviceTrustLevel, receive_policy?: DeviceReceivePolicy | null): Promise<void>;
}

/**
 * 未设设备名时对外展示的默认值（UA 派生的浏览器名，如 `"Chrome"`）。
 *
 * 导出它而不是让前端再解析一次 UA：两份判定表迟早漂成「设置页 placeholder 写 Safari、
 * 对端看到 Browser」，既难发现又完全没有价值。这里返回的就是 `OsInfo::display_name()`
 * 在 `name` 缺省时回退到的那个 `hostname`。
 */
export function default_device_name(): string;

/**
 * 检索条数上限（[`INBOX_SEARCH_LIMIT`](swarmdrop_transfer::inbox::INBOX_SEARCH_LIMIT) 的只读镜像）。
 *
 * `search_inbox` 的 `limit` 缺省就取这个值、传大了也会被钳回来，前端**不需要**传它。
 * 导出它只为一件事：UI 要说「只显示了最近 N 条」时得知道 N 是几。
 *
 * 换句话说前端仍然不许自带这个数字——那正是 #111 修掉的分叉（此前四个宿主四个值，
 * 而截断掉的永远是最早收到的那批）。wasm-bindgen 不导出常量，所以包成函数。
 * 某信任级别的默认接收策略。
 *
 * **纯派生，不碰节点**，所以是自由函数不是 `WebNode` 方法——它在节点还没起来时也该能用
 * （信任策略对话框可以先开着）。
 *
 * 存在的全部理由是**不让 JS 再抄一份那张表**。桌面与移动此前各抄了一份，两份还长出了不同的
 * 「切级别时保留哪些字段」规则，而内核那一份一个都不保留——同一个产品动作三种行为。
 * 现在规则只在 [`DeviceReceivePolicy::for_trust_level`] 一处，三端各经自己的 binding 调它。
 *
 * `previous` 传该设备**当前**的策略，用户显式设过的保存位置与代收授权会被带过去
 * （`blocked` 除外）。新配对或不关心时传 `undefined`。
 */
export function default_receive_policy(trust_level: DeviceTrustLevel, previous?: DeviceReceivePolicy | null): DeviceReceivePolicy;

/**
 * 当前持久化的设备名；未设过（或读失败 / 内容非法）返回 `undefined`。
 */
export function get_device_name(): Promise<string | undefined>;

export function inbox_search_limit(): number;

/**
 * 设置设备名；`null` / 空串 / 归一化后为空一律视为清空，回落到
 * [`default_device_name`]。入参经 `DeviceName::parse` 归一化（trim、剥控制字符与 `;`、
 * 截断到 40 个 char），UI 侧的 `maxLength` 只是提前拦一道。
 */
export function set_device_name(name?: string | null): Promise<void>;

/**
 * wasm 模块加载即初始化 panic hook + tracing（浏览器 console）。
 */
export function start(): void;

export type InitInput = RequestInfo | URL | Response | BufferSource | WebAssembly.Module;

export interface InitOutput {
    readonly memory: WebAssembly.Memory;
    readonly __wbg_webnode_free: (a: number, b: number) => void;
    readonly default_receive_policy: (a: any, b: number) => [number, number, number];
    readonly inbox_search_limit: () => number;
    readonly webnode_accept_offer: (a: number, b: number, c: number) => any;
    readonly webnode_archive_inbox_item: (a: number, b: number, c: number, d: number) => any;
    readonly webnode_cancel_receive: (a: number, b: number, c: number) => any;
    readonly webnode_cancel_send: (a: number, b: number, c: number) => any;
    readonly webnode_clear_transfer_history: (a: number) => any;
    readonly webnode_close: (a: number) => any;
    readonly webnode_connect: (a: number, b: number, c: number, d: number) => any;
    readonly webnode_connect_invite: (a: number, b: number, c: number) => any;
    readonly webnode_decode_invite_preview: (a: number, b: number, c: number) => [number, number, number];
    readonly webnode_delete_inbox_item: (a: number, b: number, c: number, d: number) => any;
    readonly webnode_delete_transfer_session: (a: number, b: number, c: number) => any;
    readonly webnode_download_url: (a: number, b: number, c: number) => any;
    readonly webnode_events: (a: number) => [number, number, number];
    readonly webnode_generate_invite: (a: number, b: number) => any;
    readonly webnode_inbox_item: (a: number, b: number, c: number) => any;
    readonly webnode_inbox_item_by_session: (a: number, b: number, c: number) => any;
    readonly webnode_inbox_items: (a: number, b: number) => any;
    readonly webnode_invite_qr_svg: (a: number, b: number, c: number) => [number, number, number, number];
    readonly webnode_list_invites: (a: number) => [number, number, number];
    readonly webnode_mark_inbox_item_opened: (a: number, b: number, c: number) => any;
    readonly webnode_node_id: (a: number) => [number, number];
    readonly webnode_paired_devices: (a: number) => [number, number, number];
    readonly webnode_pause_receive: (a: number, b: number, c: number) => any;
    readonly webnode_pause_send: (a: number, b: number, c: number) => any;
    readonly webnode_pending_offers: (a: number) => [number, number, number];
    readonly webnode_pending_pairing_requests: (a: number) => [number, number, number];
    readonly webnode_reject_offer: (a: number, b: number, c: number) => any;
    readonly webnode_relays_changed: (a: number) => any;
    readonly webnode_relays_drop: (a: number, b: number, c: number) => any;
    readonly webnode_relays_ensure: (a: number, b: number, c: number) => [number, number, number, number];
    readonly webnode_relays_state: (a: number) => [number, number, number];
    readonly webnode_relays_until_active: (a: number, b: number, c: number, d: number) => any;
    readonly webnode_remove_paired_device: (a: number, b: number, c: number) => any;
    readonly webnode_rename_device: (a: number, b: number, c: number) => any;
    readonly webnode_respond_pairing_request: (a: number, b: number, c: number, d: number) => any;
    readonly webnode_resume: (a: number, b: number, c: number) => any;
    readonly webnode_revoke_invite: (a: number, b: number, c: number) => any;
    readonly webnode_revoke_invite_by_id: (a: number, b: number, c: number) => any;
    readonly webnode_search_inbox: (a: number, b: number, c: number, d: number, e: number) => any;
    readonly webnode_send_files: (a: number, b: number, c: number, d: number, e: number) => any;
    readonly webnode_spawn: () => any;
    readonly webnode_transfer_history: (a: number) => any;
    readonly webnode_update_paired_device_policy: (a: number, b: number, c: number, d: any, e: number) => any;
    readonly default_device_name: () => [number, number];
    readonly get_device_name: () => any;
    readonly set_device_name: (a: number, b: number) => any;
    readonly start: () => void;
    readonly __wbg_intounderlyingbytesource_free: (a: number, b: number) => void;
    readonly intounderlyingbytesource_autoAllocateChunkSize: (a: number) => number;
    readonly intounderlyingbytesource_cancel: (a: number) => void;
    readonly intounderlyingbytesource_pull: (a: number, b: any) => any;
    readonly intounderlyingbytesource_start: (a: number, b: any) => void;
    readonly intounderlyingbytesource_type: (a: number) => number;
    readonly __wbg_intounderlyingsource_free: (a: number, b: number) => void;
    readonly intounderlyingsource_cancel: (a: number) => void;
    readonly intounderlyingsource_pull: (a: number, b: any) => any;
    readonly __wbg_intounderlyingsink_free: (a: number, b: number) => void;
    readonly intounderlyingsink_abort: (a: number, b: any) => any;
    readonly intounderlyingsink_close: (a: number) => any;
    readonly intounderlyingsink_write: (a: number, b: any) => any;
    readonly wasm_bindgen_1f3b1eaef9b9ff9e___closure__destroy___dyn_core_7d5f0a2ba6a62c33___ops__function__FnMut__web_sys_9ac2f0c40ea89be0___features__gen_MessageEvent__MessageEvent____Output_______: (a: number, b: number) => void;
    readonly wasm_bindgen_1f3b1eaef9b9ff9e___closure__destroy___dyn_core_7d5f0a2ba6a62c33___ops__function__FnMut_____Output_______: (a: number, b: number) => void;
    readonly wasm_bindgen_1f3b1eaef9b9ff9e___closure__destroy___dyn_core_7d5f0a2ba6a62c33___ops__function__FnMut__wasm_bindgen_1f3b1eaef9b9ff9e___JsValue____Output_______: (a: number, b: number) => void;
    readonly wasm_bindgen_1f3b1eaef9b9ff9e___closure__destroy___dyn_core_7d5f0a2ba6a62c33___ops__function__FnMut_____Output________1_: (a: number, b: number) => void;
    readonly wasm_bindgen_1f3b1eaef9b9ff9e___closure__destroy___dyn_core_7d5f0a2ba6a62c33___ops__function__FnMut__web_sys_9ac2f0c40ea89be0___features__gen_CloseEvent__CloseEvent____Output_______: (a: number, b: number) => void;
    readonly wasm_bindgen_1f3b1eaef9b9ff9e___convert__closures_____invoke___wasm_bindgen_1f3b1eaef9b9ff9e___JsValue__wasm_bindgen_1f3b1eaef9b9ff9e___JsValue_____: (a: number, b: number, c: any, d: any) => void;
    readonly wasm_bindgen_1f3b1eaef9b9ff9e___convert__closures_____invoke___web_sys_9ac2f0c40ea89be0___features__gen_MessageEvent__MessageEvent_____: (a: number, b: number, c: any) => void;
    readonly wasm_bindgen_1f3b1eaef9b9ff9e___convert__closures_____invoke___wasm_bindgen_1f3b1eaef9b9ff9e___JsValue_____: (a: number, b: number, c: any) => void;
    readonly wasm_bindgen_1f3b1eaef9b9ff9e___convert__closures_____invoke___web_sys_9ac2f0c40ea89be0___features__gen_CloseEvent__CloseEvent_____: (a: number, b: number, c: any) => void;
    readonly wasm_bindgen_1f3b1eaef9b9ff9e___convert__closures_____invoke______: (a: number, b: number) => void;
    readonly wasm_bindgen_1f3b1eaef9b9ff9e___convert__closures_____invoke_______1_: (a: number, b: number) => void;
    readonly __wbindgen_malloc: (a: number, b: number) => number;
    readonly __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
    readonly __wbindgen_exn_store: (a: number) => void;
    readonly __externref_table_alloc: () => number;
    readonly __wbindgen_externrefs: WebAssembly.Table;
    readonly __externref_drop_slice: (a: number, b: number) => void;
    readonly __wbindgen_free: (a: number, b: number, c: number) => void;
    readonly __externref_table_dealloc: (a: number) => void;
    readonly __wbindgen_start: () => void;
}

export type SyncInitInput = BufferSource | WebAssembly.Module;

/**
 * Instantiates the given `module`, which can either be bytes or
 * a precompiled `WebAssembly.Module`.
 *
 * @param {{ module: SyncInitInput }} module - Passing `SyncInitInput` directly is deprecated.
 *
 * @returns {InitOutput}
 */
export function initSync(module: { module: SyncInitInput } | SyncInitInput): InitOutput;

/**
 * If `module_or_path` is {RequestInfo} or {URL}, makes a request and
 * for everything else, calls `WebAssembly.instantiate` directly.
 *
 * @param {{ module_or_path: InitInput | Promise<InitInput> }} module_or_path - Passing `InitInput` directly is deprecated.
 *
 * @returns {Promise<InitOutput>}
 */
export default function __wbg_init (module_or_path?: { module_or_path: InitInput | Promise<InitInput> } | InitInput | Promise<InitInput>): Promise<InitOutput>;
