// 由 `cargo test -p swarmdrop-web --features specta --test specta_export` 生成，勿手改。
// 形状与运行期 serde_wasm_bindgen 序列化一致（u64 等已映射为 number）。

// This file has been generated by Specta. Do not edit this file manually.
/**  `connect()` 的结构化返回。 */
export type ConnectionJson = {
	path: PathKindJson,
	addr: string,
};

/**  连接类型。 */
export type ConnectionType = "lan" | "dcutr" | "relay";

/**
 *  接收端保存位置（host-agnostic）。
 * 
 *  core 内部统一用此类型，避免把 `entity::SaveLocation`（SeaORM 实体细节）
 *  暴露到公共 API 上。DB 边界用 [`From`] 与 `entity::SaveLocation` 双向转换。
 */
export type CoreSaveLocation = 
/**  文件系统绝对路径（桌面）或 `Paths.document` 子路径（移动端）。 */
{ type: "path"; path: string };

/**  统一的设备输出类型。 */
export type Device = {
	peerId: string,
	status: DeviceStatus,
	connection: ConnectionType | null,
	latency: number | null,
	isPaired: boolean,
	trustLevel: DeviceTrustLevel | null,
	receivePolicy: DeviceReceivePolicy | null,
	trustConfirmed: boolean | null,
} & OsInfo;

/**
 *  可信设备接收策略。
 * 
 *  字段保持 host-neutral：保存位置使用字符串表达的 host 路径，桌面端解释为绝对路径，
 *  移动端后续可解释为应用文档目录下的子路径。
 */
export type DeviceReceivePolicy = {
	autoAccept: boolean,
	requireConfirmation: boolean,
	maxTransferBytes?: number | null,
	allowDirectories: boolean,
	allowRelayAutoAccept: boolean,
	saveBehavior?: ReceiveSaveBehavior,
	defaultSaveLocation?: string | null,
	allowMcpSendToDevice: boolean,
	/**
	 *  允许 MCP/AI 代该来源设备处置入站 offer（接受或拒绝）。
	 * 
	 *  默认 false。与发送侧 `allow_mcp_send_to_device` **刻意不对称**：代收会往磁盘写入、
	 *  风险更高，故即便对 Owned 设备也需用户逐设备显式开启（发送侧则随信任级别自动派生）。
	 *  只能由用户在 app 的设备信任策略中开启，agent 无任何写权限——防止自我提权、静默代收。
	 */
	allowMcpAcceptFromDevice?: boolean,
	expiresAt?: number | null,
};

/**  设备状态。 */
export type DeviceStatus = "online" | "offline";

/**  已配对设备信任等级。 */
export type DeviceTrustLevel = "owned" | "collaborator" | "temporary" | "blocked";

/**  传输文件元信息。 */
export type FileInfo = {
	fileId: number,
	name: string,
	relativePath: string,
	size: number,
	checksum: string,
};

export type FileProgressInfo = {
	fileId: number,
	name: string,
	size: number,
	transferred: number,
	status: FileTransferStatus,
};

export type FileTransferStatus = "pending" | "transferring" | "completed";

/**  收件箱内容类型。 */
export type InboxContentKind = "files" | "text" | "clipboard" | "bundle";

/**  搜索命中条目下的文件标识（供下钻定位）。 */
export type InboxHitFile = {
	name: string,
	relativePath: string,
};

/**  收件箱详情 DTO。 */
export type InboxItemDetail = {
	files: InboxItemFileEntry[],
	transfer: TransferProjection | null,
} & InboxItemSummary;

/**  收件箱文件 DTO。 */
export type InboxItemFileEntry = {
	id: number,
	transferFileId: number | null,
	/**  条目根之下的相对路径。**Web 宿主删文件用这个**——OPFS 的键就是它。 */
	relativePath: string,
	name: string,
	size: number,
	checksum: string,
	/**
	 *  宿主可直接操作的完整路径。**桌面 / 移动删文件用这个**（那边是真实文件系统路径）；
	 *  **Web 上它是带 `opfs:/` 前缀的展示值，喂给 `remove_path` 会去找一个叫 `opfs:` 的目录**。
	 * 
	 *  两个路径字段并存且「该用哪个」按端不同，是这个 DTO 最容易踩空的地方——所以写在这里，
	 *  而不是让每个宿主自己从别处推断。
	 */
	localPath: string,
	missing: boolean,
};

/**  收件箱列表条目 DTO。 */
export type InboxItemSummary = {
	id: string,
	transferSessionId: string | null,
	sourcePeerId: string,
	sourceName: string,
	sourceKind: InboxSourceKind,
	contentKind: InboxContentKind,
	title: string,
	itemCount: number,
	totalSize: number,
	rootPath: string | null,
	contentHash: string | null,
	receivedAt: number,
	lastOpenedAt: number | null,
	archivedAt: number | null,
	deletedAt: number | null,
	missing: boolean,
};

/**  收件箱搜索命中（item 粒度）。 */
export type InboxSearchHit = {
	id: string,
	title: string,
	sourceName: string,
	itemCount: number,
	rootPath: string | null,
	receivedAt: number,
	/**
	 *  命中所在文本的片段（在 Rust 端按子串位置切窗口生成）。
	 * 
	 *  `None` = **不该渲染片段行**：命中的是标题或来源名（条目行上已经显示着），
	 *  或一个候选都没命中。判据在 [`inbox_snippet`]，三端不要各判一遍。
	 */
	snippet: string | null,
	/**  该条目下的文件（文件名 + 相对路径），供 get_inbox_file 下钻。 */
	files: InboxHitFile[],
};

/**  收件箱来源类型。 */
export type InboxSourceKind = "paired_device" | "share_code" | "mcp" | "unknown";

/**
 *  「已发出的邀请」列表条目（openspec: invite-persistence）。
 * 
 *  **没有邀请串本身**：capability 明文不落盘也不出注册表，刷新后拼不回原始链接。
 *  UI 只显示元数据 + 提供撤销；想再分享就生成一条新的。
 * 
 *  时间戳用字符串承载 Unix 秒，与 `pendingId` 同一个理由（避免 u64 → BigInt 的取回麻烦）。
 */
export type InviteListItemJson = {
	/**  `sha256(capability)` 的 hex —— 撤销时回传，UI 当不透明 ID 用。 */
	id: string,
	createdAt: string,
	expiresAt: string,
	/**  已被对方消费（仍显示到过期，让用户知道它被用过）。 */
	consumed: boolean,
};

/**  挂起 offer 的 JS 投影（`pending_offers()` 返回 `OfferJson[]`）。 */
export type OfferJson = {
	sessionId: string,
	peerId: string,
	peerName: string,
	totalSize: number,
	files: FileInfo[],
};

/**  Offer 被拒绝的原因。 */
export type OfferRejectReason = { type: "not_paired" } | { type: "user_declined" } | { type: "policy_rejected" } | 
/**  接收方处于全局「暂停接收」状态，婉拒新 offer。 */
{ type: "receiving_paused" };

/**
 *  设备操作系统信息。
 * 
 *  `hostname` 是系统主机名（运行时取，桌面端通常是机器名，移动端通常拿不到）；
 *  `name` 是用户在 onboarding / 设置里起的名字（持久化），由 core 的组合根从
 *  [`DeviceConfig`](crate::ports::DeviceConfig) 端口填充，UI 显示按
 *  `name.as_deref().unwrap_or(&hostname)` 回退。
 */
export type OsInfo = {
	/**  用户起的设备名；缺省时回退到 `hostname`。 */
	name?: string | null,
	hostname: string,
	os: string,
	platform: string,
	arch: string,
	capabilities?: string[],
};

/**
 *  邀请串解码后的展示投影（配对确认卡用）。
 * 
 *  **不含 capability**：那是 128bit bearer 凭据，明文绝不出 wasm 边界——确认卡只需要
 *  「这是谁、还有效多久、是不是仅局域网」，多给一个字段就多一条泄漏路径。
 * 
 *  **TTL 由调用方按 `expiresAt` 判**，这里不放 `expired: bool`：确认卡会在屏幕上停留几十秒，
 *  而布尔在序列化那一刻就开始变旧。权威判定本来也在发起端的 `InviteRegistry`，
 *  解码侧的预检只为 UX（见 `PairInvite::decode` 的文档）。
 * 
 *  `expiresAt` 用字符串承载 Unix 秒，与 [`InviteListItemJson`] 同一个理由。
 */
export type PairInvitePreviewJson = {
	/**
	 *  发起方 NodeId（base58）。取自签名覆盖范围内的 `inviter_id`，伪造不了——
	 *  自我过滤 / 已配对过滤都该以它为判据。
	 */
	peerId: string,
	displayName: string,
	displayPlatform: string,
	expiresAt: string,
	/**  LocalOnly 策略（受邀方只用私网地址、禁公网 fallback）。 */
	localOnly: boolean,
};

/**  连接路径类别（[`swarmdrop_net_base::PathKind`] 的 JS 投影，TS 侧是字符串联合）。 */
export type PathKindJson = "local" | "direct" | "relayed";

/**
 *  挂起入站配对请求的 JS 投影（`pending_pairing_requests()` 返回）。
 * 
 *  browser-as-inviter 用：桌面消费浏览器生成的 invite 后，浏览器（邀请方）本机需弹确认。
 *  `pendingId` 以字符串承载核心的 u64 pending id（避免 JS number 精度 + serde_wasm_bindgen
 *  对 u64 产 BigInt 的取回麻烦），`respond_pairing_request` 再 parse 回 u64。
 */
export type PendingPairingJson = {
	pendingId: string,
	peerId: string,
	deviceName: string,
};

/**  `prepare_send` 的 hash 进度事件 */
export type PrepareProgressEvent = {
	/**  用于区分并发 prepare（多用户在不同会话同时调用） */
	preparedId: string,
	/**  当前正在 hash 的文件名 */
	currentFile: string,
	/**  已完成 hash 的文件数 */
	completedFiles: number,
	/**  总文件数 */
	totalFiles: number,
	/**  累积已 hash 的字节数（所有文件） */
	bytesHashed: number,
	/**  总字节数（所有文件） */
	totalBytes: number,
};

/**  自动接收时的保存行为。 */
export type ReceiveSaveBehavior = 
/**  使用策略里配置的默认保存位置，接收完成后进入收件箱。 */
"inbox_and_default_save_location";

/**  单个 relay 意图的状态快照（`relays_state()` 元素 / `relays_changed()` 流的产出单元）。 */
export type RelayInfoJson = {
	/**  relay 节点身份（base58 NodeId）。 */
	id: string,
	state: RelayStateKind,
	/**  `active` 时为本机经该 relay 的完整可达地址（内核拼装下发），其余为 null。 */
	circuitAddr: string | null,
	/**
	 *  `failed` 时的末次错误描述，其余为 null。重试轮数不下发——那是
	 *  策略层内账（supervisor 唯一持有），诊断走日志。
	 */
	lastError: string | null,
};

/**  relay reservation 状态类别（[`swarmdrop_net::RelayState`] 的 JS 投影，TS 侧字符串联合）。 */
export type RelayStateKind = "connecting" | "active" | "failed";

export type RuntimeTransferDirection = "send" | "receive" | "unknown";

/**  suspended 原因（phase=Suspended 时有值）。 */
export type SuspendedReason = "local_paused" | "remote_paused" | "interrupted" | "peer_offline" | "app_restarted";

/**  terminal 原因（phase=Terminal 时有值）。 */
export type TerminalReason = "completed" | "cancelled" | "rejected" | "fatal_error";

/**  对方接受 Offer 的事件 payload */
export type TransferAcceptedEvent = {
	sessionId: string,
};

export type TransferCompleteEvent = {
	sessionId: string,
	direction: RuntimeTransferDirection,
	totalBytes: number,
	elapsedMs: number,
	saveLocation: CoreSaveLocation | null,
};

export type TransferDbErrorEvent = {
	sessionId: string,
	message: string,
};

/**  传输方向 */
export type TransferDirection = "send" | "receive";

export type TransferFailedEvent = {
	sessionId: string,
	direction: RuntimeTransferDirection,
	error: string,
};

export type TransferOfferEvent = {
	sessionId: string,
	peerId: string,
	deviceName: string,
	files: TransferOfferFileEvent[],
	totalSize: number,
	/**  发起来源（人工 / MCP 代理），供接收端 UI 标识。 */
	origin: TransferOrigin,
	policyAction: string | null,
	policyReason: string | null,
};

export type TransferOfferFileEvent = {
	fileId: number,
	name: string,
	relativePath: string,
	size: number,
	isDirectory: boolean,
};

/**
 *  传输发起来源：人在应用内发起，或 AI 代理经 MCP 发起。
 * 
 *  由发送方自报、承载于 Offer，供接收端展示与 inbox 来源派生——是信息性/UX 信号，
 *  不作接收端安全边界（真正的控制是发送端 `allow_mcp_send_to_device` 门控）。
 */
export type TransferOrigin = 
/**  用户在应用内手动发起。 */
{ type: "human" } | 
/**  AI 代理经 MCP 发起；`client` 为 MCP 客户端名（如 claude-desktop），不可得时为 None。 */
{ type: "mcp"; client: string | null };

export type TransferPausedEvent = {
	sessionId: string,
	direction: RuntimeTransferDirection,
};

/**
 *  传输生命周期大状态（phase）。
 *  替代旧的扁平 [`SessionStatus`]（过渡期并存）：phase 表达大状态，
 *  具体原因由 [`SuspendedReason`] / [`TerminalReason`] 表达。
 */
export type TransferPhase = "offered" | "waiting_accept" | "active" | "suspended" | "terminal";

export type TransferProgressEvent = {
	sessionId: string,
	direction: RuntimeTransferDirection,
	totalFiles: number,
	completedFiles: number,
	totalBytes: number,
	transferredBytes: number,
	speed: number | null,
	eta: number | null,
	files: FileProgressInfo[],
};

/**  传输投影 DTO —— 前端唯一状态源（逐步替代旧的分散事件 + 扁平 `SessionStatus`）。 */
export type TransferProjection = {
	sessionId: string,
	direction: TransferDirection,
	peerId: string,
	peerName: string,
	phase: TransferPhase,
	suspendedReason: SuspendedReason | null,
	terminalReason: TerminalReason | null,
	recoverable: boolean,
	epoch: number,
	totalSize: number,
	transferredBytes: number,
	startedAt: number,
	updatedAt: number,
	finishedAt: number | null,
	errorMessage: string | null,
	policyAction: string | null,
	policyReason: string | null,
	savePath: CoreSaveLocation | null,
	/**
	 *  「打开文件夹」应定位的真实容器目录 URI(收到内容实际所在的文件夹),已在 core 解析:
	 *  各文件 `local_dir` 全部同一目录 → 该目录;否则回退存储根 `save_path`。前端直读,
	 *  不再自行兜底(已完成接收必为 `Some`)。
	 */
	contentRoot: string | null,
	files: TransferProjectionFile[],
};

export type TransferProjectionFile = {
	fileId: number,
	name: string,
	relativePath: string,
	size: number,
	transferredBytes: number,
};

/**  对方拒绝 Offer 的事件 payload */
export type TransferRejectedEvent = {
	sessionId: string,
	reason: OfferRejectReason | null,
};

export type TransferResumedEvent = {
	sessionId: string,
	direction: RuntimeTransferDirection,
	peerId: string,
	peerName: string,
	files: TransferResumedFileInfo[],
	totalSize: number,
};

export type TransferResumedFileInfo = {
	fileId: number,
	name: string,
	relativePath: string,
	size: number,
	isDirectory: boolean,
};

/**
 *  Web 壳对外错误。`kind` 供 JS 分支，`message` 供展示。
 * 
 *  wasm-bindgen 方法 reject 的错误值就是本类型的序列化对象（`{ kind, message }`）——
 *  **不拍成字符串**（字符串丢了机器可判别的 kind）。JsValue 转换在 `error.rs`。
 */
export type WebError = 
/**  身份 / 密钥错误。 */
{ kind: "identity"; message: string } | 
/**  网络 / 连接 / DHT 错误。 */
{ kind: "network"; message: string } | 
/**  传输错误。 */
{ kind: "transfer"; message: string } | 
/**  入参非法（地址格式、缺 `/p2p/` 等）。 */
{ kind: "invalidInput"; message: string } | 
/**
 *  调用被 `AbortSignal` 取消。**abort ≠ 撤回拨号**：Promise 立即 reject 且
 *  无常驻意图残留，但在途拨号会继续到自然失败（libp2p 无逐次拨号取消面）。
 */
{ kind: "aborted"; message: string } | 
/**  分享码不存在 / 已过期。 */
{ kind: "notFound"; message: string } | 
/**  存储（OPFS / localStorage）错误。 */
{ kind: "storage"; message: string };

/**
 *  `TransferEvent` 的可序列化镜像（1:1 变体，字段与 payload 同名）。
 * 
 *  `TransferEvent` 本身未 derive `Serialize`（transfer 不改）——与桌面把它映射进
 *  `CoreEvent` 的适配范式一致。`events()` 的 ReadableStream 逐条产出本类型的序列化对象。
 */
export type WebTransferEvent = { type: "transferOfferReceived"; offer: TransferOfferEvent } | { type: "transferProgress"; event: TransferProgressEvent } | { type: "transferAccepted"; event: TransferAcceptedEvent } | { type: "transferRejected"; event: TransferRejectedEvent } | { type: "transferCompleted"; event: TransferCompleteEvent } | { type: "transferFailed"; event: TransferFailedEvent } | { type: "transferPaused"; event: TransferPausedEvent } | { type: "transferResumed"; event: TransferResumedEvent } | { type: "transferDbError"; event: TransferDbErrorEvent } | { type: "transferProjection"; projection: TransferProjection } | { type: "prepareProgress"; event: PrepareProgressEvent };
