// 由 `cargo test -p swarmdrop-web --features specta --test specta_export` 生成，勿手改。
// 形状与运行期 serde_wasm_bindgen 序列化一致（u64 等已映射为 number）。

// This file has been generated by Specta. Do not edit this file manually.
export type BootstrapCandidateSource = 
/**  当前 host 注入的静态引导/中继配置（含各端默认值和用户追加地址）。 */
"hostConfigured" | "mdnsLanHelper" | 
/**  运行时经 identify 学到的基础设施节点（如经局域网协助节点认识的公网中继） */
"learned";

export type CandidateRoles = {
	kadServer: boolean,
	relayServer: boolean,
};

export type CandidateScope = "public" | "lan";

/**
 *  链路详情：当前连接的可核对事实。
 * 
 *  与 [`ConnectionType`] 的分工——那个是给所有人看的一句话结论（局域网 / 打洞 /
 *  中继），这个是「凭什么这么说」：走的哪条地址、哪种传输、经不经中继、经的是谁。
 *  三端 UI 把它放在默认折叠的区块里，普通用户看不到，排障时一眼能拿到全部证据。
 */
export type ConnectionDetails = {
	/**
	 *  承载字节的传输协议。
	 * 
	 *  `None` 是真实存在的情况，不是缺陷：入站中继连接的 `send_back_addr` 只有
	 *  `/p2p/<src>` 一段，地址里没有任何传输信息。呈现层照实显示「未知」。
	 */
	transport: TransportKind | null,
	/**  当前最优连接的远端 multiaddr，原样给出——便于直接粘进 issue 或与日志比对。 */
	remoteAddr: string,
	/**
	 *  中转身份：经中继时是那台 relay 的 PeerId，直连为 `None`。
	 * 
	 *  「经中继」三个字对排障几乎没用，得说清楚经的是哪一台——自建 relay 还是
	 *  局域网里的 LanHelper，处理方式完全不同。
	 */
	relay: string | null,
};

/**  `connect()` 的结构化返回。 */
export type ConnectionJson = {
	path: PathKindJson,
	addr: string,
};

/**  连接类型。 */
export type ConnectionType = "lan" | "dcutr" | "relay";

/**
 *  接收端保存位置（host-agnostic）。
 * 
 *  core 内部统一用此类型，避免把 `entity::SaveLocation`（SeaORM 实体细节）
 *  暴露到公共 API 上。DB 边界用 [`From`] 与 `entity::SaveLocation` 双向转换。
 */
export type CoreSaveLocation = 
/**
 *  宿主自己解释的保存位置串，**core 视其为不透明**。
 * 
 *  桌面是文件系统绝对路径；移动端是 expo-file-system 的 URI，**可能是 `file://`，
 *  也可能是 Android SAF 的 `content://` tree**（用户在设置里选了系统公共目录时）；
 *  Web 是 OPFS 的相对路径。名字叫 `Path` 是历史，别据此假设它一定是文件系统路径——
 *  移动端的发布路径正是靠嗅探 `content://` 前缀来分派的。
 */
{ type: "path"; path: string };

/**  统一的设备输出类型。 */
export type Device = {
	peerId: string,
	status: DeviceStatus,
	connection: ConnectionType | null,
	/**
	 *  链路详情。仅在线且内核报告过连接地址时有值——离线设备、以及只靠 mDNS
	 *  地址推断出 `connection` 的宽限期内，这里是 `None`（没连接就没有链路可谈）。
	 */
	connectionDetails: ConnectionDetails | null,
	/**
	 *  内核尝试过局域网直连升级但失败了。
	 * 
	 *  与 `connection == Relay` 一起看才有意义：那时它把「对端本来就在外网」与
	 *  「对端就在同一网段却连不上」分开。后者呈现层应给出可行动的提示——查防火墙，
	 *  或（浏览器上）允许本地网络访问。
	 */
	lanUpgradeFailed: boolean,
	latency: number | null,
	isPaired: boolean,
	trustLevel: DeviceTrustLevel | null,
	receivePolicy: DeviceReceivePolicy | null,
	trustConfirmed: boolean | null,
} & OsInfo;

/**
 *  可信设备接收策略。
 * 
 *  字段保持 host-neutral：保存位置使用字符串表达的 host 路径，桌面端解释为绝对路径，
 *  移动端后续可解释为应用文档目录下的子路径。
 */
export type DeviceReceivePolicy = {
	autoAccept: boolean,
	requireConfirmation: boolean,
	maxTransferBytes?: number | null,
	allowDirectories: boolean,
	allowRelayAutoAccept: boolean,
	saveBehavior?: ReceiveSaveBehavior,
	defaultSaveLocation?: string | null,
	allowMcpSendToDevice: boolean,
	/**
	 *  允许 MCP/AI 代该来源设备处置入站 offer（接受或拒绝）。
	 * 
	 *  默认 false。与发送侧 `allow_mcp_send_to_device` **刻意不对称**：代收会往磁盘写入、
	 *  风险更高，故即便对 Owned 设备也需用户逐设备显式开启（发送侧则随信任级别自动派生）。
	 *  只能由用户在 app 的设备信任策略中开启，agent 无任何写权限——防止自我提权、静默代收。
	 */
	allowMcpAcceptFromDevice?: boolean,
	expiresAt?: number | null,
};

/**  设备状态。 */
export type DeviceStatus = "online" | "offline";

/**  已配对设备信任等级。 */
export type DeviceTrustLevel = "owned" | "collaborator" | "temporary" | "blocked";

/**
 *  会话失败原因。持久化进 `transfer_sessions.error_message` 列（类型不变，存 JSON）。
 * 
 *  变体数量刻意贴着**实际构造点**（三处 `ActorReport::FatalError` + 一处过期回收），
 *  不预留「将来可能用到」的码 —— `failure-semantics-contract` 的 D3 已经吃过一次亏：
 *  造出来到不了 UI 的判别码只是三端文案表里的死条目。
 */
export type FailureCode = 
/**
 *  超过保留期仍未恢复，被启动清理回收。
 * 
 *  `retention_days` 进文案（「超过 N 天」），所以它是参数而不是常量 ——
 *  保留期是配置项，两端可能不同。
 */
{ code: "sessionExpired"; retentionDays: number } | 
/**
 *  对端拒绝了续传请求。
 * 
 *  **直接内嵌 [`ResumeRejectReason`]，不再压成字符串。** 这条通道此前经
 *  `resume_reject_message()` 把一个六变体的枚举摊平成六句中文 —— 判别信息在
 *  wire 上本来就是结构化的，落库时降级成自由文本，到了 UI 又没法还原。
 */
{ code: "resumeRejected"; reason: ResumeRejectReason } | 
/**
 *  发送方的 Offer 没能送达对端（发送失败或收到非预期响应）。
 * 
 *  两个调用点的技术细节（IO 错误、响应类型）对用户是同一件事：对方没收到你的请求。
 *  细节进 `warn!`。
 */
{ code: "offerFailed" } | 
/**
 *  对端不认识本机的数据面协议名——**版本不兼容**。
 * 
 *  这是唯一一个「重试一万次也不会好」的网络类失败，所以它必须是 fatal 而不是
 *  Interrupted。此前它被压成 `AppError::Transfer(String)` 走可恢复中断，于是续传
 *  机器拿同一个协议名一次次重试，用户看到的是「传输老是断」——而真相是有一端需要
 *  升级。协议名换代（`transfer-data/3` → `/4`）时旧端全都撞这条路。
 * 
 *  把不兼容前移到协商阶段是 bump 协议名的全部价值；那份信息在这里才算真正到达用户。
 */
{ code: "peerProtocolUnsupported" } | 
/**
 *  **存量数据**：本判别码引入之前写入的自由文本。
 * 
 *  不写回填迁移 —— 失败原因是过程账本上的一句解释，重算不出来（原始错误早没了），
 *  猜也猜不准。存量行原样展示旧串即可，新行一律是判别码；随着历史滚动它自然消失。
 *  这与收件箱标题的处置不同（那边**回填**了），区别在于标题可以从文件列表重算，
 *  失败原因不能。
 */
{ code: "legacy"; message: string };

/**  传输文件元信息。 */
export type FileInfo = {
	fileId: number,
	name: string,
	/**
	 *  对端声明的相对路径，接收方据此在保存目录下建文件。
	 * 
	 *  **这是对端完全可控的字符串，落盘前必须过 [`is_safe_relative_path`]。**
	 */
	relativePath: string,
	size: number,
	checksum: string,
};

export type FileProgressInfo = {
	fileId: number,
	name: string,
	size: number,
	transferred: number,
	status: FileTransferStatus,
};

/**
 *  单个文件的发布事件。
 * 
 *  **是文件级而非会话级**：发布是「收齐即发布」，一个会话里会发生多次、散布在整条传输
 *  过程中，不是末尾一次。挂到会话级的进度事件上就表达不了「现在正在保存哪一个」。
 */
export type FilePublishEvent = {
	sessionId: string,
	fileId: number,
	/**  文件名（展示用）。 */
	name: string,
	/**
	 *  相对路径。移动端 JS 侧靠它把自己的拷贝字节数认领到正确的条目上——
	 *  它拿到的元数据里没有 session_id / file_id。
	 */
	relativePath: string,
	totalBytes: number,
	phase: FilePublishPhase,
};

/**
 *  单个文件的发布阶段（暂存 → 用户可见位置）。
 * 
 *  只有两档且都是 unit 变体：三端 codegen 都稳（specta → 字符串联合、uniffi → 无字段
 *  enum），各端用查表渲染，将来加档会在查表处编译期报缺项。
 * 
 *  **拷贝中的字节进度不在这里**：唯一会慢的发布路径是 Android 的 SAF 全量拷贝，那个循环
 *  住在移动端 JS 侧的宿主适配器里，由它直接上报自己的进度。为它给三端共用的
 *  [`FileAccess`](crate::host::FileAccess) 端口加回调参数是反向的——其余平台的发布是
 *  常数时间的重命名，根本没有循环可上报。
 */
export type FilePublishPhase = "started" | "finished";

export type FileTransferStatus = "pending" | "transferring" | "completed";

/**  收件箱内容类型。 */
export type InboxContentKind = "files" | "text" | "clipboard" | "bundle";

/**  搜索命中条目下的文件标识（供下钻定位）。 */
export type InboxHitFile = {
	name: string,
	relativePath: string,
};

/**  收件箱详情 DTO。 */
export type InboxItemDetail = {
	files: InboxItemFileEntry[],
	transfer: TransferProjection | null,
} & InboxItemSummary;

/**  收件箱文件 DTO。 */
export type InboxItemFileEntry = {
	id: number,
	transferFileId: number | null,
	/**  条目根之下的相对路径。**Web 宿主删文件用这个**——OPFS 的键就是它。 */
	relativePath: string,
	name: string,
	size: number,
	checksum: string,
	/**
	 *  宿主可直接操作的完整路径。**桌面 / 移动删文件用这个**（那边是真实文件系统路径）；
	 *  **Web 上它是带 `opfs:/` 前缀的展示值，喂给 `remove_path` 会去找一个叫 `opfs:` 的目录**。
	 * 
	 *  两个路径字段并存且「该用哪个」按端不同，是这个 DTO 最容易踩空的地方——所以写在这里，
	 *  而不是让每个宿主自己从别处推断。
	 */
	localPath: string,
	missing: boolean,
};

/**  收件箱列表条目 DTO。 */
export type InboxItemSummary = {
	id: string,
	transferSessionId: string | null,
	sourcePeerId: string,
	sourceName: string,
	sourceKind: InboxSourceKind,
	contentKind: InboxContentKind,
	title: string,
	itemCount: number,
	totalSize: number,
	rootPath: string | null,
	contentHash: string | null,
	receivedAt: number,
	lastOpenedAt: number | null,
	archivedAt: number | null,
	deletedAt: number | null,
	missing: boolean,
};

/**  收件箱搜索命中（item 粒度）。 */
export type InboxSearchHit = {
	id: string,
	title: string,
	sourceName: string,
	itemCount: number,
	rootPath: string | null,
	receivedAt: number,
	/**
	 *  命中所在文本的片段（在 Rust 端按子串位置切窗口生成）。
	 * 
	 *  `None` = **不该渲染片段行**：命中的是标题或来源名（条目行上已经显示着），
	 *  或一个候选都没命中。判据在 [`inbox_snippet`]，三端不要各判一遍。
	 */
	snippet: string | null,
	/**  该条目下的文件（文件名 + 相对路径），供 get_inbox_file 下钻。 */
	files: InboxHitFile[],
};

/**  收件箱来源类型。 */
export type InboxSourceKind = "paired_device" | "share_code" | "mcp" | "unknown";

/**
 *  提交前校验失败的原因。
 * 
 *  每个变体都对应一句**用户能据以行动**的话。刻意不设 `Other(String)` 兜底：
 *  那会让新增的失败原因静默退化成一句无从下手的原始错误。
 */
export type InfraAddrError = 
/**  不是合法的 multiaddr。 */
{ kind: "malformed"; detail: string } | 
/**  缺少 `/p2p/<peer-id>` 段——没有身份就无法验证连上的是不是同一台。 */
{ kind: "missingPeerId" } | 
/**  地址里不含任何可拨传输段（如只有 `/p2p/<id>`）。 */
{ kind: "noTransport" } | 
/**  传输本端点没有装配。 */
{ kind: "unsupportedTransport"; 
/**
 *  地址里那个传输的 wire 名（`tcp` / `quic` / `webrtc` / `webrtcDirect` /
 *  `webtransport`）。
 */
transport: string; 
/**  本端点支持的传输，供 UI 直接列出来。 */
supported: string[] } | 
/**  指向本机。 */
{ kind: "selfAddr" } | 
/**  与既有条目重复（含内置清单）。 */
{ kind: "duplicate" };

/**
 *  一段基础设施关系当前不参与 relay 收敛的原因。
 * 
 *  **说的是「设置」不是「故障」**：UI 必须中性色 + CTA 指向设置，不得升警示色、
 *  不得给「重试」。
 * 
 *  目前只有一个变体，且刻意不预留第二个（本仓既有规矩：不造到不了 UI 的判别码）：
 *  - 没有 `NodeNotRunning`——节点运行态由 `NetworkStatus.status` 表达，而
 *    `build_network_status` 里那个值恒为 `Running`，加进来就是一个永远为假的分支；
 *  - 没有 `NotARelay`——纯 kad 候选**确实可构造**（`ensure_infra_intent` 把 roles 开成了
 *    参数），但它在读模型里由 `relay: None` + `roles.relay_server == false` 表达，
 *    shared-view 的 `deriveInfraLinkState` 据此判 `seedOnly`，那一档没有失败态。
 *    「不承担该角色」不是「承担但被拦下」，给它一个判别码只会让三端多一个渲染不出
 *    差异的分支——而且它要过 specta / uniffi / wasm 三条 codegen。判据见
 *    [`exclusion_for`](crate::infra::InfraSupervisor::exclusion_for)。
 */
export type InfraExclusion = 
/**  公网范围候选，但用户关闭了公网可达性。 */
{ kind: "publicReachabilityDisabled" };

/**
 *  一段基础设施关系的完整读模型。
 * 
 *  字段分三段，**并置但不融合**：上半段只由意图路径写，下半段只由观测源现算。
 *  两者共享同一身份（`peer_id`），而用户唯一关心的正是两者的差——「我要它连上，
 *  它连上了吗」。拆成两个类型再让三端各自 join，只会把 join 做三遍。
 */
export type InfraLink = {
	peerId: string,
	addrs: string[],
	sources: BootstrapCandidateSource[],
	roles: CandidateRoles,
	scope: CandidateScope,
	firstSeen: string,
	lastSeen: string,
	/**
	 *  用户能否在 UI 上移除这条：`sources` 里**含有** `HostConfigured` 即为 true。
	 * 
	 *  纯自动来源（mDNS / Learned）**不给移除入口**：撤销会断开与该节点的全部连接
	 *  （含在途传输），而局域网协助节点本身就可能是一台正在传文件的已配对设备；
	 *  何况它下次 identify 就会被原样登记回来——点了没反应，还把传输搞挂。
	 * 
	 *  ⚠️ 判据是「**含有**」不是「全是」。后者写过一版，是错的：`upsert` 对 `sources`
	 *  是**累加**（`candidates.rs`），而 `learn_candidate` 会给每个 identify 出
	 *  `is_bootstrap_agent` 的对端补一条 `Learned`——本仓自建的那台正是 bootstrap agent，
	 *  于是它连上几秒后 `removable` 就翻假，移除按钮当场消失；用户自己加的中继更糟：
	 *  一旦连上就永久删不掉，而偏好清单还在每次启动回放它，`forgetInfraNode` 再无可达路径。
	 *  用户往自己的清单里放过的东西，必须能从自己的清单里拿走。
	 */
	removable: boolean,
	/**
	 *  传输层是否已连上。只覆盖「已建立」——内核不外露在途拨号，所以没有 `Dialing` 态。
	 * 
	 *  **刻意没有 `rtt_ms`。** RTT 由 ping 更新（30s/peer），而 `PingSuccess` 已被
	 *  降级成只推设备列表——它改不动 `NetworkStatus` 的任何其它字段，全量推送不值当。
	 *  真把 rtt 挂进来，这一格就会停在首帧的 `null`（`PeerConnected` 那一刻还没测过），
	 *  只在别的事件碰巧触发时才刷新一次：一个偶尔更新的延迟数比没有更误导
	 *  （`DESIGN.md:645-649` 的同一条规则）。要显示 relay 延迟，先给它一条自己的
	 *  刷新通道，别顺手挂在这个读模型上。
	 */
	connected: boolean,
	/**  `None` = 这条关系在内核里没有 relay 轨道（不承担该角色，或被 `excluded` 拦下）。 */
	relay: RelayLinkState | null,
	/**  本次节点会话内是否曾建立过 reservation。宽限期的唯一开关。 */
	everActive: boolean,
	/**  非 `None` ⇒ 当前不参与 relay 收敛。 */
	excluded: InfraExclusion | null,
};

/**
 *  「已发出的邀请」列表条目（openspec: invite-persistence）。
 * 
 *  **没有邀请串本身**：capability 明文不落盘也不出注册表，刷新后拼不回原始链接。
 *  UI 只显示元数据 + 提供撤销；想再分享就生成一条新的。
 * 
 *  时间戳用字符串承载 Unix 秒，与 `pendingId` 同一个理由（避免 u64 → BigInt 的取回麻烦）。
 */
export type InviteListItemJson = {
	/**  `sha256(capability)` 的 hex —— 撤销时回传，UI 当不透明 ID 用。 */
	id: string,
	createdAt: string,
	expiresAt: string,
	/**  已被对方消费（仍显示到过期，让用户知道它被用过）。 */
	consumed: boolean,
};

/**  挂起 offer 的 JS 投影（`pending_offers()` 返回 `OfferJson[]`）。 */
export type OfferJson = {
	sessionId: string,
	peerId: string,
	peerName: string,
	totalSize: number,
	files: FileInfo[],
};

/**  Offer 被拒绝的原因。 */
export type OfferRejectReason = { type: "not_paired" } | { type: "user_declined" } | { type: "policy_rejected" } | 
/**  接收方处于全局「暂停接收」状态，婉拒新 offer。 */
{ type: "receiving_paused" } | 
/**
 *  Offer 里有文件的 `relative_path` 会逃出保存目录（绝对路径、盘符或 `..` 穿越）。
 * 
 *  独立成一个变体而不是并进 `PolicyRejected`：这**不是**接收方的偏好设置拒绝了你，
 *  而是这条 offer 本身不合法。两者对发送方的含义完全不同——前者「换个设置或问问对方」，
 *  后者「你的客户端发了非法数据」。合法客户端永远不会触发它。
 */
{ type: "unsafe_path" };

/**
 *  设备操作系统信息。
 * 
 *  `hostname` 是系统主机名（运行时取，桌面端通常是机器名，移动端通常拿不到）；
 *  `name` 是用户在 onboarding / 设置里起的名字（持久化），由 core 的组合根从
 *  [`DeviceConfig`](crate::ports::DeviceConfig) 端口填充，UI 显示按
 *  `name.as_deref().unwrap_or(&hostname)` 回退。
 */
export type OsInfo = {
	/**  用户起的设备名；缺省时回退到 `hostname`。 */
	name?: string | null,
	hostname: string,
	os: string,
	platform: string,
	arch: string,
	capabilities?: string[],
};

/**
 *  邀请串解码后的展示投影（配对确认卡用）。
 * 
 *  **不含 capability**：那是 128bit bearer 凭据，明文绝不出 wasm 边界——确认卡只需要
 *  「这是谁、还有效多久、是不是仅局域网」，多给一个字段就多一条泄漏路径。
 * 
 *  **TTL 由调用方按 `expiresAt` 判**，这里不放 `expired: bool`：确认卡会在屏幕上停留几十秒，
 *  而布尔在序列化那一刻就开始变旧。权威判定本来也在发起端的 `InviteRegistry`，
 *  解码侧的预检只为 UX（见 `PairInvite::decode` 的文档）。
 * 
 *  `expiresAt` 用字符串承载 Unix 秒，与 [`InviteListItemJson`] 同一个理由。
 */
export type PairInvitePreviewJson = {
	/**
	 *  发起方 NodeId（base58）。取自签名覆盖范围内的 `inviter_id`，伪造不了——
	 *  自我过滤 / 已配对过滤都该以它为判据。
	 */
	peerId: string,
	displayName: string,
	displayPlatform: string,
	expiresAt: string,
	/**  LocalOnly 策略（受邀方只用私网地址、禁公网 fallback）。 */
	localOnly: boolean,
};

/**
 *  一次配对尝试的结果（与桌面 `PairingOutcome` / 移动 `MobilePairingResult` 同构）。
 * 
 *  两个字段各自表达一种**不能压成错误的结果**：
 * 
 *  - `refused` —— 对方点了拒绝。这是一次完全正常的交互，不是失败。它曾经被包成
 *    `WebError::network("邀请方拒绝了配对或配对未成功")`，于是用户看到标题「网络错误」
 *    配一句写死的简体中文（英文界面下尤其突兀），而网络其实一切正常。**判别码进结构体，
 *    文案归前端**。
 *  - `persisted` —— 走到这一步对端已经收到 `Success` 并把本机加进了它的已配对列表，
 *    本机此时若报失败，两台设备对同一件事的认知就永久分叉了。真实后果只有一个 ——
 *    这台设备刷新/重启后会从本机列表消失（对端仍记着），UI 该照这个说。
 */
export type PairingOutcomeJson = {
	/**  对方拒绝时的原因判别码；`None` = 配对达成。 */
	refused: PairingRefusedJson | null,
	/**  已配对对端的 NodeId（base58）。`refused` 非空时是空串。 */
	peerId: string,
	/**
	 *  设备是否已落盘。`false` = 刷新页面后这台设备会不见（对端仍记着）。
	 *  仅在配对达成时有意义，被拒时恒为 `true`。
	 */
	persisted: boolean,
};

/**
 *  对方拒绝配对的原因判别码 —— 内核 `PairingRefuseReason` 的投影，wire 形状逐字相同
 *  （`{ type: "user_rejected" }`，与桌面 bindings 里那个类型可互换）。
 * 
 *  **为什么是投影而不是直接用内核类型**：`swarmdrop-core` 在本 crate 里是 wasm-only
 *  依赖（见 Cargo.toml），而本模块 native 也要编（specta 导出跑在 native）。
 * 
 *  **为什么这份重复是安全的**：唯一的构造点是 `node.rs` 里那个**穷尽 match**，内核加一个
 *  拒绝原因就会在那里编译失败。判别码不能靠字符串传 —— 那只会在运行时静默落到兜底分支。
 */
export type PairingRefusedJson = { type: "user_rejected" };

/**  连接路径类别（[`swarmdrop_net_base::PathKind`] 的 JS 投影，TS 侧是字符串联合）。 */
export type PathKindJson = "local" | "direct" | "relayed";

/**
 *  挂起入站配对请求的 JS 投影（`pending_pairing_requests()` 返回）。
 * 
 *  browser-as-inviter 用：桌面消费浏览器生成的 invite 后，浏览器（邀请方）本机需弹确认。
 *  `pendingId` 以字符串承载核心的 u64 pending id（避免 JS number 精度 + serde_wasm_bindgen
 *  对 u64 产 BigInt 的取回麻烦），`respond_pairing_request` 再 parse 回 u64。
 */
export type PendingPairingJson = {
	pendingId: string,
	peerId: string,
	deviceName: string,
};

/**  `prepare_send` 的 hash 进度事件 */
export type PrepareProgressEvent = {
	/**  用于区分并发 prepare（多用户在不同会话同时调用） */
	preparedId: string,
	/**  当前正在 hash 的文件名 */
	currentFile: string,
	/**  已完成 hash 的文件数 */
	completedFiles: number,
	/**  总文件数 */
	totalFiles: number,
	/**  累积已 hash 的字节数（所有文件） */
	bytesHashed: number,
	/**  总字节数（所有文件） */
	totalBytes: number,
};

/**  自动接收时的保存行为。 */
export type ReceiveSaveBehavior = 
/**  使用策略里配置的默认保存位置，接收完成后进入收件箱。 */
"inbox_and_default_save_location";

/**
 *  [`RelayState`] 的 IPC 投影。
 * 
 *  `last_error` **原样保留内核下发的字符串**——这是三端唯一能说清「为什么连不上」
 *  的东西，排查时用户要贴的就是这一句，不翻译、不改写。
 */
export type RelayLinkState = 
/**  正在拨号或等待 reservation 应答。 */
{ kind: "connecting" } | 
/**  reservation 已建立，携带内核拼装的 circuit 可达地址（调用方不得自行拼接）。 */
{ kind: "active"; circuitAddr: string } | 
/**  拨号失败或 reservation 失效，携带末次错误原文。**会自动重试**，文案不得给终态感。 */
{ kind: "failed"; lastError: string };

/**  断点续传被拒绝的原因。 */
export type ResumeRejectReason = { type: "cancelled" } | { type: "fatal_error" } | { type: "source_modified" } | { type: "checkpoint_invalid" } | { type: "peer_unavailable" } | { type: "session_not_found" };

export type RuntimeTransferDirection = "send" | "receive" | "unknown";

/**  suspended 原因（phase=Suspended 时有值）。 */
export type SuspendedReason = "local_paused" | "remote_paused" | "interrupted" | "peer_offline" | "app_restarted";

/**  terminal 原因（phase=Terminal 时有值）。 */
export type TerminalReason = "completed" | "cancelled" | "rejected" | "fatal_error" | 
/**
 *  入站 offer 的决策窗口耗尽，本端从未作答。
 * 
 *  **与 `Rejected` 分开是必要的，不是措辞讲究。** 对端看到的确实是一次婉拒（清理任务
 *  drop 掉 responder，RPC handler 据此回复），但本端用户**什么都没做**——把它记成
 *  「已拒绝」等于在他自己的传输历史里写一条他没做过的决定，而这恰恰是他下次想不起来
 *  「我拒过这个人吗」时会去查的地方。
 */
"expired";

/**  对方接受 Offer 的事件 payload */
export type TransferAcceptedEvent = {
	sessionId: string,
};

export type TransferCompleteEvent = {
	sessionId: string,
	direction: RuntimeTransferDirection,
	totalBytes: number,
	elapsedMs: number,
	saveLocation: CoreSaveLocation | null,
};

export type TransferDbErrorEvent = {
	sessionId: string,
	message: string,
};

/**  传输方向 */
export type TransferDirection = "send" | "receive";

export type TransferFailedEvent = {
	sessionId: string,
	direction: RuntimeTransferDirection,
	error: string,
};

export type TransferOfferEvent = {
	sessionId: string,
	peerId: string,
	deviceName: string,
	files: TransferOfferFileEvent[],
	totalSize: number,
	/**  发起来源（人工 / MCP 代理），供接收端 UI 标识。 */
	origin: TransferOrigin,
	policyAction: string | null,
	policyReason: string | null,
};

export type TransferOfferFileEvent = {
	fileId: number,
	name: string,
	relativePath: string,
	size: number,
	isDirectory: boolean,
};

/**
 *  传输发起来源：人在应用内发起，或 AI 代理经 MCP 发起。
 * 
 *  由发送方自报、承载于 Offer，供接收端展示与 inbox 来源派生——是信息性/UX 信号，
 *  不作接收端安全边界（真正的控制是发送端 `allow_mcp_send_to_device` 门控）。
 */
export type TransferOrigin = 
/**  用户在应用内手动发起。 */
{ type: "human" } | 
/**  AI 代理经 MCP 发起；`client` 为 MCP 客户端名（如 claude-desktop），不可得时为 None。 */
{ type: "mcp"; client: string | null };

export type TransferPausedEvent = {
	sessionId: string,
	direction: RuntimeTransferDirection,
};

/**
 *  传输生命周期大状态（phase）。
 *  替代旧的扁平 [`SessionStatus`]（过渡期并存）：phase 表达大状态，
 *  具体原因由 [`SuspendedReason`] / [`TerminalReason`] 表达。
 */
export type TransferPhase = "offered" | "waiting_accept" | "active" | "suspended" | "terminal";

export type TransferProgressEvent = {
	sessionId: string,
	direction: RuntimeTransferDirection,
	totalFiles: number,
	completedFiles: number,
	totalBytes: number,
	transferredBytes: number,
	speed: number | null,
	eta: number | null,
	files: FileProgressInfo[],
};

/**  传输投影 DTO —— 前端唯一状态源（逐步替代旧的分散事件 + 扁平 `SessionStatus`）。 */
export type TransferProjection = {
	sessionId: string,
	direction: TransferDirection,
	peerId: string,
	peerName: string,
	phase: TransferPhase,
	suspendedReason: SuspendedReason | null,
	terminalReason: TerminalReason | null,
	recoverable: boolean,
	epoch: number,
	totalSize: number,
	transferredBytes: number,
	startedAt: number,
	updatedAt: number,
	finishedAt: number | null,
	/**  失败判别码（见 [`crate::failure`]）。曾是直达三端 UI 的自由中文文本。 */
	failure: FailureCode | null,
	policyAction: string | null,
	policyReason: string | null,
	savePath: CoreSaveLocation | null,
	/**
	 *  「打开文件夹」应定位的真实容器目录 URI(收到内容实际所在的文件夹),已在 core 解析:
	 *  各文件 `local_dir` 全部同一目录 → 该目录;否则回退存储根 `save_path`。前端直读,
	 *  不再自行兜底(已完成接收必为 `Some`)。
	 */
	contentRoot: string | null,
	files: TransferProjectionFile[],
};

export type TransferProjectionFile = {
	fileId: number,
	name: string,
	relativePath: string,
	size: number,
	transferredBytes: number,
};

/**  对方拒绝 Offer 的事件 payload */
export type TransferRejectedEvent = {
	sessionId: string,
	reason: OfferRejectReason | null,
};

export type TransferResumedEvent = {
	sessionId: string,
	direction: RuntimeTransferDirection,
	peerId: string,
	peerName: string,
	files: TransferResumedFileInfo[],
	totalSize: number,
};

export type TransferResumedFileInfo = {
	fileId: number,
	name: string,
	relativePath: string,
	size: number,
	isDirectory: boolean,
};

/**
 *  承载连接的传输协议（由 multiaddr 协议栈判定，见 [`Addr::transport`](crate::Addr::transport)）。
 * 
 *  与 [`PathKind`] **正交**，排障时要一起看：`PathKind` 回答「字节走不走中继」，
 *  本枚举回答「字节跑在哪种传输上」。同是 `Relayed`，底层 TCP 还是 QUIC 指向
 *  完全不同的排查方向；同是 `Direct`，`Webrtc` 说明是打洞来的、`Quic` 说明是公网直拨。
 * 
 *  变体名刻意不写成 `WebRtc`：camelCase 序列化后会变成 `"webRtc"`，而三端 UI 与
 *  日志里这个词一直是 `webrtc`。
 */
export type TransportKind = 
/**  TCP（上叠 Noise + Yamux）。 */
"tcp" | 
/**  QUIC v1（传输层自带 TLS）。 */
"quic" | 
/**  WebRTC 打洞：**信令**经 relay，数据面一个字节不过中继。 */
"webrtc" | 
/**  WebRTC Direct：certhash 免信令免域名，浏览器够到原生端的唯一入口。 */
"webrtcDirect" | 
/**
 *  WebTransport（HTTP/3 over QUIC）：与 WebRTC Direct 同样是「certhash 免域名」，
 *  但数据面就是 QUIC —— 没有 ICE/DTLS/SCTP 三层的转发开销。
 */
"webtransport";

/**
 *  Web 壳对外错误。`kind` 供 JS 分支，`message` 供展示。
 * 
 *  wasm-bindgen 方法 reject 的错误值就是本类型的序列化对象（`{ kind, message }`）——
 *  **不拍成字符串**（字符串丢了机器可判别的 kind）。JsValue 转换在 `error.rs`。
 */
export type WebError = 
/**  身份 / 密钥错误。 */
{ kind: "identity"; message: string } | 
/**  网络 / 连接 / DHT 错误。 */
{ kind: "network"; message: string } | 
/**  传输错误。 */
{ kind: "transfer"; message: string } | 
/**  入参非法（地址格式、缺 `/p2p/` 等）。 */
{ kind: "invalidInput"; message: string } | 
/**
 *  调用被 `AbortSignal` 取消。**abort ≠ 撤回拨号**：Promise 立即 reject 且
 *  无常驻意图残留，但在途拨号会继续到自然失败（libp2p 无逐次拨号取消面）。
 */
{ kind: "aborted"; message: string } | 
/**  分享码不存在 / 已过期。 */
{ kind: "notFound"; message: string } | 
/**  存储（OPFS / localStorage）错误。 */
{ kind: "storage"; message: string };

/**
 *  `TransferEvent` 的可序列化镜像（1:1 变体，字段与 payload 同名）。
 * 
 *  `TransferEvent` 本身未 derive `Serialize`（transfer 不改）——与桌面把它映射进
 *  `CoreEvent` 的适配范式一致。`events()` 的 ReadableStream 逐条产出本类型的序列化对象。
 */
export type WebTransferEvent = { type: "transferOfferReceived"; offer: TransferOfferEvent } | { type: "transferProgress"; event: TransferProgressEvent } | { type: "transferAccepted"; event: TransferAcceptedEvent } | { type: "transferRejected"; event: TransferRejectedEvent } | { type: "transferCompleted"; event: TransferCompleteEvent } | { type: "transferFailed"; event: TransferFailedEvent } | { type: "transferPaused"; event: TransferPausedEvent } | { type: "transferResumed"; event: TransferResumedEvent } | { type: "transferDbError"; event: TransferDbErrorEvent } | { type: "transferProjection"; projection: TransferProjection } | { type: "prepareProgress"; event: PrepareProgressEvent } | { type: "filePublish"; event: FilePublishEvent };
