// 由 `cargo test -p swarmdrop-web --features specta --test specta_export` 生成，勿手改。
// 形状与运行期 serde_wasm_bindgen 序列化一致（u64 等已映射为 number）。

// This file has been generated by Specta. Do not edit this file manually.
/**  `connect()` 的结构化返回。 */
export type ConnectionJson = {
	path: PathKindJson,
	addr: string,
};

/**
 *  接收端保存位置（host-agnostic）。
 * 
 *  core 内部统一用此类型，避免把 `entity::SaveLocation`（SeaORM 实体细节）
 *  暴露到公共 API 上。DB 边界用 [`From`] 与 `entity::SaveLocation` 双向转换。
 */
export type CoreSaveLocation = 
/**  文件系统绝对路径（桌面）或 `Paths.document` 子路径（移动端）。 */
{ type: "path"; path: string };

/**  传输文件元信息。 */
export type FileInfo = {
	fileId: number,
	name: string,
	relativePath: string,
	size: number,
	checksum: string,
};

export type FileProgressInfo = {
	fileId: number,
	name: string,
	size: number,
	transferred: number,
	status: FileTransferStatus,
};

export type FileTransferStatus = "pending" | "transferring" | "completed";

/**  `lookup_share_code()` 的结构化返回（`NodeAddr` 的 JS 投影）。 */
export type NodeAddrJson = {
	id: string,
	addrs: string[],
};

/**  挂起 offer 的 JS 投影（`pending_offers()` 返回 `OfferJson[]`）。 */
export type OfferJson = {
	sessionId: string,
	peerId: string,
	peerName: string,
	totalSize: number,
	files: FileInfo[],
};

/**  Offer 被拒绝的原因。 */
export type OfferRejectReason = { type: "not_paired" } | { type: "user_declined" } | { type: "policy_rejected" } | 
/**  接收方处于全局「暂停接收」状态，婉拒新 offer。 */
{ type: "receiving_paused" };

/**  连接路径类别（[`swarmdrop_net_base::PathKind`] 的 JS 投影，TS 侧是字符串联合）。 */
export type PathKindJson = "local" | "direct" | "relayed";

/**  `prepare_send` 的 hash 进度事件 */
export type PrepareProgressEvent = {
	/**  用于区分并发 prepare（多用户在不同会话同时调用） */
	preparedId: string,
	/**  当前正在 hash 的文件名 */
	currentFile: string,
	/**  已完成 hash 的文件数 */
	completedFiles: number,
	/**  总文件数 */
	totalFiles: number,
	/**  累积已 hash 的字节数（所有文件） */
	bytesHashed: number,
	/**  总字节数（所有文件） */
	totalBytes: number,
};

export type RuntimeTransferDirection = "send" | "receive" | "unknown";

/**  suspended 原因（phase=Suspended 时有值）。 */
export type SuspendedReason = "local_paused" | "remote_paused" | "interrupted" | "peer_offline" | "app_restarted";

/**  terminal 原因（phase=Terminal 时有值）。 */
export type TerminalReason = "completed" | "cancelled" | "rejected" | "fatal_error";

/**  对方接受 Offer 的事件 payload */
export type TransferAcceptedEvent = {
	sessionId: string,
};

export type TransferCompleteEvent = {
	sessionId: string,
	direction: RuntimeTransferDirection,
	totalBytes: number,
	elapsedMs: number,
	saveLocation: CoreSaveLocation | null,
};

export type TransferDbErrorEvent = {
	sessionId: string,
	message: string,
};

/**  传输方向 */
export type TransferDirection = "send" | "receive";

export type TransferFailedEvent = {
	sessionId: string,
	direction: RuntimeTransferDirection,
	error: string,
};

export type TransferOfferEvent = {
	sessionId: string,
	peerId: string,
	deviceName: string,
	files: TransferOfferFileEvent[],
	totalSize: number,
	/**  发起来源（人工 / MCP 代理），供接收端 UI 标识。 */
	origin: TransferOrigin,
	policyAction: string | null,
	policyReason: string | null,
};

export type TransferOfferFileEvent = {
	fileId: number,
	name: string,
	relativePath: string,
	size: number,
	isDirectory: boolean,
};

/**
 *  传输发起来源：人在应用内发起，或 AI 代理经 MCP 发起。
 * 
 *  由发送方自报、承载于 Offer，供接收端展示与 inbox 来源派生——是信息性/UX 信号，
 *  不作接收端安全边界（真正的控制是发送端 `allow_mcp_send_to_device` 门控）。
 */
export type TransferOrigin = 
/**  用户在应用内手动发起。 */
{ type: "human" } | 
/**  AI 代理经 MCP 发起；`client` 为 MCP 客户端名（如 claude-desktop），不可得时为 None。 */
{ type: "mcp"; client: string | null };

export type TransferPausedEvent = {
	sessionId: string,
	direction: RuntimeTransferDirection,
};

/**
 *  传输生命周期大状态（phase）。
 *  替代旧的扁平 [`SessionStatus`]（过渡期并存）：phase 表达大状态，
 *  具体原因由 [`SuspendedReason`] / [`TerminalReason`] 表达。
 */
export type TransferPhase = "offered" | "waiting_accept" | "active" | "suspended" | "terminal";

export type TransferProgressEvent = {
	sessionId: string,
	direction: RuntimeTransferDirection,
	totalFiles: number,
	completedFiles: number,
	totalBytes: number,
	transferredBytes: number,
	speed: number | null,
	eta: number | null,
	files: FileProgressInfo[],
};

/**  传输投影 DTO —— 前端唯一状态源（逐步替代旧的分散事件 + 扁平 `SessionStatus`）。 */
export type TransferProjection = {
	sessionId: string,
	direction: TransferDirection,
	peerId: string,
	peerName: string,
	phase: TransferPhase,
	suspendedReason: SuspendedReason | null,
	terminalReason: TerminalReason | null,
	recoverable: boolean,
	epoch: number,
	totalSize: number,
	transferredBytes: number,
	startedAt: number,
	updatedAt: number,
	finishedAt: number | null,
	errorMessage: string | null,
	policyAction: string | null,
	policyReason: string | null,
	savePath: CoreSaveLocation | null,
	/**
	 *  「打开文件夹」应定位的真实容器目录 URI(收到内容实际所在的文件夹),已在 core 解析:
	 *  各文件 `local_dir` 全部同一目录 → 该目录;否则回退存储根 `save_path`。前端直读,
	 *  不再自行兜底(已完成接收必为 `Some`)。
	 */
	contentRoot: string | null,
	files: TransferProjectionFile[],
};

export type TransferProjectionFile = {
	fileId: number,
	name: string,
	relativePath: string,
	size: number,
	transferredBytes: number,
};

/**  对方拒绝 Offer 的事件 payload */
export type TransferRejectedEvent = {
	sessionId: string,
	reason: OfferRejectReason | null,
};

export type TransferResumedEvent = {
	sessionId: string,
	direction: RuntimeTransferDirection,
	peerId: string,
	peerName: string,
	files: TransferResumedFileInfo[],
	totalSize: number,
};

export type TransferResumedFileInfo = {
	fileId: number,
	name: string,
	relativePath: string,
	size: number,
	isDirectory: boolean,
};

/**
 *  Web 壳对外错误。`kind` 供 JS 分支，`message` 供展示。
 * 
 *  wasm-bindgen 方法 reject 的错误值就是本类型的序列化对象（`{ kind, message }`）——
 *  **不拍成字符串**（字符串丢了机器可判别的 kind）。JsValue 转换在 `error.rs`。
 */
export type WebError = 
/**  身份 / 密钥错误。 */
{ kind: "identity"; message: string } | 
/**  网络 / 连接 / DHT 错误。 */
{ kind: "network"; message: string } | 
/**  传输错误。 */
{ kind: "transfer"; message: string } | 
/**  入参非法（地址格式、缺 `/p2p/` 等）。 */
{ kind: "invalidInput"; message: string } | 
/**  分享码不存在 / 已过期。 */
{ kind: "notFound"; message: string } | 
/**  存储（OPFS / localStorage）错误。 */
{ kind: "storage"; message: string };

/**
 *  `TransferEvent` 的可序列化镜像（1:1 变体，字段与 payload 同名）。
 * 
 *  `TransferEvent` 本身未 derive `Serialize`（transfer 不改）——与桌面把它映射进
 *  `CoreEvent` 的适配范式一致。`events()` 的 ReadableStream 逐条产出本类型的序列化对象。
 */
export type WebTransferEvent = { type: "transferOfferReceived"; offer: TransferOfferEvent } | { type: "transferProgress"; event: TransferProgressEvent } | { type: "transferAccepted"; event: TransferAcceptedEvent } | { type: "transferRejected"; event: TransferRejectedEvent } | { type: "transferCompleted"; event: TransferCompleteEvent } | { type: "transferFailed"; event: TransferFailedEvent } | { type: "transferPaused"; event: TransferPausedEvent } | { type: "transferResumed"; event: TransferResumedEvent } | { type: "transferDbError"; event: TransferDbErrorEvent } | { type: "transferProjection"; projection: TransferProjection } | { type: "prepareProgress"; event: PrepareProgressEvent };
