//! Tauri Builder 装配
//!
//! 把 [`crate::run`] 拆成四段：tracing 初始化 / plugin 注册 / setup hook /
//! 命令注册。每段各司其职，方便调整。
//!
//! 命令通过 [`tauri-specta`] 收集，debug build 会同时把 TypeScript bindings
//! 导出到 `src/lib/bindings.ts`，供前端 typesafe 调用。

use std::sync::Arc;

use tauri::{Builder, Manager, Wry};
use tauri_specta::{Builder as SpectaBuilder, ErrorHandlingMode, collect_commands, collect_events};
use tracing_subscriber::{EnvFilter, fmt, prelude::*};

use crate::{commands, events};

/// 初始化 tracing 订阅器（默认 `swarmdrop=debug,swarmdrop_net=debug`，可被
/// `RUST_LOG` 覆盖）
pub fn init_tracing() {
    tracing_subscriber::registry()
        .with(fmt::layer())
        .with(
            EnvFilter::try_from_default_env()
                .unwrap_or_else(|_| EnvFilter::new("swarmdrop=debug,swarmdrop_net=debug")),
        )
        .init();
}

/// 构造 tauri-specta [`SpectaBuilder`]：所有 IPC 命令在此集中注册。
///
/// 单独抽出便于测试中导出 TS bindings（`src-tauri/tests/specta_export.rs`），
/// 避免依赖完整的 `tauri::Builder`。
///
/// 启用 [`SpectaBuilder::dangerously_cast_bigints_to_number`]：本应用的所有
/// `u64` / `i64` / `usize` 字段（文件大小、毫秒时间戳、字节计数）都在 JS 安全
/// 整数范围（< 2^53）内，统一映射成 TS `number` 比 `bigint` 对前端更友好。
pub fn specta_builder() -> SpectaBuilder<Wry> {
    SpectaBuilder::<Wry>::new()
        .dangerously_cast_bigints_to_number()
        // Throw 模式：生成的 commands 直接 throw，前端代码维持现有 try/catch 习惯，
        // 不用改成 `if (r.status === "error") ...` 的 Result tuple 风格。
        .error_handling(ErrorHandlingMode::Throw)
        .commands(collect_commands![
            // lifecycle
            commands::start,
            commands::shutdown,
            commands::list_devices,
            commands::get_network_status,
            commands::install_update,
            // inbox
            commands::list_inbox_items,
            commands::search_inbox,
            commands::get_inbox_item_detail,
            commands::get_inbox_item_by_transfer_session_id,
            commands::repair_missing_inbox_items,
            commands::open_inbox_item,
            commands::show_inbox_item_in_folder,
            commands::export_inbox_item,
            commands::archive_inbox_item,
            commands::delete_inbox_item,
            // identity
            commands::initialize_identity,
            commands::generate_keypair,
            commands::register_keypair,
            commands::get_device_name,
            commands::set_device_name,
            // pairing
            commands::generate_pair_invite,
            commands::invite_qr_svg,
            commands::decode_pair_invite,
            commands::consume_pair_invite,
            commands::request_pairing,
            commands::respond_pairing_request,
            commands::remove_paired_device,
            commands::update_paired_device_policy,
            // transfer
            commands::scan_sources,
            commands::prepare_send,
            commands::start_send,
            commands::accept_receive,
            commands::reject_receive,
            commands::cancel_send,
            commands::cancel_receive,
            commands::get_transfer_projections,
            commands::get_transfer_source_paths,
            commands::delete_transfer_session,
            commands::clear_transfer_history,
            commands::pause_transfer,
            commands::resume_transfer,
            commands::set_receiving_paused,
            commands::is_receiving_paused,
            // 应用窗口 / 托盘
            commands::quit_app,
            // 语言（托盘 + 系统通知等原生字符串本地化）
            commands::set_locale,
            // mcp
            commands::get_mcp_status,
            commands::start_mcp_server,
            commands::stop_mcp_server,
            // 外部文件打开（Open With → share-target）
            commands::take_pending_external_open,
        ])
        .events(collect_events![
            events::NetworkStatusChanged,
            events::DevicesChanged,
            events::PairingRequestReceived,
            events::PairedDeviceAdded,
            events::TransferOffer,
            events::TransferProgress,
            events::TransferAccepted,
            events::TransferRejected,
            events::TransferComplete,
            events::TransferFailed,
            events::TransferPaused,
            events::TransferResumed,
            events::TransferDbError,
            events::TransferProjectionUpdate,
            events::ReceivingPausedChanged,
            events::ExternalFileOpen,
            events::TrayOpenReceiveFolder,
            events::TrayOpenSettings,
        ])
}

/// 构造完整的 [`Builder`]：plugin → tauri-specta handler → setup hook。
pub fn build_app() -> Builder<Wry> {
    let specta = specta_builder();

    // debug build 时导出 TS bindings；release build 跳过避免误覆盖。
    #[cfg(debug_assertions)]
    {
        use specta_typescript::Typescript;
        if let Err(e) = specta.export(
            Typescript::default().header("// AUTO-GENERATED by tauri-specta. DO NOT EDIT.\n"),
            "../src/lib/bindings.ts",
        ) {
            tracing::warn!("Failed to export specta TS bindings: {e}");
        }
    }

    let builder = register_plugins(Builder::default()).invoke_handler(specta.invoke_handler());
    register_setup(builder, specta)
}

/// 注册所有官方 + 第三方 plugin。
fn register_plugins(builder: Builder<Wry>) -> Builder<Wry> {
    let builder = builder
        // single-instance 必须最先注册：常驻后台 app 二次启动时唤出已有窗口而非再起进程，
        // 避免出现两个托盘图标 / 状态错乱。
        .plugin(tauri_plugin_single_instance::init(|app, args, _cwd| {
            // 无文件的二次启动：唤出主窗口。带文件的「用本应用打开」由 handle_second_instance
            // 处理（Windows/Linux 从 argv 取路径，macOS 走 RunEvent::Opened、此调用 no-op）。
            crate::tray::show_main_window(app);
            crate::external_open::handle_second_instance(app, args);
        }))
        .plugin(tauri_plugin_store::Builder::new().build())
        .plugin(tauri_plugin_os::init())
        .plugin(tauri_plugin_fs::init())
        .plugin(tauri_plugin_biometry::init())
        .plugin(tauri_plugin_notification::init())
        .plugin(tauri_plugin_opener::init())
        .plugin(tauri_plugin_dialog::init())
        .plugin(tauri_plugin_http::init())
        .plugin(tauri_plugin_process::init());

    // MCP Bridge —— 仅 debug build 注册,供 @hypothesi/tauri-mcp-server 调试
    // (读日志 / 调 IPC / 操作 WebView)。默认监听 0.0.0.0:9223;release 不注册。
    #[cfg(debug_assertions)]
    let builder = builder.plugin(tauri_plugin_mcp_bridge::init());

    // WebDriver E2E —— 仅 debug build 注册,供 e2e/desktop 下的 WebdriverIO 原生模式测试用。
    // wdio-webdriver 起内嵌 WebDriver server(embedded provider,零外部进程);wdio 提供
    // browser.tauri.execute / IPC mock / 前后端日志采集。release 不注册,攻击面仅限 dev。
    #[cfg(debug_assertions)]
    let builder = builder
        .plugin(tauri_plugin_wdio_webdriver::init())
        .plugin(tauri_plugin_wdio::init());

    builder
}

/// `setup` hook：updater plugin 容错注册 + 数据库初始化 + MCP state 装配 +
/// tauri-specta event mount。
fn register_setup(builder: Builder<Wry>, specta: SpectaBuilder<Wry>) -> Builder<Wry> {
    builder.setup(move |app| {
        // tauri-specta events —— 当前未声明事件，为将来扩展预留 mount 钩子。
        specta.mount_events(app);

        // 原生字符串（托盘 / 系统通知）locale：前端 preferences-store 为权威源，此处读
        // 持久化值应用到 rust-i18n，保证托盘首帧即正确语言（必须在 build_tray 之前）。
        crate::i18n::init_locale_from_store(app.handle());

        // 系统托盘：常驻图标 + 菜单。句柄存入 state 长存（被 drop 图标会消失）。
        crate::tray::build_tray(app.handle())?;

        // 平台标题栏调整:macOS 由 tauri.conf.json 的 trafficLightPosition 控制红绿灯位置;
        // Windows / Linux 需要运行时关装饰,改由前端自画最小化/最大化/关闭三按钮。
        #[cfg(not(target_os = "macos"))]
        {
            if let Some(window) = app.get_webview_window("main") {
                let _ = window.set_decorations(false);
            }
        }

        // updater plugin —— 移动端不支持时静默跳过
        if let Err(e) = app
            .handle()
            .plugin(tauri_plugin_updater::Builder::new().build())
        {
            tracing::warn!("Failed to initialize updater plugin: {e}");
        }

        // 事件总线提前注入：启动清理也会经 Coordinator 发布 TransferProjection。
        let event_bus = crate::host::event_bus::TauriEventBus::new(app.handle().clone());
        app.manage(event_bus.clone());

        // 数据库（SeaORM + SQLite）—— 同步执行 + 启动清理过期会话
        let handle = app.handle().clone();
        let db = tauri::async_runtime::block_on(crate::database::init_database(&handle))?;
        let cleanup_event_bus: Arc<dyn swarmdrop_core::host::EventBus> = Arc::new(event_bus);
        tauri::async_runtime::block_on(crate::database::cleanup_stale_sessions(
            &db,
            cleanup_event_bus,
        ))?;
        app.manage(db);

        // MCP server 状态容器
        app.manage(crate::mcp::server::McpServerState::default());

        // 网络运行时状态容器。启动节点前为 None，避免依赖 NetManagerState 的命令
        // 在节点未启动时触发 Tauri 的 "state not managed" 注入错误。
        app.manage(tokio::sync::Mutex::new(None::<crate::network::NetManager>));

        // 外部「用 SwarmDrop 打开」：后台注册处理器 + 冷启动参数解析。缓冲用模块内全局
        // OnceLock（不依赖此处时序：macOS 冷启动 Opened 可能早于本 setup）。
        // 平台差异（macOS 走 RunEvent::Opened、其余走 argv）封装在 external_open 内部。
        crate::external_open::register_open_with();
        crate::external_open::handle_launch_args(app.handle());

        Ok(())
    })
}

#[cfg(test)]
mod tests {
    /// 让 `cargo test` 即可再生 TS bindings（否则只有 debug 运行 app 才导出）
    #[test]
    fn export_ts_bindings() {
        use specta_typescript::Typescript;
        super::specta_builder()
            .export(
                Typescript::default().header("// AUTO-GENERATED by tauri-specta. DO NOT EDIT.\n"),
                concat!(env!("CARGO_MANIFEST_DIR"), "/../src/lib/bindings.ts"),
            )
            .expect("export TS bindings");
    }
}
