//! Tauri Builder 装配
//!
//! 把 [`crate::run`] 拆成四段：tracing 初始化 / plugin 注册 / setup hook /
//! 命令注册。每段各司其职，方便调整。
//!
//! 命令通过 [`tauri-specta`] 收集，debug build 会同时把 TypeScript bindings
//! 导出到 `src/lib/bindings.ts`，供前端 typesafe 调用。

use tauri::{Builder, Manager, Wry};
use tauri_specta::{collect_commands, collect_events, Builder as SpectaBuilder, ErrorHandlingMode};
use tracing_subscriber::{fmt, prelude::*, EnvFilter};

use crate::{commands, events};

/// 初始化 tracing 订阅器（默认 `swarmdrop=debug,swarm_p2p_core=debug`，可被
/// `RUST_LOG` 覆盖）
pub fn init_tracing() {
    tracing_subscriber::registry()
        .with(fmt::layer())
        .with(
            EnvFilter::try_from_default_env()
                .unwrap_or_else(|_| EnvFilter::new("swarmdrop=debug,swarm_p2p_core=debug")),
        )
        .init();
}

/// 构造 tauri-specta [`SpectaBuilder`]：所有 IPC 命令在此集中注册。
///
/// 单独抽出便于测试中导出 TS bindings（`src-tauri/tests/specta_export.rs`），
/// 避免依赖完整的 `tauri::Builder`。
///
/// 启用 [`SpectaBuilder::dangerously_cast_bigints_to_number`]：本应用的所有
/// `u64` / `i64` / `usize` 字段（文件大小、毫秒时间戳、字节计数）都在 JS 安全
/// 整数范围（< 2^53）内，统一映射成 TS `number` 比 `bigint` 对前端更友好。
pub fn specta_builder() -> SpectaBuilder<Wry> {
    SpectaBuilder::<Wry>::new()
        .dangerously_cast_bigints_to_number()
        // Throw 模式：生成的 commands 直接 throw，前端代码维持现有 try/catch 习惯，
        // 不用改成 `if (r.status === "error") ...` 的 Result tuple 风格。
        .error_handling(ErrorHandlingMode::Throw)
        .commands(collect_commands![
            // lifecycle
            commands::start,
            commands::shutdown,
            commands::list_devices,
            commands::get_network_status,
            commands::install_update,
            // identity
            commands::initialize_identity,
            commands::generate_keypair,
            commands::register_keypair,
            commands::get_device_name,
            commands::set_device_name,
            // pairing
            commands::generate_pairing_code,
            commands::get_device_info,
            commands::request_pairing,
            commands::respond_pairing_request,
            commands::remove_paired_device,
            // transfer
            commands::scan_sources,
            commands::prepare_send,
            commands::start_send,
            commands::accept_receive,
            commands::reject_receive,
            commands::cancel_send,
            commands::cancel_receive,
            commands::get_transfer_history,
            commands::get_transfer_session,
            commands::delete_transfer_session,
            commands::clear_transfer_history,
            commands::pause_transfer,
            commands::resume_transfer,
            // mcp
            commands::get_mcp_status,
            commands::start_mcp_server,
            commands::stop_mcp_server,
        ])
        .events(collect_events![
            events::NetworkStatusChanged,
            events::DevicesChanged,
            events::PairingRequestReceived,
            events::PairedDeviceAdded,
            events::TransferOffer,
            events::TransferProgress,
            events::TransferAccepted,
            events::TransferRejected,
            events::TransferComplete,
            events::TransferFailed,
            events::TransferPaused,
            events::TransferResumed,
            events::TransferDbError,
        ])
}

/// 构造完整的 [`Builder`]：plugin → tauri-specta handler → setup hook。
pub fn build_app() -> Builder<Wry> {
    let specta = specta_builder();

    // debug build 时导出 TS bindings；release build 跳过避免误覆盖。
    #[cfg(debug_assertions)]
    {
        use specta_typescript::Typescript;
        if let Err(e) = specta.export(
            Typescript::default().header("// AUTO-GENERATED by tauri-specta. DO NOT EDIT.\n"),
            "../src/lib/bindings.ts",
        ) {
            tracing::warn!("Failed to export specta TS bindings: {e}");
        }
    }

    let builder = register_plugins(Builder::default()).invoke_handler(specta.invoke_handler());
    register_setup(builder, specta)
}

/// 注册所有官方 + 第三方 plugin。
fn register_plugins(builder: Builder<Wry>) -> Builder<Wry> {
    let builder = builder
        .plugin(tauri_plugin_store::Builder::new().build())
        .plugin(tauri_plugin_os::init())
        .plugin(tauri_plugin_fs::init())
        .plugin(tauri_plugin_biometry::init())
        .plugin(tauri_plugin_notification::init())
        .plugin(tauri_plugin_opener::init())
        .plugin(tauri_plugin_dialog::init())
        .plugin(tauri_plugin_http::init())
        .plugin(tauri_plugin_process::init());

    // MCP Bridge —— 仅 debug build 注册,供 @hypothesi/tauri-mcp-server 调试
    // (读日志 / 调 IPC / 操作 WebView)。默认监听 0.0.0.0:9223;release 不注册。
    #[cfg(debug_assertions)]
    let builder = builder.plugin(tauri_plugin_mcp_bridge::init());

    builder
}

/// `setup` hook：updater plugin 容错注册 + 数据库初始化 + MCP state 装配 +
/// tauri-specta event mount。
fn register_setup(builder: Builder<Wry>, specta: SpectaBuilder<Wry>) -> Builder<Wry> {
    builder.setup(move |app| {
        // tauri-specta events —— 当前未声明事件，为将来扩展预留 mount 钩子。
        specta.mount_events(app);

        // 平台标题栏调整:macOS 由 tauri.conf.json 的 trafficLightPosition 控制红绿灯位置;
        // Windows / Linux 需要运行时关装饰,改由前端自画最小化/最大化/关闭三按钮。
        #[cfg(not(target_os = "macos"))]
        {
            if let Some(window) = app.get_webview_window("main") {
                let _ = window.set_decorations(false);
            }
        }

        // updater plugin —— 移动端不支持时静默跳过
        if let Err(e) = app
            .handle()
            .plugin(tauri_plugin_updater::Builder::new().build())
        {
            tracing::warn!("Failed to initialize updater plugin: {e}");
        }

        // 数据库（SeaORM + SQLite）—— 同步执行 + 启动清理过期会话
        let handle = app.handle().clone();
        let db = tauri::async_runtime::block_on(crate::database::init_database(&handle))?;
        tauri::async_runtime::block_on(crate::database::cleanup_stale_sessions(&db))?;
        app.manage(db);

        // MCP server 状态容器
        app.manage(crate::mcp::server::McpServerState::default());

        // 网络运行时状态容器。启动节点前为 None，避免依赖 NetManagerState 的命令
        // 在节点未启动时触发 Tauri 的 "state not managed" 注入错误。
        app.manage(tokio::sync::Mutex::new(None::<crate::network::NetManager>));

        Ok(())
    })
}
