/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppPairingRouteImport } from './routes/_app/pairing'
import { Route as AppSendIndexRouteImport } from './routes/_app/send/index'

const AppTransferIndexLazyRouteImport = createFileRoute('/_app/transfer/')()
const AppSettingsIndexLazyRouteImport = createFileRoute('/_app/settings/')()
const AppReceiveIndexLazyRouteImport = createFileRoute('/_app/receive/')()
const AppPairingIndexLazyRouteImport = createFileRoute('/_app/pairing/')()
const AppDevicesIndexLazyRouteImport = createFileRoute('/_app/devices/')()
const AppTransferSessionIdLazyRouteImport = createFileRoute(
  '/_app/transfer/$sessionId',
)()
const AppPairingInputLazyRouteImport = createFileRoute('/_app/pairing/input')()
const AppPairingGenerateLazyRouteImport = createFileRoute(
  '/_app/pairing/generate',
)()

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPairingRoute = AppPairingRouteImport.update({
  id: '/pairing',
  path: '/pairing',
  getParentRoute: () => AppRoute,
} as any)
const AppTransferIndexLazyRoute = AppTransferIndexLazyRouteImport.update({
  id: '/transfer/',
  path: '/transfer/',
  getParentRoute: () => AppRoute,
} as any).lazy(() =>
  import('./routes/_app/transfer/index.lazy').then((d) => d.Route),
)
const AppSettingsIndexLazyRoute = AppSettingsIndexLazyRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AppRoute,
} as any).lazy(() =>
  import('./routes/_app/settings/index.lazy').then((d) => d.Route),
)
const AppReceiveIndexLazyRoute = AppReceiveIndexLazyRouteImport.update({
  id: '/receive/',
  path: '/receive/',
  getParentRoute: () => AppRoute,
} as any).lazy(() =>
  import('./routes/_app/receive/index.lazy').then((d) => d.Route),
)
const AppPairingIndexLazyRoute = AppPairingIndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppPairingRoute,
} as any).lazy(() =>
  import('./routes/_app/pairing/index.lazy').then((d) => d.Route),
)
const AppDevicesIndexLazyRoute = AppDevicesIndexLazyRouteImport.update({
  id: '/devices/',
  path: '/devices/',
  getParentRoute: () => AppRoute,
} as any).lazy(() =>
  import('./routes/_app/devices/index.lazy').then((d) => d.Route),
)
const AppSendIndexRoute = AppSendIndexRouteImport.update({
  id: '/send/',
  path: '/send/',
  getParentRoute: () => AppRoute,
} as any).lazy(() =>
  import('./routes/_app/send/index.lazy').then((d) => d.Route),
)
const AppTransferSessionIdLazyRoute =
  AppTransferSessionIdLazyRouteImport.update({
    id: '/transfer/$sessionId',
    path: '/transfer/$sessionId',
    getParentRoute: () => AppRoute,
  } as any).lazy(() =>
    import('./routes/_app/transfer/$sessionId.lazy').then((d) => d.Route),
  )
const AppPairingInputLazyRoute = AppPairingInputLazyRouteImport.update({
  id: '/input',
  path: '/input',
  getParentRoute: () => AppPairingRoute,
} as any).lazy(() =>
  import('./routes/_app/pairing/input.lazy').then((d) => d.Route),
)
const AppPairingGenerateLazyRoute = AppPairingGenerateLazyRouteImport.update({
  id: '/generate',
  path: '/generate',
  getParentRoute: () => AppPairingRoute,
} as any).lazy(() =>
  import('./routes/_app/pairing/generate.lazy').then((d) => d.Route),
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/pairing': typeof AppPairingRouteWithChildren
  '/pairing/generate': typeof AppPairingGenerateLazyRoute
  '/pairing/input': typeof AppPairingInputLazyRoute
  '/transfer/$sessionId': typeof AppTransferSessionIdLazyRoute
  '/send/': typeof AppSendIndexRoute
  '/devices/': typeof AppDevicesIndexLazyRoute
  '/pairing/': typeof AppPairingIndexLazyRoute
  '/receive/': typeof AppReceiveIndexLazyRoute
  '/settings/': typeof AppSettingsIndexLazyRoute
  '/transfer/': typeof AppTransferIndexLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/pairing/generate': typeof AppPairingGenerateLazyRoute
  '/pairing/input': typeof AppPairingInputLazyRoute
  '/transfer/$sessionId': typeof AppTransferSessionIdLazyRoute
  '/send': typeof AppSendIndexRoute
  '/devices': typeof AppDevicesIndexLazyRoute
  '/pairing': typeof AppPairingIndexLazyRoute
  '/receive': typeof AppReceiveIndexLazyRoute
  '/settings': typeof AppSettingsIndexLazyRoute
  '/transfer': typeof AppTransferIndexLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/pairing': typeof AppPairingRouteWithChildren
  '/_app/pairing/generate': typeof AppPairingGenerateLazyRoute
  '/_app/pairing/input': typeof AppPairingInputLazyRoute
  '/_app/transfer/$sessionId': typeof AppTransferSessionIdLazyRoute
  '/_app/send/': typeof AppSendIndexRoute
  '/_app/devices/': typeof AppDevicesIndexLazyRoute
  '/_app/pairing/': typeof AppPairingIndexLazyRoute
  '/_app/receive/': typeof AppReceiveIndexLazyRoute
  '/_app/settings/': typeof AppSettingsIndexLazyRoute
  '/_app/transfer/': typeof AppTransferIndexLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/pairing'
    | '/pairing/generate'
    | '/pairing/input'
    | '/transfer/$sessionId'
    | '/send/'
    | '/devices/'
    | '/pairing/'
    | '/receive/'
    | '/settings/'
    | '/transfer/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/pairing/generate'
    | '/pairing/input'
    | '/transfer/$sessionId'
    | '/send'
    | '/devices'
    | '/pairing'
    | '/receive'
    | '/settings'
    | '/transfer'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/pairing'
    | '/_app/pairing/generate'
    | '/_app/pairing/input'
    | '/_app/transfer/$sessionId'
    | '/_app/send/'
    | '/_app/devices/'
    | '/_app/pairing/'
    | '/_app/receive/'
    | '/_app/settings/'
    | '/_app/transfer/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/pairing': {
      id: '/_app/pairing'
      path: '/pairing'
      fullPath: '/pairing'
      preLoaderRoute: typeof AppPairingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/transfer/': {
      id: '/_app/transfer/'
      path: '/transfer'
      fullPath: '/transfer/'
      preLoaderRoute: typeof AppTransferIndexLazyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/': {
      id: '/_app/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AppSettingsIndexLazyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/receive/': {
      id: '/_app/receive/'
      path: '/receive'
      fullPath: '/receive/'
      preLoaderRoute: typeof AppReceiveIndexLazyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pairing/': {
      id: '/_app/pairing/'
      path: '/'
      fullPath: '/pairing/'
      preLoaderRoute: typeof AppPairingIndexLazyRouteImport
      parentRoute: typeof AppPairingRoute
    }
    '/_app/devices/': {
      id: '/_app/devices/'
      path: '/devices'
      fullPath: '/devices/'
      preLoaderRoute: typeof AppDevicesIndexLazyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/send/': {
      id: '/_app/send/'
      path: '/send'
      fullPath: '/send/'
      preLoaderRoute: typeof AppSendIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/transfer/$sessionId': {
      id: '/_app/transfer/$sessionId'
      path: '/transfer/$sessionId'
      fullPath: '/transfer/$sessionId'
      preLoaderRoute: typeof AppTransferSessionIdLazyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pairing/input': {
      id: '/_app/pairing/input'
      path: '/input'
      fullPath: '/pairing/input'
      preLoaderRoute: typeof AppPairingInputLazyRouteImport
      parentRoute: typeof AppPairingRoute
    }
    '/_app/pairing/generate': {
      id: '/_app/pairing/generate'
      path: '/generate'
      fullPath: '/pairing/generate'
      preLoaderRoute: typeof AppPairingGenerateLazyRouteImport
      parentRoute: typeof AppPairingRoute
    }
  }
}

interface AppPairingRouteChildren {
  AppPairingGenerateLazyRoute: typeof AppPairingGenerateLazyRoute
  AppPairingInputLazyRoute: typeof AppPairingInputLazyRoute
  AppPairingIndexLazyRoute: typeof AppPairingIndexLazyRoute
}

const AppPairingRouteChildren: AppPairingRouteChildren = {
  AppPairingGenerateLazyRoute: AppPairingGenerateLazyRoute,
  AppPairingInputLazyRoute: AppPairingInputLazyRoute,
  AppPairingIndexLazyRoute: AppPairingIndexLazyRoute,
}

const AppPairingRouteWithChildren = AppPairingRoute._addFileChildren(
  AppPairingRouteChildren,
)

interface AppRouteChildren {
  AppPairingRoute: typeof AppPairingRouteWithChildren
  AppTransferSessionIdLazyRoute: typeof AppTransferSessionIdLazyRoute
  AppSendIndexRoute: typeof AppSendIndexRoute
  AppDevicesIndexLazyRoute: typeof AppDevicesIndexLazyRoute
  AppReceiveIndexLazyRoute: typeof AppReceiveIndexLazyRoute
  AppSettingsIndexLazyRoute: typeof AppSettingsIndexLazyRoute
  AppTransferIndexLazyRoute: typeof AppTransferIndexLazyRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppPairingRoute: AppPairingRouteWithChildren,
  AppTransferSessionIdLazyRoute: AppTransferSessionIdLazyRoute,
  AppSendIndexRoute: AppSendIndexRoute,
  AppDevicesIndexLazyRoute: AppDevicesIndexLazyRoute,
  AppReceiveIndexLazyRoute: AppReceiveIndexLazyRoute,
  AppSettingsIndexLazyRoute: AppSettingsIndexLazyRoute,
  AppTransferIndexLazyRoute: AppTransferIndexLazyRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
