/* tslint:disable */
/* eslint-disable */
/**
 * The `ReadableStreamType` enum.
 *
 * *This API requires the following crate features to be activated: `ReadableStreamType`*
 */

type ReadableStreamType = "bytes";
// 由 `cargo test -p swarmdrop-web --features specta --test specta_export` 生成，勿手改。
// 形状与运行期 serde_wasm_bindgen 序列化一致（u64 等已映射为 number）。

// This file has been generated by Specta. Do not edit this file manually.
/**  `connect()` 的结构化返回。 */
export type ConnectionJson = {
    path: PathKindJson,
    addr: string,
};

/**
 *  接收端保存位置（host-agnostic）。
 *
 *  core 内部统一用此类型，避免把 `entity::SaveLocation`（SeaORM 实体细节）
 *  暴露到公共 API 上。DB 边界用 [`From`] 与 `entity::SaveLocation` 双向转换。
 */
export type CoreSaveLocation =
/**  文件系统绝对路径（桌面）或 `Paths.document` 子路径（移动端）。 */
{ type: "path"; path: string };

/**  传输文件元信息。 */
export type FileInfo = {
    fileId: number,
    name: string,
    relativePath: string,
    size: number,
    checksum: string,
};

export type FileProgressInfo = {
    fileId: number,
    name: string,
    size: number,
    transferred: number,
    status: FileTransferStatus,
};

export type FileTransferStatus = "pending" | "transferring" | "completed";

/**  挂起 offer 的 JS 投影（`pending_offers()` 返回 `OfferJson[]`）。 */
export type OfferJson = {
    sessionId: string,
    peerId: string,
    peerName: string,
    totalSize: number,
    files: FileInfo[],
};

/**  Offer 被拒绝的原因。 */
export type OfferRejectReason = { type: "not_paired" } | { type: "user_declined" } | { type: "policy_rejected" } |
/**  接收方处于全局「暂停接收」状态，婉拒新 offer。 */
{ type: "receiving_paused" };

/**  连接路径类别（[`swarmdrop_net_base::PathKind`] 的 JS 投影，TS 侧是字符串联合）。 */
export type PathKindJson = "local" | "direct" | "relayed";

/**
 *  挂起入站配对请求的 JS 投影（`pending_pairing_requests()` 返回）。
 *
 *  browser-as-inviter 用：桌面消费浏览器生成的 invite 后，浏览器（邀请方）本机需弹确认。
 *  `pendingId` 以字符串承载核心的 u64 pending id（避免 JS number 精度 + serde_wasm_bindgen
 *  对 u64 产 BigInt 的取回麻烦），`respond_pairing_request` 再 parse 回 u64。
 */
export type PendingPairingJson = {
    pendingId: string,
    peerId: string,
    deviceName: string,
};

/**  `prepare_send` 的 hash 进度事件 */
export type PrepareProgressEvent = {
    /**  用于区分并发 prepare（多用户在不同会话同时调用） */
    preparedId: string,
    /**  当前正在 hash 的文件名 */
    currentFile: string,
    /**  已完成 hash 的文件数 */
    completedFiles: number,
    /**  总文件数 */
    totalFiles: number,
    /**  累积已 hash 的字节数（所有文件） */
    bytesHashed: number,
    /**  总字节数（所有文件） */
    totalBytes: number,
};

/**  单个 relay 意图的状态快照（`relays_state()` 元素 / `relays_changed()` 流的产出单元）。 */
export type RelayInfoJson = {
    /**  relay 节点身份（base58 NodeId）。 */
    id: string,
    state: RelayStateKind,
    /**  `active` 时为本机经该 relay 的完整可达地址（内核拼装下发），其余为 null。 */
    circuitAddr: string | null,
    /**  尝试轮数（`connecting` = 当前第几轮；`failed` = 累计轮数；`active` = 0）。 */
    attempts: number,
    /**  `failed` 时的末次错误描述，其余为 null。 */
    lastError: string | null,
};

/**  relay reservation 状态类别（[`swarmdrop_net::RelayState`] 的 JS 投影，TS 侧字符串联合）。 */
export type RelayStateKind = "connecting" | "active" | "failed";

export type RuntimeTransferDirection = "send" | "receive" | "unknown";

/**  suspended 原因（phase=Suspended 时有值）。 */
export type SuspendedReason = "local_paused" | "remote_paused" | "interrupted" | "peer_offline" | "app_restarted";

/**  terminal 原因（phase=Terminal 时有值）。 */
export type TerminalReason = "completed" | "cancelled" | "rejected" | "fatal_error";

/**  对方接受 Offer 的事件 payload */
export type TransferAcceptedEvent = {
    sessionId: string,
};

export type TransferCompleteEvent = {
    sessionId: string,
    direction: RuntimeTransferDirection,
    totalBytes: number,
    elapsedMs: number,
    saveLocation: CoreSaveLocation | null,
};

export type TransferDbErrorEvent = {
    sessionId: string,
    message: string,
};

/**  传输方向 */
export type TransferDirection = "send" | "receive";

export type TransferFailedEvent = {
    sessionId: string,
    direction: RuntimeTransferDirection,
    error: string,
};

export type TransferOfferEvent = {
    sessionId: string,
    peerId: string,
    deviceName: string,
    files: TransferOfferFileEvent[],
    totalSize: number,
    /**  发起来源（人工 / MCP 代理），供接收端 UI 标识。 */
    origin: TransferOrigin,
    policyAction: string | null,
    policyReason: string | null,
};

export type TransferOfferFileEvent = {
    fileId: number,
    name: string,
    relativePath: string,
    size: number,
    isDirectory: boolean,
};

/**
 *  传输发起来源：人在应用内发起，或 AI 代理经 MCP 发起。
 *
 *  由发送方自报、承载于 Offer，供接收端展示与 inbox 来源派生——是信息性/UX 信号，
 *  不作接收端安全边界（真正的控制是发送端 `allow_mcp_send_to_device` 门控）。
 */
export type TransferOrigin =
/**  用户在应用内手动发起。 */
{ type: "human" } |
/**  AI 代理经 MCP 发起；`client` 为 MCP 客户端名（如 claude-desktop），不可得时为 None。 */
{ type: "mcp"; client: string | null };

export type TransferPausedEvent = {
    sessionId: string,
    direction: RuntimeTransferDirection,
};

/**
 *  传输生命周期大状态（phase）。
 *  替代旧的扁平 [`SessionStatus`]（过渡期并存）：phase 表达大状态，
 *  具体原因由 [`SuspendedReason`] / [`TerminalReason`] 表达。
 */
export type TransferPhase = "offered" | "waiting_accept" | "active" | "suspended" | "terminal";

export type TransferProgressEvent = {
    sessionId: string,
    direction: RuntimeTransferDirection,
    totalFiles: number,
    completedFiles: number,
    totalBytes: number,
    transferredBytes: number,
    speed: number | null,
    eta: number | null,
    files: FileProgressInfo[],
};

/**  传输投影 DTO —— 前端唯一状态源（逐步替代旧的分散事件 + 扁平 `SessionStatus`）。 */
export type TransferProjection = {
    sessionId: string,
    direction: TransferDirection,
    peerId: string,
    peerName: string,
    phase: TransferPhase,
    suspendedReason: SuspendedReason | null,
    terminalReason: TerminalReason | null,
    recoverable: boolean,
    epoch: number,
    totalSize: number,
    transferredBytes: number,
    startedAt: number,
    updatedAt: number,
    finishedAt: number | null,
    errorMessage: string | null,
    policyAction: string | null,
    policyReason: string | null,
    savePath: CoreSaveLocation | null,
    /**
     *  「打开文件夹」应定位的真实容器目录 URI(收到内容实际所在的文件夹),已在 core 解析:
     *  各文件 `local_dir` 全部同一目录 → 该目录;否则回退存储根 `save_path`。前端直读,
     *  不再自行兜底(已完成接收必为 `Some`)。
     */
    contentRoot: string | null,
    files: TransferProjectionFile[],
};

export type TransferProjectionFile = {
    fileId: number,
    name: string,
    relativePath: string,
    size: number,
    transferredBytes: number,
};

/**  对方拒绝 Offer 的事件 payload */
export type TransferRejectedEvent = {
    sessionId: string,
    reason: OfferRejectReason | null,
};

export type TransferResumedEvent = {
    sessionId: string,
    direction: RuntimeTransferDirection,
    peerId: string,
    peerName: string,
    files: TransferResumedFileInfo[],
    totalSize: number,
};

export type TransferResumedFileInfo = {
    fileId: number,
    name: string,
    relativePath: string,
    size: number,
    isDirectory: boolean,
};

/**
 *  Web 壳对外错误。`kind` 供 JS 分支，`message` 供展示。
 *
 *  wasm-bindgen 方法 reject 的错误值就是本类型的序列化对象（`{ kind, message }`）——
 *  **不拍成字符串**（字符串丢了机器可判别的 kind）。JsValue 转换在 `error.rs`。
 */
export type WebError =
/**  身份 / 密钥错误。 */
{ kind: "identity"; message: string } |
/**  网络 / 连接 / DHT 错误。 */
{ kind: "network"; message: string } |
/**  传输错误。 */
{ kind: "transfer"; message: string } |
/**  入参非法（地址格式、缺 `/p2p/` 等）。 */
{ kind: "invalidInput"; message: string } |
/**
 *  调用被 `AbortSignal` 取消。**abort ≠ 撤回拨号**：Promise 立即 reject 且
 *  无常驻意图残留，但在途拨号会继续到自然失败（libp2p 无逐次拨号取消面）。
 */
{ kind: "aborted"; message: string } |
/**  分享码不存在 / 已过期。 */
{ kind: "notFound"; message: string } |
/**  存储（OPFS / localStorage）错误。 */
{ kind: "storage"; message: string };

/**
 *  `TransferEvent` 的可序列化镜像（1:1 变体，字段与 payload 同名）。
 *
 *  `TransferEvent` 本身未 derive `Serialize`（transfer 不改）——与桌面把它映射进
 *  `CoreEvent` 的适配范式一致。`events()` 的 ReadableStream 逐条产出本类型的序列化对象。
 */
export type WebTransferEvent = { type: "transferOfferReceived"; offer: TransferOfferEvent } | { type: "transferProgress"; event: TransferProgressEvent } | { type: "transferAccepted"; event: TransferAcceptedEvent } | { type: "transferRejected"; event: TransferRejectedEvent } | { type: "transferCompleted"; event: TransferCompleteEvent } | { type: "transferFailed"; event: TransferFailedEvent } | { type: "transferPaused"; event: TransferPausedEvent } | { type: "transferResumed"; event: TransferResumedEvent } | { type: "transferDbError"; event: TransferDbErrorEvent } | { type: "transferProjection"; projection: TransferProjection } | { type: "prepareProgress"; event: PrepareProgressEvent };



export class IntoUnderlyingByteSource {
    private constructor();
    free(): void;
    [Symbol.dispose](): void;
    cancel(): void;
    pull(controller: ReadableByteStreamController): Promise<any>;
    start(controller: ReadableByteStreamController): void;
    readonly autoAllocateChunkSize: number;
    readonly type: ReadableStreamType;
}

export class IntoUnderlyingSink {
    private constructor();
    free(): void;
    [Symbol.dispose](): void;
    abort(reason: any): Promise<any>;
    close(): Promise<any>;
    write(chunk: any): Promise<any>;
}

export class IntoUnderlyingSource {
    private constructor();
    free(): void;
    [Symbol.dispose](): void;
    cancel(): void;
    pull(controller: ReadableStreamDefaultController): Promise<any>;
}

/**
 * 浏览器传输端节点。
 */
export class WebNode {
    private constructor();
    free(): void;
    [Symbol.dispose](): void;
    /**
     * 接受入站 offer 并开始接收（落 OPFS）。
     */
    accept_offer(session_id: string): Promise<void>;
    /**
     * 关停节点：NetManager::shutdown 取消内部 token（停 presence / infra / event-loop +
     * transfer cleanup，drop Router 停路由）并关 Endpoint（drop Swarm → 断连）——
     * 与 `WebNode.endpoint` 是同一 handle，无需再显式关一次。
     */
    close(): Promise<void>;
    /**
     * 拨任意 multiaddr（`.../ws` 或 `.../webrtc-direct/certhash/...`，须带 `/p2p/<id>`）。
     * 返回结构化的连接信息（`{ path: "local"|"direct"|"relayed", addr }`）。
     *
     * `signal`（可选）：标准 `AbortSignal`——超时组合用平台原语表达
     * （`AbortSignal.timeout(5000)` / `AbortSignal.any([...])`）。abort 时 Promise
     * 立即以 `{ kind: "aborted" }` reject；**abort ≠ 撤回拨号**（在途拨号继续到
     * 自然失败，无常驻意图残留）。不传 signal 时由内核兜底超时（Browser 15s）
     * 保证有限时间内 settle。
     */
    connect(addr: string, signal?: AbortSignal | null): Promise<ConnectionJson>;
    /**
     * 受邀方：消费邀请串完成**真配对握手**。
     *
     * `pair_with_invite` 解码验签 → TTL 预检 → 按 `TransportPolicy` 过滤地址 → 连邀请方出示
     * capability（`PairingMethod::Invite`）→ 邀请方（桌面）校验 CAS 一次性消费 + 用户确认 →
     * 双方写配对记录。身份 pin 由握手强制（连到的必然是 `inviter_id`）。成功返回已配对对端的
     * NodeId（base58）；确认发生在**邀请方**侧，浏览器侧无需交互。配对后该对端进入本机信任
     * 表，双向传输（收 / 发）不再被 `NotPaired` 拦。
     */
    connect_invite(invite: string): Promise<string>;
    /**
     * 完成接收后，把 OPFS 里的文件读回成 blob URL 供 `<a download>` 下载。
     */
    download_url(relative_path: string): Promise<string>;
    /**
     * 传输事件流（逐条产出 `WebTransferEvent` 序列化对象）。**只能取一次**（单点消费）。
     */
    events(): ReadableStream<WebTransferEvent>;
    /**
     * 发起方（browser-as-inviter）：生成一次性签名邀请串，供桌面/移动扫码或粘贴消费。
     *
     * `local_only=true` 走 LocalOnly（受邀方只用私网地址）。邀请自包含本机 dialable 地址提示——
     * 浏览器不 listen 本地 socket，其可达地址来自 **relay reservation**（circuit 地址）；故桌面要
     * 拨得到本机，本机需先经 [`relays_ensure`](Self::relays_ensure) 在某 helper 上建 reservation
     * （等到 `active`），否则邀请里无可拨地址、消费方连不上。
     */
    generate_invite(local_only: boolean): string;
    /**
     * 本节点身份（base58）。
     */
    node_id(): string;
    /**
     * 当前挂起（待确认）的入站 offer 列表。
     */
    pending_offers(): OfferJson[];
    /**
     * 挂起的入站配对请求（消费方扫/粘本机 invite 后到达）。**取出即清空**，调用方自行累积展示。
     */
    pending_pairing_requests(): PendingPairingJson[];
    /**
     * 拒绝入站 offer。
     */
    reject_offer(session_id: string): Promise<void>;
    /**
     * relay 状态变化流：每次变化产出一份全量快照（可直接 setState）。
     * 可多次调用（每次独立订阅），与 `events()` 的单点消费不同。
     */
    relays_changed(): ReadableStream<RelayInfoJson[]>;
    /**
     * 撤销 relay 意图（[`relays_ensure`](Self::relays_ensure) 的对称面）。
     *
     * **真撤销**而非停止等待：停止后台收敛重试、关闭 circuit listener、立刻
     * 断开与该 helper 的连接（含中止在途拨号），条目从状态集合消失。
     */
    relays_drop(helper_id: string): Promise<void>;
    /**
     * 登记一个 relay helper 的常驻可达意图（幂等，同步返回）。
     *
     * 浏览器被动接收连接的唯一入口。拨号 / reservation / 断线重建由 core 的
     * InfraSupervisor 统一收敛（最迟 1s 内启动第一轮，失败退避重试）；进度经
     * [`relays_state`](Self::relays_state) / [`relays_changed`](Self::relays_changed)
     * 观测，或用 [`relays_until_active`](Self::relays_until_active) 等首次建立。
     *
     * 返回 helper 的 base58 NodeId——即 `relays_drop` / `relays_until_active` 的
     * 入参，调用方直接串联，无需自行解析 multiaddr 的 `/p2p/` 段。
     */
    relays_ensure(helper_addr: string): string;
    /**
     * 全量 relay 状态快照（`{ id, state, circuitAddr?, attempts, lastError? }[]`）。
     */
    relays_state(): RelayInfoJson[];
    /**
     * 等待某 relay 首次进入 `active`，resolve 出 circuit 可达地址（内核拼装）。
     *
     * 观察到 `failed` 时**立即 reject**（把「要不要再等下一轮退避」还给调用方），
     * 意图保留——要停止后台收敛请调 [`relays_drop`](Self::relays_drop)。
     * `signal`（可选）：abort 只是不再等待，同样不改变意图生命周期。
     * 不传 signal 时 30s 兜底超时保证 Promise 有限时间内 settle。
     */
    relays_until_active(helper_id: string, signal?: AbortSignal | null): Promise<string>;
    /**
     * 响应一个入站配对请求（`accept=true` 接受并写配对记录、CAS 消费 invite / `false` 拒绝）。
     */
    respond_pairing_request(pending_id: string, accept: boolean): Promise<void>;
    /**
     * 手动发起断点续传（对某 suspended 会话）。
     */
    resume(session_id: string): Promise<void>;
    /**
     * 向 `to`（base58 NodeId）发送用户选择的文件：登记文件源 → prepare（checksum + bao
     * outboard）→ 发 Offer。返回 session_id。
     */
    send_files(to: string, files: File[]): Promise<string>;
    /**
     * 建节点：持久化身份（Window=localStorage / Worker=OPFS）→ 包 core 组合根 [`start_node`]
     * （Browser [`EndpointProfile`] + Web 端口）→ 完整 [`NetManager`] + 3 协议 Router（含
     * pairing）。**须在主线程 Window 跑**——webrtc-websys dial 碰 window，Worker 里会 panic。
     */
    static spawn(): Promise<WebNode>;
}

/**
 * wasm 模块加载即初始化 panic hook + tracing（浏览器 console）。
 */
export function start(): void;

export type InitInput = RequestInfo | URL | Response | BufferSource | WebAssembly.Module;

export interface InitOutput {
    readonly memory: WebAssembly.Memory;
    readonly start: () => void;
    readonly __wbg_webnode_free: (a: number, b: number) => void;
    readonly webnode_accept_offer: (a: number, b: number, c: number) => any;
    readonly webnode_close: (a: number) => any;
    readonly webnode_connect: (a: number, b: number, c: number, d: number) => any;
    readonly webnode_connect_invite: (a: number, b: number, c: number) => any;
    readonly webnode_download_url: (a: number, b: number, c: number) => any;
    readonly webnode_events: (a: number) => [number, number, number];
    readonly webnode_generate_invite: (a: number, b: number) => [number, number, number, number];
    readonly webnode_node_id: (a: number) => [number, number];
    readonly webnode_pending_offers: (a: number) => [number, number, number];
    readonly webnode_pending_pairing_requests: (a: number) => [number, number, number];
    readonly webnode_reject_offer: (a: number, b: number, c: number) => any;
    readonly webnode_relays_changed: (a: number) => any;
    readonly webnode_relays_drop: (a: number, b: number, c: number) => any;
    readonly webnode_relays_ensure: (a: number, b: number, c: number) => [number, number, number, number];
    readonly webnode_relays_state: (a: number) => [number, number, number];
    readonly webnode_relays_until_active: (a: number, b: number, c: number, d: number) => any;
    readonly webnode_respond_pairing_request: (a: number, b: number, c: number, d: number) => any;
    readonly webnode_resume: (a: number, b: number, c: number) => any;
    readonly webnode_send_files: (a: number, b: number, c: number, d: number, e: number) => any;
    readonly webnode_spawn: () => any;
    readonly __wbg_intounderlyingbytesource_free: (a: number, b: number) => void;
    readonly __wbg_intounderlyingsink_free: (a: number, b: number) => void;
    readonly intounderlyingbytesource_autoAllocateChunkSize: (a: number) => number;
    readonly intounderlyingbytesource_cancel: (a: number) => void;
    readonly intounderlyingbytesource_pull: (a: number, b: any) => any;
    readonly intounderlyingbytesource_start: (a: number, b: any) => void;
    readonly intounderlyingbytesource_type: (a: number) => number;
    readonly intounderlyingsink_abort: (a: number, b: any) => any;
    readonly intounderlyingsink_close: (a: number) => any;
    readonly intounderlyingsink_write: (a: number, b: any) => any;
    readonly __wbg_intounderlyingsource_free: (a: number, b: number) => void;
    readonly intounderlyingsource_cancel: (a: number) => void;
    readonly intounderlyingsource_pull: (a: number, b: any) => any;
    readonly wasm_bindgen_68a07cbe32b35190___closure__destroy___dyn_core_7d5f0a2ba6a62c33___ops__function__FnMut_____Output_______: (a: number, b: number) => void;
    readonly wasm_bindgen_68a07cbe32b35190___closure__destroy___dyn_core_7d5f0a2ba6a62c33___ops__function__FnMut__web_sys_55f879203fe08ada___features__gen_CloseEvent__CloseEvent____Output_______: (a: number, b: number) => void;
    readonly wasm_bindgen_68a07cbe32b35190___closure__destroy___dyn_core_7d5f0a2ba6a62c33___ops__function__FnMut__web_sys_55f879203fe08ada___features__gen_MessageEvent__MessageEvent____Output_______: (a: number, b: number) => void;
    readonly wasm_bindgen_68a07cbe32b35190___closure__destroy___dyn_core_7d5f0a2ba6a62c33___ops__function__FnMut__wasm_bindgen_68a07cbe32b35190___JsValue____Output_______: (a: number, b: number) => void;
    readonly wasm_bindgen_68a07cbe32b35190___closure__destroy___dyn_core_7d5f0a2ba6a62c33___ops__function__FnMut_____Output________1_: (a: number, b: number) => void;
    readonly wasm_bindgen_68a07cbe32b35190___convert__closures_____invoke___wasm_bindgen_68a07cbe32b35190___JsValue__wasm_bindgen_68a07cbe32b35190___JsValue_____: (a: number, b: number, c: any, d: any) => void;
    readonly wasm_bindgen_68a07cbe32b35190___convert__closures_____invoke___web_sys_55f879203fe08ada___features__gen_CloseEvent__CloseEvent_____: (a: number, b: number, c: any) => void;
    readonly wasm_bindgen_68a07cbe32b35190___convert__closures_____invoke___web_sys_55f879203fe08ada___features__gen_MessageEvent__MessageEvent_____: (a: number, b: number, c: any) => void;
    readonly wasm_bindgen_68a07cbe32b35190___convert__closures_____invoke___wasm_bindgen_68a07cbe32b35190___JsValue_____: (a: number, b: number, c: any) => void;
    readonly wasm_bindgen_68a07cbe32b35190___convert__closures_____invoke______: (a: number, b: number) => void;
    readonly wasm_bindgen_68a07cbe32b35190___convert__closures_____invoke_______1_: (a: number, b: number) => void;
    readonly __wbindgen_malloc: (a: number, b: number) => number;
    readonly __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
    readonly __wbindgen_exn_store: (a: number) => void;
    readonly __externref_table_alloc: () => number;
    readonly __wbindgen_externrefs: WebAssembly.Table;
    readonly __externref_drop_slice: (a: number, b: number) => void;
    readonly __wbindgen_free: (a: number, b: number, c: number) => void;
    readonly __externref_table_dealloc: (a: number) => void;
    readonly __wbindgen_start: () => void;
}

export type SyncInitInput = BufferSource | WebAssembly.Module;

/**
 * Instantiates the given `module`, which can either be bytes or
 * a precompiled `WebAssembly.Module`.
 *
 * @param {{ module: SyncInitInput }} module - Passing `SyncInitInput` directly is deprecated.
 *
 * @returns {InitOutput}
 */
export function initSync(module: { module: SyncInitInput } | SyncInitInput): InitOutput;

/**
 * If `module_or_path` is {RequestInfo} or {URL}, makes a request and
 * for everything else, calls `WebAssembly.instantiate` directly.
 *
 * @param {{ module_or_path: InitInput | Promise<InitInput> }} module_or_path - Passing `InitInput` directly is deprecated.
 *
 * @returns {Promise<InitOutput>}
 */
export default function __wbg_init (module_or_path?: { module_or_path: InitInput | Promise<InitInput> } | InitInput | Promise<InitInput>): Promise<InitOutput>;
